(function(root){
'use strict';
const DATA='/prison-age/engine-atlas.json',esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let pack=null,held=null,filter='ALL',route=[],overlay=null;
const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0');
function style(){
 if($('prisonAgeAtlasStyle'))return;
 const s=document.createElement('style');s.id='prisonAgeAtlasStyle';s.textContent=`
 .paAtlas{position:fixed;z-index:80;inset:0;background:#0b0b0af7;color:#efeee9;overflow:auto;padding:max(10px,env(safe-area-inset-top)) 12px max(70px,env(safe-area-inset-bottom));font:10px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace}
 .paAtlas[hidden]{display:none}.paHead{position:sticky;top:0;z-index:2;display:flex;justify-content:space-between;gap:10px;align-items:end;padding:8px 0;background:#0b0b0af0;border-bottom:1px solid #383b38}.paEy{font-size:7px;letter-spacing:.16em;color:#e86f43}.paHead h2{margin:2px 0;font:900 clamp(28px,6vw,58px)/.86 system-ui,sans-serif;letter-spacing:-.06em}.paClose,.paAtlas button{border:1px solid #414641;background:#101210;color:inherit;border-radius:0;padding:8px;cursor:pointer}
 .paLaw{padding:9px 0;color:#9ba29d;max-width:900px}.paLaw b{color:#e86f43}.paFilters{display:flex;gap:4px;overflow:auto;padding:7px 0}.paFilters button{white-space:nowrap}.paFilters button.on{background:#efeee9;color:#111}
 .paWork{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:10px}.paGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-left:1px solid #343834;border-top:1px solid #343834}.paCard{text-align:left;min-height:150px;border:0!important;border-right:1px solid #343834!important;border-bottom:1px solid #343834!important;background:#111311!important;padding:10px!important;display:grid;gap:6px;align-content:start}.paCard.on{background:#efeee9!important;color:#141414!important}.paNum{font:800 22px/1 system-ui,sans-serif}.paEngine{color:#e86f43;font-size:7px;letter-spacing:.12em}.paTitle{font:800 14px/1.05 system-ui,sans-serif}.paMeta{color:#8c958e;font-size:7px;margin-top:auto}
 .paHeld{position:sticky;top:76px;align-self:start;border:1px solid #454945;background:#151715;padding:12px;min-height:360px}.paHeld h3{font:900 28px/.95 system-ui,sans-serif;margin:8px 0}.paBlock{border-top:1px solid #373b37;padding:9px 0}.paBlock b{display:block;color:#9ba29d;font-size:7px;letter-spacing:.12em;margin-bottom:4px}.paBlock p{margin:0;font:15px/1.38 Georgia,serif}.paEcho{display:flex;gap:4px;flex-wrap:wrap}.paRoute{position:fixed;left:0;right:0;bottom:0;z-index:82;background:#161816eF;border-top:1px solid #444;padding:8px max(12px,calc((100vw - 1120px)/2));display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.paSlots{display:grid;grid-template-columns:repeat(3,1fr);gap:4px}.paSlot{text-align:left}.paSlot span{display:block;color:#858d86;font-size:6px}.paRouteActions{display:flex;gap:4px}.paRouteActions button{min-width:78px}.paCopy{border-color:#e86f43!important;color:#ffd2c2!important}
 @media(max-width:850px){.paWork{grid-template-columns:1fr}.paGrid{grid-template-columns:repeat(2,minmax(0,1fr))}.paHeld{position:relative;top:auto}.paRoute{grid-template-columns:1fr}.paRouteActions button{flex:1}.paAtlas{padding-bottom:116px}}
 `;document.head.appendChild(s);
}
function card(n){return pack?.cards?.find(x=>x.n===n)||null}
function renderFilters(){const fs=['ALL',...new Set(pack.cards.map(c=>c.family))];$('paFilters').innerHTML=fs.map(f=>'<button data-f="'+esc(f)+'" class="'+(f===filter?'on':'')+'">'+esc(f)+'</button>').join('');$('paFilters').querySelectorAll('button').forEach(b=>b.onclick=()=>{filter=b.dataset.f;renderFilters();renderGrid()})}
function renderGrid(){const xs=pack.cards.filter(c=>filter==='ALL'||c.family===filter);$('paGrid').innerHTML=xs.map(c=>'<button class="paCard '+(held?.n===c.n?'on':'')+'" data-n="'+c.n+'"><span class="paNum">'+pad(c.n)+'</span><span class="paEngine">'+esc(c.engine)+' · '+esc(c.verb)+'</span><span class="paTitle">'+esc(c.title)+'</span><span class="paMeta">'+esc(c.family)+'</span></button>').join('');$('paGrid').querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>select(+b.dataset.n))}
function select(n){held=card(n)||held;if(!held)return;$('paHeldNum').textContent=pad(held.n);$('paHeldTitle').textContent=held.title;$('paHeldEngine').textContent=held.engine+' / '+held.verb;$('paOperator').textContent=held.operator;$('paTrace').textContent=held.trace;$('paEcho').innerHTML=(held.echo||[]).map(n=>'<button data-e="'+n+'">'+pad(n)+'</button>').join('');$('paEcho').querySelectorAll('button').forEach(b=>b.onclick=()=>select(+b.dataset.e));renderGrid()}
function renderRoute(){const labels=['HOLD','TURN','TRACE'];$('paSlots').innerHTML=labels.map((l,i)=>'<button class="paSlot" data-i="'+i+'" '+(route[i]?'':'disabled')+'><span>'+l+'</span><b>'+(route[i]?pad(route[i].n)+' · '+esc(route[i].verb):'—')+'</b></button>').join('');$('paSlots').querySelectorAll('button:not(:disabled)').forEach(b=>b.onclick=()=>select(route[+b.dataset.i].n));$('paCopy').disabled=!route.length}
function add(){if(!held)return;if(route.some(x=>x.n===held.n))return;if(route.length>=3)route.shift();route.push(held);renderRoute()}
function packet(){return{schema:'prison-age.engine-route/v0.1',created_at:new Date().toISOString(),authority:'NONE / CREATIVE CONSTRAINT SURFACE',source:{host:'/prison-age/',atlas:DATA},law:pack.law,route:route.map((c,i)=>({phase:['HOLD','TURN','TRACE'][i],engine:c.n,title:c.title,engine_name:c.engine,verb:c.verb,operator:c.operator,trace:c.trace})),return:{instruction:'Return to the original addressed problem. Record one observed delta, one unresolved uncertainty, and whether the chosen operator should be kept, revised or dropped.'}}}
async function copy(){const txt=JSON.stringify(packet(),null,2);try{await navigator.clipboard.writeText(txt);$('paCopy').textContent='COPIED';setTimeout(()=>$('paCopy').textContent='COPY PACKET',800)}catch(_){prompt('Copy packet:',txt)}}
function open(){if(!overlay)return;overlay.hidden=false;document.body.style.overflow='hidden';if(!held)select(25)}
function close(){if(!overlay)return;overlay.hidden=true;document.body.style.overflow=''}
function build(){
 style();overlay=document.createElement('section');overlay.id='prisonAgeEngineAtlas';overlay.className='paAtlas';overlay.hidden=true;overlay.setAttribute('aria-label','Prison Age derived engine atlas');
 overlay.innerHTML='<div class="paHead"><div><div class="paEy">DERIVED APERTURE · AUTHORITY NONE</div><h2>ENGINE ATLAS · 01—32</h2></div><button id="paClose" class="paClose">RETURN SOURCE</button></div><div class="paLaw"><b>BOUNDARY</b> · Generated panels ≠ source prose ≠ canon ≠ proof. Hold one lens; compose ≤3 constraints; only observed consequences become evidence.</div><div id="paFilters" class="paFilters"></div><div class="paWork"><div id="paGrid" class="paGrid"></div><aside class="paHeld"><div class="paEy">φ HELD ENGINE · <span id="paHeldNum">—</span></div><h3 id="paHeldTitle">Choose an engine</h3><div id="paHeldEngine" class="paEngine">—</div><div class="paBlock"><b>TURN / OPERATOR</b><p id="paOperator">—</p></div><div class="paBlock"><b>TRACE / WHAT WOULD COUNT</b><p id="paTrace">—</p></div><div class="paBlock"><b>ECHO / RELATED</b><div id="paEcho" class="paEcho"></div></div><button id="paAdd">ADD TO ROUTE</button></aside></div><footer class="paRoute"><div id="paSlots" class="paSlots"></div><div class="paRouteActions"><button id="paClear">CLEAR</button><button id="paCopy" class="paCopy" disabled>COPY PACKET</button></div></footer>';
 document.body.appendChild(overlay);$('paClose').onclick=close;$('paAdd').onclick=add;$('paClear').onclick=()=>{route=[];renderRoute()};$('paCopy').onclick=copy;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!overlay.hidden)close()});
 const trigger=$('engineAtlasBtn');if(trigger)trigger.onclick=open;
 fetch(DATA,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('ATLAS '+r.status);return r.json()}).then(x=>{pack=x;renderFilters();renderGrid();renderRoute();select(25);root.PrisonAgeEngineAtlas=Object.freeze({open,close,snapshot:()=>({held:held?.n||null,route:route.map(x=>x.n),authority:pack.authority})})}).catch(e=>{overlay.querySelector('.paLaw').textContent='ENGINE ATLAS UNAVAILABLE · '+String(e.message||e)});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build();
})(typeof globalThis!=='undefined'?globalThis:this);
