(function(root){
'use strict';
const DATA='/prison-age/evidence-atlas.json',esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let pack=null,held=null,filter='ALL',trail=[];const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0');
function readHref(x){const u=new URL('/docs/',location.origin);u.searchParams.set('src',x.path);u.searchParams.set('ap_scale','SENT');u.searchParams.set('ap_char',String(x.start));u.searchParams.set('echo','/prison-age/echo-index.json');u.searchParams.set('echo_source',x.source_id);u.searchParams.set('return',location.pathname+location.search);return u.pathname+u.search}
function style(){if($('paEvidenceStyle'))return;const s=document.createElement('style');s.id='paEvidenceStyle';s.textContent=`
.paEvidence{position:fixed;z-index:90;inset:0;background:#070908f7;color:#efeee9;overflow:auto;padding:max(10px,env(safe-area-inset-top)) 12px 110px;font:10px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace}.paEvidence[hidden]{display:none}.peaHead{position:sticky;top:0;z-index:2;display:flex;justify-content:space-between;gap:10px;align-items:end;padding:8px 0;background:#070908f3;border-bottom:1px solid #303936}.peaEy{font-size:7px;letter-spacing:.16em;color:#d6b36a}.peaHead h2{margin:2px 0;font:900 clamp(28px,6vw,58px)/.86 system-ui,sans-serif;letter-spacing:-.06em}.peaClose,.paEvidence button,.paEvidence a{border:1px solid #37413d;background:#0d100e;color:inherit;border-radius:0;padding:8px;text-decoration:none;cursor:pointer}.peaLaw{padding:9px 0;color:#8f9a95;max-width:920px}.peaLaw b{color:#d6b36a}.peaFilters{display:flex;gap:4px;overflow:auto;padding:7px 0}.peaFilters button{white-space:nowrap}.peaFilters button.on{background:#efeee9;color:#111}.peaWork{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,380px);gap:10px}.peaGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-left:1px solid #303936;border-top:1px solid #303936}.peaCard{text-align:left;min-height:138px;border:0!important;border-right:1px solid #303936!important;border-bottom:1px solid #303936!important;background:#0c100e!important;padding:9px!important;display:grid;gap:5px;align-content:start}.peaCard.on{background:#e9e7df!important;color:#111!important}.peaNum{font:800 20px/1 system-ui}.peaClass{color:#d6b36a;font-size:7px;letter-spacing:.12em}.peaPair{font:800 12px/1.08 system-ui}.peaTerms{font-size:7px;color:#8e9994;margin-top:auto}.peaHeld{position:sticky;top:78px;align-self:start;border:1px solid #414a46;background:#101311;padding:11px;min-height:360px}.peaHeld h3{font:900 25px/.95 system-ui;margin:7px 0}.peaFrag{border-top:1px solid #343d39;padding:8px 0}.peaFrag b{display:block;color:#8e9994;font-size:7px;letter-spacing:.12em;margin-bottom:4px}.peaFrag p{margin:0 0 6px;font:15px/1.35 Georgia,serif}.peaFrag .addr{font-size:6px;color:#76827c;overflow-wrap:anywhere}.peaEvidenceLine{border-top:1px solid #343d39;padding-top:8px;color:#c7d0cb}.peaEvidenceLine b{color:#d6b36a}.peaActions{display:flex;gap:4px;flex-wrap:wrap;margin-top:8px}.peaTrail{position:fixed;left:0;right:0;bottom:0;z-index:92;background:#101411ef;border-top:1px solid #414a46;padding:8px max(12px,calc((100vw - 1120px)/2));display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.peaSlots{display:grid;grid-template-columns:repeat(3,1fr);gap:4px}.peaSlot{text-align:left}.peaSlot span{display:block;color:#7f8a84;font-size:6px}.peaTrailActions{display:flex;gap:4px}.peaTrailActions button{min-width:78px}.peaCopy{border-color:#d6b36a!important;color:#efd99f!important}
@media(max-width:850px){.peaWork{grid-template-columns:1fr}.peaGrid{grid-template-columns:repeat(2,minmax(0,1fr))}.peaHeld{position:relative;top:auto}.peaTrail{grid-template-columns:1fr}.paEvidence{padding-bottom:145px}}`;document.head.appendChild(s)}
function card(n){return pack?.cards?.find(x=>x.n===n)||null}
function filterKey(c){return c.class}
function renderFilters(){const fs=['ALL','PHRASE','DENSE','TERM'];$('peaFilters').innerHTML=fs.map(f=>'<button data-f="'+f+'" class="'+(filter===f?'on':'')+'">'+f+'</button>').join('');$('peaFilters').querySelectorAll('button').forEach(b=>b.onclick=()=>{filter=b.dataset.f;renderFilters();renderGrid()})}
function renderGrid(){const xs=pack.cards.filter(c=>filter==='ALL'||filterKey(c)===filter);$('peaGrid').innerHTML=xs.map(c=>'<button class="peaCard '+(held?.n===c.n?'on':'')+'" data-n="'+c.n+'"><span class="peaNum">'+pad(c.n)+'</span><span class="peaClass">'+esc(c.class)+'</span><span class="peaPair">'+esc(c.a.title)+' ↔ '+esc(c.b.title)+'</span><span class="peaTerms">'+esc((c.phrases.length?c.phrases:c.shared).slice(0,4).join(' · '))+'</span></button>').join('');$('peaGrid').querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>select(+b.dataset.n))}
function frag(side,x){return '<div class="peaFrag"><b>'+side+' · '+esc(x.source_id)+'</b><p>“'+esc(x.text)+'”</p><div class="addr">'+esc(x.address)+'</div><div class="peaActions"><a href="'+esc(readHref(x))+'">READ '+side+'</a><a href="'+esc(x.path)+'">SOURCE '+side+'</a></div></div>'}
function select(n,{url=true}={}){held=card(n)||held;if(!held)return;$('peaHeldTitle').textContent=pad(held.n)+' · '+held.class;$('peaHeldPair').textContent=held.a.title+' ↔ '+held.b.title;$('peaFragments').innerHTML=frag('A',held.a)+frag('B',held.b);$('peaBasis').innerHTML='<b>EVIDENCE</b> · '+esc((held.phrases.length?'phrases '+held.phrases.join(' / ')+' · ':'')+'shared '+held.shared.join(' · ')+' · score '+held.score);renderGrid();if(url){const u=new URL(location.href);u.searchParams.set('atlas','evidence');u.searchParams.set('card',String(held.n));history.replaceState(null,'',u.pathname+u.search)}}
function renderTrail(){const labels=['HOLD','TURN','TRACE'];$('peaSlots').innerHTML=labels.map((l,i)=>'<button class="peaSlot" data-i="'+i+'" '+(trail[i]?'':'disabled')+'><span>'+l+'</span><b>'+(trail[i]?pad(trail[i].n)+' · '+esc(trail[i].class):'—')+'</b></button>').join('');$('peaSlots').querySelectorAll('button:not(:disabled)').forEach(b=>b.onclick=()=>select(trail[+b.dataset.i].n));$('peaCopy').disabled=!trail.length}
function add(){if(!held||trail.some(x=>x.n===held.n))return;if(trail.length>=3)trail.shift();trail.push(held);renderTrail()}
function packet(){return{schema:'prison-age.evidence-route/v0.1',created_at:new Date().toISOString(),authority:'EVIDENCE_ONLY',source_set:'PRISON_AGE',cards:trail.map(c=>({n:c.n,class:c.class,pair:c.pair,a:c.a.address,b:c.b.address,shared:c.shared,phrases:c.phrases})),returnAddress:location.pathname+location.search,law:pack.law}}
async function copy(){if(!trail.length)return;const x=JSON.stringify(packet(),null,2);try{await navigator.clipboard.writeText(x)}catch(_){const t=document.createElement('textarea');t.value=x;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}$('peaCopy').textContent='COPIED';setTimeout(()=>$('peaCopy').textContent='COPY TRAIL',900)}
function open(cardNo=null){$('paEvidence').hidden=false;const u=new URL(location.href);u.searchParams.set('atlas','evidence');if(cardNo)u.searchParams.set('card',String(cardNo));history.replaceState(null,'',u.pathname+u.search);select(cardNo||held?.n||1,{url:false})}
function close(){ $('paEvidence').hidden=true;const u=new URL(location.href);u.searchParams.delete('atlas');u.searchParams.delete('card');history.replaceState(null,'',u.pathname+u.search)}
async function init(){style();const box=document.createElement('section');box.id='paEvidence';box.className='paEvidence';box.hidden=true;box.innerHTML='<div class="peaHead"><div><div class="peaEy">PRISON AGE / SOURCE-DERIVED</div><h2>EVIDENCE ATLAS</h2></div><button class="peaClose" id="peaClose">RETURN SOURCE</button></div><div class="peaLaw"><b>EVIDENCE ONLY</b> · two exact fragments + shared lexical evidence. No card asserts meaning, causality or canon order.</div><div class="peaFilters" id="peaFilters"></div><div class="peaWork"><div class="peaGrid" id="peaGrid"></div><aside class="peaHeld"><div class="peaEy">HELD RELATION</div><h3 id="peaHeldTitle">—</h3><div id="peaHeldPair"></div><div id="peaFragments"></div><div class="peaEvidenceLine" id="peaBasis"></div><div class="peaActions"><button id="peaAdd">ADD TO TRAIL</button></div></aside></div><div class="peaTrail"><div class="peaSlots" id="peaSlots"></div><div class="peaTrailActions"><button id="peaClear">CLEAR</button><button class="peaCopy" id="peaCopy">COPY TRAIL</button></div></div>';document.body.appendChild(box);pack=await fetch(DATA,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('ATLAS '+r.status);return r.json()});renderFilters();renderGrid();renderTrail();$('peaClose').onclick=close;$('peaAdd').onclick=add;$('peaClear').onclick=()=>{trail=[];renderTrail()};$('peaCopy').onclick=copy;const q=new URLSearchParams(location.search);if(q.get('atlas')==='evidence')open(Number(q.get('card'))||1)}
function mount(){let b=$('evidenceAtlasBtn');if(!b){b=document.createElement('button');b.id='evidenceAtlasBtn';b.type='button';b.textContent='EVIDENCE ATLAS';const head=document.querySelector('.head');head?.insertBefore(b,head.lastElementChild)}b.onclick=()=>open(held?.n||1)}
root.PrisonAgeEvidenceAtlas=Object.freeze({open,close,select,add,packet,snapshot:()=>({held:held?JSON.parse(JSON.stringify(held)):null,trail:trail.map(x=>x.n),filter,visible:!$('paEvidence')?.hidden})});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>void init());else void init();
})(globalThis);