import assert from 'node:assert/strict';
import {parseSunoId,classifySourceAddress,resolveSourceAddress} from './source-adapters.js';
const id='11111111-2222-4333-8444-555555555555';
assert.equal(parseSunoId('https://suno.com/song/'+id),id);
assert.equal(parseSunoId(id),id);
assert.equal(parseSunoId('https://example.com/x.mp3'),null);
assert.equal(classifySourceAddress('https://example.com/x.mp3').kind,'REMOTE_AUDIO');
const fake=async()=>({ok:true,json:async()=>({title:'TEST',display_name:'ARTIST',audio_url:'https://cdn.example/test.mp3',metadata:{duration:123,tags:'test',prompt:'hello'}})});
const s=await resolveSourceAddress('https://suno.com/song/'+id,fake);
assert.equal(s.kind,'SUNO');assert.equal(s.title,'TEST');assert.equal(s.lyrics,'hello');assert.equal(s.resolution,'PUBLIC_CLIP_METADATA');
const fallback=await resolveSourceAddress(id,async()=>{throw Error('blocked')});
assert.equal(fallback.audioUrl,'https://cdn1.suno.ai/'+id+'.mp3');assert.equal(fallback.resolution,'UUID_CDN_FALLBACK');
console.log('LISTEN SOURCE ADAPTER SELFTEST PASS');
