(()=>{
'use strict';
const NS='http://www.w3.org/2000/svg',TAU=Math.PI*2,$=s=>document.querySelector(s),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const C={paper:'#f4efe4',ink:'#191915',graph:'#4b4942',faint:'#aaa499',line:'#cec7ba',red:'#a8422d',red2:'#c56348',blue:'#526c77',ghost:'#817c72'};
const STORE='poly-atlas-dayline-branch-i-public-v1',RETURN_STORE='poly-atlas-dayline-branch-i-public-last-return',VIEW_STORE='poly-atlas-dayline-branch-i-public-view',RESUME_STORE='poly-atlas-dayline-branch-i-public-resume';
const sample={
 meta:{title:'ATLAS DAYLINE',subtitle:'REALITY FIRST · EMPTY UNTIL CAPTURED',dayStart:'11:00',dayEnd:'23:00'},
 state:{now:null,contexts:['home','computer','phone'],horizon:180,sort:'focus',ink:'structure',lens:'atlas',selected:null,route:[]},
 anchors:[],
 tasks:[],
 events:[], evidence:{orient:[],miss:[],noise:[],friction:[],return:[]}
}
let data=load(),editId=null,anchorEditId=null,evidenceKind=null,taskDraft=null,taskIsNew=false,anchorDraft=null,anchorIsNew=false,taskPoints=new Map(),spinePoints=new Map(),contextHubPoints=new Map(),drag={kind:null,id:null,pointer:null,checkpointed:false};
function loadView(){try{return JSON.parse(localStorage.getItem(VIEW_STORE)||'{}')}catch{return{}}}
function loadResumeSeed(){try{return JSON.parse(localStorage.getItem(RESUME_STORE)||'null')}catch{return null}}
const savedView=loadView(),MOBILE_ACTION_KEY='poly-atlas-dayline-mobile-action-default-v1',bootMobile=window.matchMedia('(max-width:820px)').matches,firstMobileAction=bootMobile&&!localStorage.getItem(MOBILE_ACTION_KEY);
let ui={previewBundle:[],mobileView:savedView.mobileView||'now',semanticScale:savedView.semanticScale||'auto',district:savedView.district||null,folds:savedView.folds||{},projection:firstMobileAction?'plain':(savedView.projection||'atlas'),projectionStarted:Date.now(),projectionMs:{atlas:0,plain:0},projectionActs:{atlas:0,plain:0},scenario:null,sessionStarted:Date.now(),firstActAt:null,focusChanges:0,contextChanges:0,acts:0,resumeSeed:null,resumeStartedAt:null,lastReorientMs:null};
if(firstMobileAction)localStorage.setItem(MOBILE_ACTION_KEY,'1');
let sessionStart=null,sessionEventStart=0;
function clone(x){return JSON.parse(JSON.stringify(x))}
function localDateKey(d=new Date()){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function deviceClockMinute(){const d=new Date(),m=d.getHours()*60+d.getMinutes();return clamp(Math.round(m/5)*5,dayStart(),dayEnd())}
function syncDeviceNow(){const next=mh(deviceClockMinute()),prev=data.state.now;if(prev===next){toast('NOW already '+next);return}checkpoint('SYNC_NOW');data.state.now=next;event('TIME_SYNC','',prev+' → '+next);render();toast('NOW '+prev+' → '+next)}
function load(){try{const x=JSON.parse(localStorage.getItem(STORE));if(x&&x.tasks&&x.state){normalize(x);return x}}catch{}const x=clone(sample);normalize(x);return x}
function normalize(x){x.events=x.events||[];x.undo=x.undo||[];const oldEv=x.evidence||{};x.evidence={orient:oldEv.orient||oldEv.surfaced||[],miss:oldEv.miss||oldEv.wrong||[],noise:oldEv.noise||oldEv.deadInk||[],friction:oldEv.friction||[],return:oldEv.return||[]};x.state.route=(x.state.route||[]).slice(0,3);x.state.ink=x.state.ink||'structure';x.state.lens=x.state.lens||'atlas';for(const t of x.tasks||[]){t.sourceClass=t.sourceClass||'USER';t.provenance=t.provenance||''}if(!x.state.now){const d=new Date(),m=d.getHours()*60+d.getMinutes(),lo=hm(x.meta.dayStart),hi=hm(x.meta.dayEnd);x.state.now=mh(clamp(Math.round(m/5)*5,lo,hi))}}
function save(){localStorage.setItem(STORE,JSON.stringify(data))}
function validateState(x){const errors=[],ids=(x.tasks||[]).map(t=>t.id),set=new Set(ids),lo=hm(x.meta?.dayStart||'00:00'),hi=hm(x.meta?.dayEnd||'23:59');if(set.size!==ids.length)errors.push('duplicate task id');if(!(hi>lo))errors.push('dayEnd must be after dayStart');for(const t of x.tasks||[]){if(!t.id)errors.push('task missing id');if(!['USER','IMPORTED','WORKING_SPEC','DERIVED'].includes(t.sourceClass||'USER'))errors.push(`${t.id}: unknown sourceClass`);const a=hm(t.earliest||x.meta.dayStart),b=hm(t.latest||x.meta.dayEnd);if(!(b>a))errors.push(`${t.id}: latest must be after earliest`);if(a<lo||b>hi)errors.push(`${t.id}: window outside day bounds`);for(const d of t.depends||[]){if(!set.has(d))errors.push(`${t.id}: missing dependency ${d}`);if(d===t.id)errors.push(`${t.id}: self dependency`)}}const route=x.state?.route||[];if(route.length>3)errors.push('route exceeds temporary cap 3');if(new Set(route).size!==route.length)errors.push('route contains duplicates');for(const id of route)if(!set.has(id))errors.push(`route references missing task ${id}`);if(x.state?.selected&&!set.has(x.state.selected))errors.push('selected references missing task');if(!['atlas','focus'].includes(x.state?.lens||'atlas'))errors.push('unknown lens');for(const a of x.anchors||[]){const st=hm(a.start||x.meta.dayStart),en=hm(a.end||a.start||x.meta.dayStart);if(en<st)errors.push(`${a.id}: anchor end before start`);if(st<lo||en>hi)errors.push(`${a.id}: anchor outside day bounds`)}return errors}
function event(type,subject='',detail=''){const e={id:'e:'+Date.now().toString(36)+Math.random().toString(36).slice(2,5),at:new Date().toISOString(),type,subject,detail};data.events.push(e);if(data.events.length>160)data.events=data.events.slice(-160);if(ui?.resumeStartedAt&&['FOCUS','ACT'].includes(type)){ui.lastReorientMs=Date.now()-ui.resumeStartedAt;ui.resumeStartedAt=null;ui.resumeSeed=null;localStorage.removeItem(RESUME_STORE)}return e}
function coreSnapshot(){return clone({meta:data.meta,state:data.state,anchors:data.anchors,tasks:data.tasks,evidence:data.evidence})}
function hashCore(core){let h=2166136261,s=JSON.stringify({tasks:core.tasks,anchors:core.anchors,state:core.state});for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function checkpoint(label='CHANGE'){data.undo=data.undo||[];data.undo.push({at:new Date().toISOString(),label,core:coreSnapshot()});if(data.undo.length>15)data.undo=data.undo.slice(-15)}
function undo(){const u=(data.undo||[]).pop();if(!u){toast('Nothing to undo');return}const keepUndo=data.undo,keepEvents=data.events||[];data.meta=u.core.meta;data.state=u.core.state;data.anchors=u.core.anchors;data.tasks=u.core.tasks;data.evidence=u.core.evidence;data.undo=keepUndo;data.events=keepEvents;event('UNDO','',u.label);render();toast('Undid '+u.label)}
function nextHardAnchor(now=hm(data.state.now)){const activeA=(data.anchors||[]).filter(a=>hm(a.start)<=now&&now<hm(a.end)).sort((a,b)=>hm(a.end)-hm(b.end))[0];if(activeA)return{kind:'inside',anchor:activeA,minutes:0,until:hm(activeA.end)};const next=(data.anchors||[]).filter(a=>hm(a.start)>now).sort((a,b)=>hm(a.start)-hm(b.start))[0];const until=next?hm(next.start):dayEnd();return{kind:next?'before':'open',anchor:next||null,minutes:Math.max(0,until-now),until}}
function phaseFor(t){if(!t)return'receive';if(t.status==='done')return'return';if((data.state.route||[]).includes(t.id))return'carry';if(data.state.selected===t.id)return'cut';return'receive'}
function relevantIds(){const ids=new Set([...(data.state.route||[]),...ui.previewBundle]),f=focus();if(f){ids.add(f.id);bundleCandidates(f).forEach(b=>ids.add(b.x.id));(f.depends||[]).forEach(id=>ids.add(id))}return ids}
function returnReceipt(){const ops=data.tasks.map(opportunity),after=coreSnapshot(),before=clone(sessionStart||after),delta=(data.events||[]).slice(sessionEventStart),evidence=clone(data.evidence),evidenceCount=Object.values(evidence).reduce((n,x)=>n+(Array.isArray(x)?x.length:0),0),changed=hashCore(before)!==hashCore(after)||delta.length>0||evidenceCount>0,observedNow=mh(deviceClockMinute()),receipt={kind:'poly-atlas-return-f',version:2,returnClass:changed?'WORLD_DELTA':'ORIENTATION_SNAPSHOT',worldKey:'dayline:'+localDateKey(),domainPack:'planning.dayline',generatedAt:new Date().toISOString(),clockWitness:{canonicalNow:data.state.now,deviceLocalNow:observedNow,deltaMinutes:hm(data.state.now)-hm(observedNow),law:'canonical NOW may be manually simulated; device clock is witness only until explicit NOW ↻ sync'},before,after,afterChecksum:hashCore(after),sourceRefs:[...new Set(data.tasks.map(t=>t.provenance).filter(Boolean))],eventIds:delta.map(e=>e.id),delta,evidence,residue:ops.filter(t=>t.status!=='done'&&!data.state.route.includes(t.id)).map(t=>({id:t.id,bucket:t.bucket})),nextRoutes:(data.state.route||[]).map(id=>({id,title:taskById(id)?.title||id})),missed:ops.filter(t=>t.bucket==='MISSED').map(t=>t.id),projectionExperiment:{acts:clone(ui.projectionActs),ms:{atlas:ui.projectionMs.atlas+(ui.projection==='atlas'?Date.now()-ui.projectionStarted:0),plain:ui.projectionMs.plain+(ui.projection==='plain'?Date.now()-ui.projectionStarted:0)},lastProjection:ui.projection}};localStorage.setItem(RETURN_STORE,JSON.stringify(receipt));const blob=new Blob([JSON.stringify(receipt,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='poly-atlas-return-f.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);event('RETURN','',receipt.afterChecksum);render();toast((receipt.returnClass==='ORIENTATION_SNAPSHOT'?'Snapshot ':'Return ')+receipt.afterChecksum)}
function replayLastReturn(){try{const receipt=JSON.parse(localStorage.getItem(RETURN_STORE)||'null');if(!receipt?.after)throw Error('No saved Return');const issues=validateState(receipt.after);if(issues.length)throw Error(issues[0]);const got=hashCore(receipt.after);if(receipt.afterChecksum&&got!==receipt.afterChecksum)throw Error('Return checksum mismatch');checkpoint('RETURN_REPLAY');const keepUndo=data.undo,keepEvents=data.events;data.meta=clone(receipt.after.meta);data.state=clone(receipt.after.state);data.anchors=clone(receipt.after.anchors);data.tasks=clone(receipt.after.tasks);data.evidence=clone(receipt.after.evidence);data.undo=keepUndo;data.events=keepEvents;ui.previewBundle=[];event('RETURN_REPLAY','',got);render();toast('Replayed '+got)}catch(e){toast(e.message)}}
function el(tag,a={},text){const e=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;return e}
function add(g,tag,a={},text){const e=el(tag,a,text);g.appendChild(e);return e} function line(g,x1,y1,x2,y2,a={}){return add(g,'line',{x1,y1,x2,y2,...a})} function txt(g,x,y,text,a={}){return add(g,'text',{x,y,...a},text)} function group(g,a={}){return add(g,'g',a)}
function hm(s){const [h,m]=String(s).split(':').map(Number);return h*60+m} function mh(m){m=Math.round(m);return `${String(Math.floor(m/60)%24).padStart(2,'0')}:${String((m%60+60)%60).padStart(2,'0')}`}
function dayStart(){return hm(data.meta.dayStart)} function dayEnd(){return hm(data.meta.dayEnd)} function daySpan(){return Math.max(60,dayEnd()-dayStart())}
function minuteAngle(m){return -Math.PI/2+((m-dayStart())/daySpan())*TAU} function angleMinute(a){let u=(a+Math.PI/2)/TAU;while(u<0)u+=1;while(u>=1)u-=1;return clamp(Math.round((dayStart()+u*daySpan())/5)*5,dayStart(),dayEnd())}
function point(cx,cy,r,a){return[cx+Math.cos(a)*r,cy+Math.sin(a)*r]}
function arcPath(cx,cy,r,a0,a1){let span=a1-a0;while(span<0)span+=TAU;const p0=point(cx,cy,r,a0),p1=point(cx,cy,r,a1),large=span>Math.PI?1:0;return`M ${p0[0]} ${p0[1]} A ${r} ${r} 0 ${large} 1 ${p1[0]} ${p1[1]}`}
function sectorPath(cx,cy,r0,r1,a0,a1){let span=a1-a0;while(span<0)span+=TAU;const p0=point(cx,cy,r0,a0),p1=point(cx,cy,r1,a0),p2=point(cx,cy,r1,a1),p3=point(cx,cy,r0,a1),large=span>Math.PI?1:0;return`M ${p0[0]} ${p0[1]} L ${p1[0]} ${p1[1]} A ${r1} ${r1} 0 ${large} 1 ${p2[0]} ${p2[1]} L ${p3[0]} ${p3[1]} A ${r0} ${r0} 0 ${large} 0 ${p0[0]} ${p0[1]} Z`}
function active(){return new Set(data.state.contexts||[])} function taskById(id){return data.tasks.find(t=>t.id===id)} function openDeps(t){return(t.depends||[]).filter(id=>taskById(id)?.status!=='done')}
function overlapMinutes(a,b){return Math.max(0,Math.min(hm(a.latest),hm(b.latest))-Math.max(hm(a.earliest),hm(b.earliest)))}
function sharedContexts(a,b){const B=new Set(b.contexts||[]);return(a.contexts||[]).filter(x=>B.has(x))}
function contextFreq(tasks=data.tasks.filter(t=>t.status!=='done')){const m=new Map();for(const t of tasks)for(const c of t.contexts||[])m.set(c,(m.get(c)||0)+1);return m}
function primaryContext(t,freq=contextFreq()){const cs=t.contexts||[];if(!cs.length)return'uncategorized';const generic=new Set(['home','phone','computer']);const specific=cs.filter(c=>!generic.has(c));const pool=specific.length?specific:cs;return [...pool].sort((a,b)=>(freq.get(a)||999)-(freq.get(b)||999)||a.localeCompare(b))[0]}
function districtGroups(derived=data.tasks.map(opportunity)){const freq=contextFreq(derived.filter(t=>t.status!=='done')),m=new Map();for(const t of derived){if(t.status==='done')continue;const k=primaryContext(t,freq);if(!m.has(k))m.set(k,[]);m.get(k).push(t)}return m}
function semanticMode(){const open=data.tasks.filter(t=>t.status!=='done').length;return ui.semanticScale==='auto'?(open>18?'districts':'parcels'):ui.semanticScale}
function hull(points){const P=[...points].sort((a,b)=>a.x-b.x||a.y-b.y);if(P.length<=1)return P;const cross=(o,a,b)=>(a.x-o.x)*(b.y-o.y)-(a.y-o.y)*(b.x-o.x),lo=[],hi=[];for(const p of P){while(lo.length>=2&&cross(lo[lo.length-2],lo[lo.length-1],p)<=0)lo.pop();lo.push(p)}for(let i=P.length-1;i>=0;i--){const p=P[i];while(hi.length>=2&&cross(hi[hi.length-2],hi[hi.length-1],p)<=0)hi.pop();hi.push(p)}lo.pop();hi.pop();return lo.concat(hi)}
function districtFor(id){const t=taskById(id);return t?primaryContext(t):null}
function selectDistrict(k){ui.district=k;ui.semanticScale='parcels';const group=[...districtGroups().get(k)||[]].sort((a,b)=>b.score-a.score);if(group[0]){data.state.selected=group[0].id;event('FOCUS',group[0].id,'district:'+k)}render()}
function clearDistrict(){ui.district=null;render()}
function captureInterruption(reason='hidden'){const seed={at:new Date().toISOString(),reason,checksum:checksum(),selected:data.state.selected,route:[...(data.state.route||[])],contexts:[...(data.state.contexts||[])],now:data.state.now,mobileView:ui.mobileView,nextAnchor:nextHardAnchor().anchor?.id||null};localStorage.setItem(RESUME_STORE,JSON.stringify(seed));return seed}
function maybeOfferResume(){const seed=loadResumeSeed();if(!seed||seed.checksum!==checksum())return;const away=Date.now()-Date.parse(seed.at);if(away<60000)return;ui.resumeSeed={...seed,away};ui.resumeStartedAt=Date.now();render()}
function resumeFocus(syncNow=false){const s=ui.resumeSeed;if(!s)return;if(syncNow){const d=new Date(),m=clamp(Math.round((d.getHours()*60+d.getMinutes())/5)*5,dayStart(),dayEnd());checkpoint('RESUME_TIME');data.state.now=mh(m);event('TIME','',data.state.now)}if(s.selected&&taskById(s.selected))data.state.selected=s.selected;if(s.mobileView)ui.mobileView=s.mobileView;if(ui.resumeStartedAt)ui.lastReorientMs=Date.now()-ui.resumeStartedAt;ui.resumeStartedAt=null;event('RESUME',s.selected||'',syncNow?'sync-now':'focus-only');ui.resumeSeed=null;localStorage.removeItem(RESUME_STORE);render()}
function dismissResume(){ui.resumeSeed=null;ui.resumeStartedAt=null;localStorage.removeItem(RESUME_STORE);render()}
function opportunityAt(t,sim=null){
 const now=hm(sim?.now||data.state.now),act=new Set(sim?.contexts||data.state.contexts||[]),horizon=sim?.horizon??data.state.horizon,ctx=t.contexts||[],hits=ctx.filter(c=>act.has(c)),match=ctx.length?hits.length/ctx.length:1,start=hm(t.earliest),end=hm(t.latest),missed=t.status!=='done'&&now>end,inWindow=!missed&&now>=start&&now<=end,untilStart=Math.max(0,start-now),untilEnd=end-now,blocked=openDeps(t),lookFit=(+t.duration||15)<=horizon,gap=nextHardAnchor(now),gapFit=gap.minutes>0&&(+t.duration||15)<=gap.minutes;
 const setupRaw=(+t.setup||0)*9,hitsCredit=hits.length*7,setup=Math.max(0,setupRaw-hitsCredit),timePenalty=missed?72:(inWindow?0:Math.min(50,untilStart/9)),depPenalty=blocked.length*30,horizonPenalty=lookFit?0:18,gapPenalty=(inWindow&&!gapFit&&gap.kind!=='open')?16:0,cost=t.status==='done'?96:clamp(setup+timePenalty+depPenalty+horizonPenalty+gapPenalty,0,100),urgency=inWindow?Math.max(0,30-Math.max(0,untilEnd)/14):0,valuePart=(+t.value||3)*18,contextPart=match*36,fitPart=lookFit?10:0,gapPart=gapFit&&inWindow?8:0,sourcePart=({USER:12,IMPORTED:0,WORKING_SPEC:-10,DERIVED:-14}[t.sourceClass||'USER']??0);
 let score=Math.round(valuePart+contextPart+urgency-cost*.64+fitPart+gapPart+sourcePart);const bucket=t.status==='done'?'DONE':missed?'MISSED':blocked.length?'BLOCKED':inWindow&&cost<=18?'NOW':inWindow||untilStart<=horizon?'SOON':'LATER';
 return{...t,cost,score,bucket,hits,match,inWindow,missed,blocked,fit:lookFit,gapFit,freeGap:gap.minutes,nextAnchor:gap.anchor,why:{value:valuePart,context:contextPart,urgency,setup:-setup*.64,time:-timePenalty*.64,dependencies:-depPenalty*.64,horizon:-horizonPenalty*.64,gap:(gapPart-gapPenalty*.64),fit:fitPart,source:sourcePart}};
}
function opportunity(t){return opportunityAt(t,null)}
function scenarioDiffs(){if(!ui.scenario)return[];return data.tasks.filter(t=>t.status!=='done').map(t=>{const current=opportunity(t),future=opportunityAt(t,ui.scenario);return{id:t.id,title:t.title,current,future,gain:Math.round(current.cost-future.cost),scoreDelta:future.score-current.score}}).sort((a,b)=>Math.abs(b.gain)-Math.abs(a.gain)||b.scoreDelta-a.scoreDelta)}

function ordered(){const arr=data.tasks.map((t,i)=>({...opportunity(t),_i:i})).filter(t=>t.status!=='done'),ranks=new Map(data.state.route.map((id,i)=>[id,i]));const routeCmp=(a,b)=>{const ra=ranks.has(a.id)?ranks.get(a.id):9999,rb=ranks.has(b.id)?ranks.get(b.id):9999;return ra-rb};if(data.state.sort==='manual')return arr.sort((a,b)=>routeCmp(a,b)||a._i-b._i);if(data.state.sort==='time')return arr.sort((a,b)=>routeCmp(a,b)||hm(a.earliest)-hm(b.earliest)||b.value-a.value);return arr.sort((a,b)=>routeCmp(a,b)||b.score-a.score||a.cost-b.cost||a._i-b._i)}
function focus(){let t=taskById(data.state.selected);if(!t){t=ordered()[0];data.state.selected=t?.id||null}return t?opportunity(t):null}
function bundleCandidates(t){return data.tasks.filter(x=>x.id!==t.id&&x.status!=='done'&&!data.state.route.includes(x.id)).map(x=>{const ox=opportunity(x),shared=sharedContexts(t,x),ov=overlapMinutes(t,x),score=shared.length*18+Math.min(30,ov/6)+(ox.gapFit?7:0)-(+x.setup||0)*2-(ox.bucket==='MISSED'?80:0);return{x:ox,shared,ov,score}}).filter(z=>z.x.bucket!=='MISSED'&&(z.shared.length||z.ov>20)).sort((a,b)=>b.score-a.score).slice(0,3)}
function previewBundle(ids=null){const f=focus(),cap=Math.max(0,3-data.state.route.length);let next=ids||(f?bundleCandidates(f).map(b=>b.x.id):[]);ui.previewBundle=[...new Set(next)].filter(id=>taskById(id)&&!data.state.route.includes(id)).slice(0,cap);render()}
function previewCandidate(id){const cap=Math.max(0,3-data.state.route.length);if(cap<=0){toast('RUN full: 3/3');return}const next=[...ui.previewBundle.filter(x=>x!==id),id];ui.previewBundle=next.slice(-cap);render()}
function clearPreview(){ui.previewBundle=[];render()}
function actPreview(){if(!ui.previewBundle.length){toast('Nothing previewed');return}checkpoint('ACT_PREVIEW');for(const id of ui.previewBundle){if(data.state.route.length>=3)break;if(!data.state.route.includes(id))data.state.route.push(id)}ui.acts++;recordProjectionAct();if(!ui.firstActAt)ui.firstActAt=Date.now();event('ACT','',ui.previewBundle.join(',')+'|'+ui.projection);ui.previewBundle=[];render()}
function textWrap(str,max=28){const words=String(str).split(/\s+/),out=[];let ln='';for(const w of words){const n=ln?ln+' '+w:w;if(n.length>max&&ln){out.push(ln);ln=w}else ln=n}if(ln)out.push(ln);return out}
function clear(id){$(id).replaceChildren()} function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('on');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('on'),1200)}
function saveView(){localStorage.setItem(VIEW_STORE,JSON.stringify({mobileView:ui.mobileView,semanticScale:ui.semanticScale,district:ui.district,folds:ui.folds||{},projection:ui.projection}))}
function projectionTick(){const now=Date.now(),elapsed=Math.max(0,now-ui.projectionStarted);ui.projectionMs[ui.projection]=(ui.projectionMs[ui.projection]||0)+elapsed;ui.projectionStarted=now}
function setProjection(mode){if(!['atlas','plain'].includes(mode))return;projectionTick();ui.projection=mode;document.body.dataset.projection=mode;$('#atlasProjectionBtn').classList.toggle('on',mode==='atlas');$('#plainProjectionBtn').classList.toggle('on',mode==='plain');renderPlain();saveView()}
function recordProjectionAct(){ui.projectionActs[ui.projection]=(ui.projectionActs[ui.projection]||0)+1}
function openScenario(){const base=ui.scenario||{now:data.state.now,contexts:[...(data.state.contexts||[])],horizon:data.state.horizon};$('#scenarioTime').value=base.now;$('#scenarioContexts').value=(base.contexts||[]).join(', ');$('#scenarioHorizon').value=String(base.horizon??data.state.horizon);$('#scenarioDialog').showModal()}
function readScenarioForm(){const now=$('#scenarioTime').value||data.state.now,contexts=$('#scenarioContexts').value.split(',').map(x=>x.trim()).filter(Boolean),horizon=+$('#scenarioHorizon').value||data.state.horizon;return{now,contexts,horizon}}
function previewScenario(){ui.scenario=readScenarioForm();$('#scenarioDialog').close();render();toast('Scenario preview only · canon unchanged')}
function clearScenario(){ui.scenario=null;$('#scenarioDialog').close();render();toast('Scenario cleared')}
function applyScenario(){const sim=readScenarioForm();checkpoint('SCENARIO_APPLY');data.state.now=sim.now;data.state.contexts=[...sim.contexts];data.state.horizon=sim.horizon;ui.contextChanges++;event('SCENARIO_APPLY','',`${sim.now}|${sim.contexts.join('+')}`);ui.scenario=null;$('#scenarioDialog').close();render();toast('Scenario applied to canonical state')}
function renderPlain(){const root=$('#plainView');if(!root)return;const list=ordered(),f=focus(),gap=nextHardAnchor();$('#plainState').innerHTML=`<b>NOW ${data.state.now}</b><br>${(data.state.contexts||[]).map(c=>'@'+c).join(' ')}<br>FREE GAP ${gap.minutes}m · RUN ${data.state.route.length}/3`;$('#plainAnchors').innerHTML=(data.anchors||[]).map(a=>`<span class="plain-anchor"><b>${a.start}–${a.end}</b> ${escapeHtml(a.title)}</span>`).join('');$('#plainList').innerHTML=list.map(t=>`<div class="plain-row ${f?.id===t.id?'selected':''} ${data.state.route.includes(t.id)?'routed':''}" data-plain-id="${t.id}"><input type="checkbox" data-plain-done="${t.id}" ${t.status==='done'?'checked':''}><div><div class="plain-title">${escapeHtml(t.title)}</div><div class="plain-meta">${t.bucket} · ${t.earliest}–${t.latest} · ${t.duration}m · COST ${Math.round(t.cost)} · ${(t.contexts||[]).map(c=>'@'+c).join(' ')}</div></div><div class="plain-actions"><button class="act" data-plain-act="${t.id}">${data.state.route.includes(t.id)?'REMOVE RUN':'ACT → RUN'}</button><button class="edit" data-plain-edit="${t.id}">EDIT</button></div></div>`).join('')||'<div class="plain-row"><div></div><div class="plain-title">No open tasks.</div><div></div></div>';const diffs=scenarioDiffs();$('#plainFoot').innerHTML=`<span>PLAIN = ABLATION · same canonical IDs/state/ranking</span><span>ACT A/P ${ui.projectionActs.atlas}/${ui.projectionActs.plain}${ui.scenario?` · SCENARIO ${ui.scenario.now} · Δ ${diffs.filter(d=>Math.abs(d.gain)>=8).length}`:''}</span>`;root.querySelectorAll('[data-plain-id]').forEach(r=>r.addEventListener('click',e=>{if(e.target.closest('button,input'))return;data.state.selected=r.dataset.plainId;ui.focusChanges++;render()}));root.querySelectorAll('[data-plain-done]').forEach(x=>x.addEventListener('change',()=>toggleDone(x.dataset.plainDone)));root.querySelectorAll('[data-plain-act]').forEach(x=>x.addEventListener('click',e=>{e.stopPropagation();routeToggle(x.dataset.plainAct)}));root.querySelectorAll('[data-plain-edit]').forEach(x=>x.addEventListener('click',e=>{e.stopPropagation();openTask(x.dataset.plainEdit)}))}
function escapeHtml(x){return String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c))}
function render(){taskPoints=new Map();spinePoints=new Map();contextHubPoints=new Map();renderStatic();renderRelationsAndField();renderRoute();renderSpine();renderMargins();renderLedger();renderForecast();renderStrategy();renderOverlay();renderPlain();applyMobileViewport();document.body.dataset.projection=ui.projection;$('#atlasProjectionBtn').classList.toggle('on',ui.projection==='atlas');$('#plainProjectionBtn').classList.toggle('on',ui.projection==='plain');$('#scenarioBtn').classList.toggle('scenario-on',!!ui.scenario);$('#scenarioBadge').textContent=ui.scenario?`PREVIEW ${ui.scenario.now} · ${(ui.scenario.contexts||[]).join('+')}`:'NO COUNTERFACTUAL';save();saveView()}


function applyMobileViewport(){const svg=$('#atlas');if(!svg)return;const mobile=window.matchMedia('(max-width:820px)').matches;if(!mobile){svg.setAttribute('viewBox','0 0 1200 2480');return}const boxes={now:'250 90 700 850',field:'205 105 790 820',run:'250 865 700 710',return:'25 1450 1150 370',tide:'25 1875 1150 550',atlas:'0 0 1200 2480'};svg.setAttribute('viewBox',boxes[ui.mobileView]||boxes.now);document.querySelectorAll('[data-mobile-view]').forEach(b=>b.classList.toggle('on',b.dataset.mobileView===ui.mobileView))}
function renderStatic(){clear('#staticLayer');const g=$('#staticLayer'),cx=600,cy=500;
 line(g,18,24,1182,24,{stroke:C.ink,'stroke-width':.55,'stroke-opacity':.55});line(g,18,2456,1182,2456,{stroke:C.ink,'stroke-width':.55,'stroke-opacity':.55});line(g,18,24,18,2456,{stroke:C.ink,'stroke-width':.55,'stroke-opacity':.55});line(g,1182,24,1182,2456,{stroke:C.ink,'stroke-width':.55,'stroke-opacity':.55});[[18,24],[1182,24],[18,2456],[1182,2456]].forEach(([x,y])=>{line(g,x-8,y,x+8,y,{stroke:C.ink,'stroke-width':.6});line(g,x,y-8,x,y+8,{stroke:C.ink,'stroke-width':.6})});
 txt(g,58,72,data.meta.title,{class:'title',fill:C.ink});txt(g,58,96,data.meta.subtitle,{class:'subtitle',fill:C.graph});txt(g,58,120,'BRANCH I / SEE → SIMULATE → COMPARE → ACT → RETURN',{class:'micro',fill:C.ghost});
 txt(g,1110,63,'域',{class:'serif',fill:C.red,'font-size':17,'text-anchor':'middle'});add(g,'rect',{x:1097,y:44,width:26,height:26,fill:'none',stroke:C.red,'stroke-width':1});
 [76,116,158,202,246,292,334].forEach((r,i)=>add(g,'circle',{cx,cy,r,fill:'none',stroke:i===6?C.ink:C.line,'stroke-width':i===6?1.1:.65,'stroke-opacity':i===6?.75:.8,'stroke-dasharray':i===6?'0':(i%2?'2 5':'0')}));
 for(let i=0;i<24;i++){const a=-Math.PI/2+i/24*TAU,major=i%2===0,p1=point(cx,cy,major?308:323,a),p2=point(cx,cy,344,a);line(g,p1[0],p1[1],p2[0],p2[1],{stroke:C.ink,'stroke-width':major?.65:.38,'stroke-opacity':major?.5:.27})}
 const st=dayStart(),span=daySpan();for(let i=0;i<=12;i++){const m=st+i*span/12,a=minuteAngle(m),p=point(cx,cy,365,a);txt(g,p[0],p[1]+3,mh(m),{class:'tiny',fill:C.graph,'text-anchor':'middle'})}
 line(g,cx-370,cy,cx+370,cy,{stroke:C.ink,'stroke-width':.35,'stroke-opacity':.18});line(g,cx,cy-370,cx,cy+370,{stroke:C.ink,'stroke-width':.35,'stroke-opacity':.18});txt(g,600,865,'OPPORTUNITY FIELD / 任务域',{class:'smallcaps label',fill:C.graph,'text-anchor':'middle'});txt(g,600,882,'ANGLE = TIME  ·  RADIUS = ACTIVATION COST  ·  BLUE = FREE GAP / COUNTERFACTUAL',{class:'micro',fill:C.ghost,'text-anchor':'middle'});
}

function renderDistricts(rel,g,derived){const groups=districtGroups(derived),mode=semanticMode();if(mode!=='districts'&&!ui.district)return;for(const [key,tasks] of groups){const pts=[];for(const t of tasks){const p=taskPoints.get(t.id);if(!p)continue;const pad=9+Math.min(10,tasks.length);pts.push({x:p.x-pad,y:p.y},{x:p.x+pad,y:p.y},{x:p.x,y:p.y-pad},{x:p.x,y:p.y+pad})}if(!pts.length)continue;const H=hull(pts),cx=H.reduce((a,p)=>a+p.x,0)/H.length,cy=H.reduce((a,p)=>a+p.y,0)/H.length,selected=ui.district===key,activeDistrict=active().has(key),nowCount=tasks.filter(t=>t.bucket==='NOW').length;if(H.length>=3){const d='M '+H.map(p=>`${p.x} ${p.y}`).join(' L ')+' Z',hit=add(g,'path',{d,fill:selected?'rgba(168,66,45,.055)':activeDistrict?'rgba(25,25,21,.035)':'rgba(82,108,119,.025)',stroke:selected?C.red:C.graph,'stroke-width':selected?1.35:.65,'stroke-opacity':selected?.82:.28,'stroke-dasharray':selected?'0':'3 4',class:'ctrl'});hit.addEventListener('click',e=>{e.stopPropagation();selectDistrict(key)})}else add(g,'circle',{cx,cy,r:22,fill:'rgba(25,25,21,.03)',stroke:selected?C.red:C.graph,'stroke-width':.7,'stroke-opacity':.32});if(mode==='districts'||selected){const gg=group(g,{class:'ctrl'});txt(gg,cx,cy-3,key.toUpperCase(),{class:'micro',fill:selected?C.red:C.ink,'text-anchor':'middle'});txt(gg,cx,cy+10,`${tasks.length} TASK${tasks.length===1?'':'S'} · NOW ${nowCount}`,{class:'tiny',fill:nowCount?C.red:C.ghost,'text-anchor':'middle'});add(gg,'rect',{x:cx-45,y:cy-17,width:90,height:34,fill:'transparent'});gg.addEventListener('click',e=>{e.stopPropagation();selectDistrict(key)})}}}
function renderRelationsAndField(){clear('#relationLayer');clear('#fieldLayer');const rel=$('#relationLayer'),g=$('#fieldLayer'),cx=600,cy=500,derived=data.tasks.map(opportunity),ink=data.state.ink,lens=data.state.lens||'atlas',relevant=relevantIds(),sem=semanticMode();
 derived.forEach(t=>{const mid=(hm(t.earliest)+hm(t.latest))/2,a=minuteAngle(mid),r=88+(t.cost/100)*218,[x,y]=point(cx,cy,r,a);taskPoints.set(t.id,{x,y,a,r,t})});renderDistricts(rel,g,derived);
 // Counterfactual scenario layer: blue vectors are derived comparisons, never canonical edits.
 if(ui.scenario){const diffs=scenarioDiffs(),strong=new Set(diffs.filter(d=>Math.abs(d.gain)>=8||d.id===data.state.selected||data.state.route.includes(d.id)).map(d=>d.id));for(const d of diffs){if(!strong.has(d.id))continue;const p=taskPoints.get(d.id),mid=(hm(d.current.earliest)+hm(d.current.latest))/2,a=minuteAngle(mid),sr=88+(d.future.cost/100)*218,[sx,sy]=point(cx,cy,sr,a),inward=d.gain>0;add(rel,'line',{x1:p.x,y1:p.y,x2:sx,y2:sy,stroke:C.blue,'stroke-width':inward?1.15:.75,'stroke-opacity':inward?.6:.32,'stroke-dasharray':'3 3'});add(rel,'circle',{cx:sx,cy:sy,r:d.id===data.state.selected?5:3.3,fill:C.paper,stroke:C.blue,'stroke-width':d.id===data.state.selected?1.4:.8,'stroke-opacity':.82});if(d.id===data.state.selected){const lp=point(cx,cy,sr+15,a);txt(rel,lp[0],lp[1],`${d.gain>=0?'+':''}${d.gain} COST`,{class:'tiny',fill:C.blue,'text-anchor':'middle'})}}const sa=minuteAngle(hm(ui.scenario.now)),sp=point(cx,cy,345,sa);line(g,cx,cy,sp[0],sp[1],{stroke:C.blue,'stroke-width':1,'stroke-opacity':.42,'stroke-dasharray':'4 4'});txt(g,sp[0],sp[1]-7,'SCENARIO',{class:'tiny',fill:C.blue,'text-anchor':'middle'})}

 // Free runway: distinct from look-ahead horizon. It ends at the next hard anchor.
 const gap=nextHardAnchor(),na=minuteAngle(hm(data.state.now));if(gap.minutes>0){const ea=minuteAngle(gap.until);add(g,'path',{d:sectorPath(cx,cy,306,325,na,ea),fill:'rgba(82,108,119,.08)',stroke:C.blue,'stroke-width':.7,'stroke-opacity':.42});const mp=point(cx,cy,338,na+(ea-na)/2);txt(g,mp[0],mp[1],`FREE ${gap.minutes}m`,{class:'tiny',fill:C.blue,'text-anchor':'middle'})}
 // Context hubs: relations route through named hubs rather than forming O(n²) spaghetti.
 const ctxSet=[...new Set(derived.flatMap(t=>t.contexts||[]))].sort();ctxSet.forEach((c,i)=>{const a=-Math.PI/2+(i/Math.max(1,ctxSet.length))*TAU,p=point(cx,cy,278,a);contextHubPoints.set(c,{x:p[0],y:p[1],a});if(ink!=='quiet'){add(rel,'circle',{cx:p[0],cy:p[1],r:3.4,fill:active().has(c)?C.ink:C.paper,stroke:C.ink,'stroke-width':.55,'stroke-opacity':.55});if(ink==='full'||active().has(c)){const q=point(cx,cy,292,a);txt(rel,q[0],q[1]+2,c.toUpperCase(),{class:'tiny',fill:active().has(c)?C.ink:C.ghost,'text-anchor':'middle','transform':`rotate(${a*180/Math.PI+90} ${q[0]} ${q[1]})`})}}});
 if(ink!=='quiet')derived.forEach(t=>{const p=taskPoints.get(t.id),visible=lens==='atlas'||relevant.has(t.id);if(!visible)return;(t.contexts||[]).forEach(c=>{const h=contextHubPoints.get(c);if(!h)return;const strong=active().has(c)||data.state.selected===t.id;add(rel,'path',{d:`M ${p.x} ${p.y} Q ${(p.x+h.x)/2*.72+cx*.28} ${(p.y+h.y)/2*.72+cy*.28} ${h.x} ${h.y}`,fill:'none',stroke:strong?C.graph:C.ghost,'stroke-width':strong?.75:.38,'stroke-opacity':strong?.16:.055,'stroke-dasharray':strong?'0':'2 5'})})});
 derived.forEach(t=>(t.depends||[]).forEach(id=>{const a=taskPoints.get(t.id),b=taskPoints.get(id);if(a&&b&&(lens==='atlas'||relevant.has(t.id)||relevant.has(id)))add(rel,'path',{d:`M ${a.x} ${a.y} L ${b.x} ${b.y}`,fill:'none',stroke:C.ink,'stroke-width':1,'stroke-opacity':.44,'stroke-dasharray':'5 4'})}));
 data.anchors.forEach((a,idx)=>{const a0=minuteAngle(hm(a.start)),a1=minuteAngle(hm(a.end)),r=331,arc=arcPath(cx,cy,r,a0,a1);const hit=add(g,'path',{d:arc,fill:'none',stroke:'transparent','stroke-width':14,class:'anchorHit','data-id':a.id});add(g,'path',{d:arc,fill:'none',stroke:C.red,'stroke-width':4,'stroke-opacity':.72,class:'anchorArc'});hit.addEventListener('click',()=>openAnchor(a.id));[a0,a1].forEach(aa=>{const p0=point(cx,cy,300,aa),p1=point(cx,cy,347,aa);line(g,p0[0],p0[1],p1[0],p1[1],{stroke:C.red,'stroke-width':1.1,'stroke-opacity':.8,'stroke-dasharray':idx?'4 3':'0'})})});
 derived.forEach(t=>{const P=taskPoints.get(t.id),mid=P.a,r=P.r,win0=minuteAngle(hm(t.earliest)),win1=minuteAngle(hm(t.latest)),route=data.state.route.includes(t.id),selected=data.state.selected===t.id,districtKey=primaryContext(t),districtVisible=!ui.district||ui.district===districtKey,visible=(lens==='atlas'||relevant.has(t.id))&&districtVisible,ghostOpacity=(sem==='districts'&&!selected&&!route)?.09:(visible?1:.09);const gg=group(g,{class:'taskParcel',tabindex:'0','data-id':t.id,opacity:ghostOpacity});add(gg,'path',{d:arcPath(cx,cy,r,win0,win1),fill:'none',stroke:t.status==='done'?C.ghost:C.graph,'stroke-width':.72,'stroke-opacity':t.status==='done'?.15:.24,'stroke-dasharray':'2 3'});
  const aw=clamp((t.duration/daySpan())*TAU,.035,.22),th=6+(+t.value||3)*2.3,pth=sectorPath(cx,cy,r-th/2,r+th/2,mid-aw/2,mid+aw/2);let fill=t.status==='done'?'url(#hatch)':(t.bucket==='BLOCKED'||t.bucket==='MISSED')?'url(#hatch)':'rgba(25,25,21,.13)',stroke=t.bucket==='MISSED'?C.red:(t.status==='done'?C.ghost:C.ink),so=t.status==='done'?.22:.66;if(selected){fill='rgba(168,66,45,.17)';stroke=C.red;so=.95}if(route){fill='url(#hatchRed)';stroke=C.red;so=1}add(gg,'path',{d:pth,class:'parcel-main',fill,stroke,'stroke-width':selected?1.8:route?1.35:.8,'stroke-opacity':so});
  if(sem!=='districts'&&(ink==='full'||selected||route)){const cols=clamp(Math.ceil(t.duration/5),1,18),rows=clamp((t.contexts||[]).length,1,5);for(let rr=0;rr<rows;rr++){const rr0=r-th/2+(rr/rows)*th,rr1=r-th/2+((rr+1)/rows)*th;for(let cc=1;cc<cols;cc++){const aa=mid-aw/2+(cc/cols)*aw,p0=point(cx,cy,rr0,aa),p1=point(cx,cy,rr1,aa);line(gg,p0[0],p0[1],p1[0],p1[1],{stroke:C.ink,'stroke-width':.28,'stroke-opacity':.25})}if(rr>0){const rradius=r-th/2+(rr/rows)*th;add(gg,'path',{d:arcPath(cx,cy,rradius,mid-aw/2,mid+aw/2),fill:'none',stroke:C.ink,'stroke-width':.28,'stroke-opacity':.22})}}}
  (t.contexts||[]).forEach((c,k)=>{const aa=mid-aw/2+(k+1)/(t.contexts.length+1)*aw,p0=point(cx,cy,r-th/2-4,aa),p1=point(cx,cy,r+th/2+4,aa);line(gg,p0[0],p0[1],p1[0],p1[1],{stroke:C.ink,'stroke-width':.4,'stroke-opacity':.38})});
  if(sem!=='districts'&&(selected||route||t.cost>76)){const lp=point(cx,cy,r+17,mid);txt(gg,lp[0],lp[1],t.id.replace('t:','').slice(0,11).toUpperCase(),{class:'tiny',fill:selected?C.red:C.graph,'text-anchor':'middle','transform':`rotate(${mid*180/Math.PI+90} ${lp[0]} ${lp[1]})`})}if(selected)renderWindowHandles(g,t,r,win0,win1);gg.addEventListener('click',e=>{e.stopPropagation();data.state.selected=t.id;ui.previewBundle=[];ui.focusChanges++;event('FOCUS',t.id,'field');render()});gg.addEventListener('dblclick',e=>{e.stopPropagation();openTask(t.id)});gg.addEventListener('keydown',e=>{if(e.key==='Enter')openTask(t.id)})});
 const nowm=hm(data.state.now),nowa=minuteAngle(nowm),np=point(cx,cy,318,nowa),hp=point(cx,cy,342,nowa);line(g,cx,cy,np[0],np[1],{stroke:C.red,'stroke-width':1.5,'stroke-opacity':.8});add(g,'circle',{cx:hp[0],cy:hp[1],r:10,fill:C.paper,stroke:C.red,'stroke-width':1.3,class:'nowHandle','data-dragkind':'now'});add(g,'circle',{cx:hp[0],cy:hp[1],r:3.2,fill:C.red,class:'nowHandle','data-dragkind':'now'});
 const fg=nextHardAnchor();add(g,'circle',{cx,cy,r:63,fill:C.paper,stroke:C.ink,'stroke-width':1.2});add(g,'circle',{cx,cy,r:52,fill:'none',stroke:C.line,'stroke-width':.8,'stroke-dasharray':'2 3'});txt(g,cx,cy-22,'NOW / 此刻',{class:'smallcaps micro',fill:C.graph,'text-anchor':'middle'});txt(g,cx,cy+4,data.state.now,{class:'serif',fill:C.red,'font-size':24,'text-anchor':'middle'});txt(g,cx,cy+21,`GAP ${fg.minutes}m · LOOK ${data.state.horizon===9999?'DAY':data.state.horizon+'m'}`,{class:'tiny',fill:fg.minutes?C.blue:C.ghost,'text-anchor':'middle'});txt(g,cx,cy+34,`${data.state.lens.toUpperCase()} · ${sem.toUpperCase()} · ${data.state.contexts.length} CONDITIONS`,{class:'tiny',fill:C.ghost,'text-anchor':'middle'});const ch=add(g,'circle',{cx,cy,r:54,fill:'transparent',class:'hot'});ch.addEventListener('click',()=>{$('#timeInput').value=data.state.now;$('#timeDialog').showModal()});const ff=focus();if(ff){txt(g,cx,901,`FOCUS → ${ff.title.slice(0,62)}${ff.title.length>62?'…':''}`,{class:'micro',fill:C.ink,'text-anchor':'middle'});}
}
function renderWindowHandles(g,t,r,a0,a1){const cx=600,cy=500;[['start',a0],['end',a1]].forEach(([kind,a])=>{const p=point(cx,cy,r,a),q=point(cx,cy,r+(kind==='start'?-16:16),a);line(g,p[0],p[1],q[0],q[1],{stroke:C.red,'stroke-width':1.05,'stroke-opacity':.75});add(g,'circle',{cx:q[0],cy:q[1],r:7,fill:C.paper,stroke:C.red,'stroke-width':1.2,class:'winHandle','data-dragkind':kind,'data-id':t.id});txt(g,q[0],q[1]-10,kind==='start'?'E':'L',{class:'tiny',fill:C.red,'text-anchor':'middle'})})}

function renderRoute(){clear('#routeLayer');const g=$('#routeLayer'),ids=data.state.route.filter(id=>taskPoints.has(id));if(!ids.length&&data.state.selected)ids.push(data.state.selected);if(ids.length){let d='M 600 500';ids.forEach(id=>{const p=taskPoints.get(id);d+=` L ${p.x} ${p.y}`});add(g,'path',{d,fill:'none',stroke:C.red,'stroke-width':data.state.route.length?2.15:1.05,'stroke-opacity':data.state.route.length?.86:.38,'stroke-dasharray':data.state.route.length?'0':'5 4'});ids.forEach((id,i)=>{const p=taskPoints.get(id);add(g,'circle',{cx:p.x,cy:p.y,r:4+(i===0?1:0),fill:C.red});if(data.state.route.length)txt(g,p.x,p.y-9,String(i+1),{class:'tiny',fill:C.red,'text-anchor':'middle'})})}const pv=ui.previewBundle.filter(id=>taskPoints.has(id));if(pv.length){let d=`M ${focus()?taskPoints.get(focus().id)?.x||600:600} ${focus()?taskPoints.get(focus().id)?.y||500:500}`;pv.forEach(id=>{const p=taskPoints.get(id);d+=` L ${p.x} ${p.y}`});add(g,'path',{d,fill:'none',stroke:C.blue,'stroke-width':1.35,'stroke-opacity':.75,'stroke-dasharray':'4 4'});pv.forEach((id,i)=>{const p=taskPoints.get(id);add(g,'circle',{cx:p.x,cy:p.y,r:5,fill:C.paper,stroke:C.blue,'stroke-width':1.2});txt(g,p.x,p.y-9,'P'+(i+1),{class:'tiny',fill:C.blue,'text-anchor':'middle'})})}}

function renderSpine(){clear('#spineLayer');const g=$('#spineLayer'),list=ordered().slice(0,7),x=600,y0=950,rowH=78;txt(g,x,918,'RUN / OPERATIONAL SPINE',{class:'smallcaps label',fill:C.graph,'text-anchor':'middle'});txt(g,x,935,'PREVIEW DOES NOT MUTATE · ACT COMMITS · STATUS RETURNS',{class:'micro',fill:C.ghost,'text-anchor':'middle'});line(g,x,944,x,1534,{stroke:C.ink,'stroke-width':.55,'stroke-opacity':.34});
 list.forEach((t,i)=>{const y=y0+i*rowH,w=260+(+t.value||3)*32,xx=x-w/2,selected=data.state.selected===t.id,routeIndex=data.state.route.indexOf(t.id),routed=routeIndex>=0;spinePoints.set(t.id,{x,y:y+30});const gg=group(g,{class:'spineRow','data-id':t.id,tabindex:'0'});add(gg,'rect',{x:xx,y,width:w,height:60,fill:selected?'rgba(168,66,45,.055)':routed?'rgba(168,66,45,.035)':'rgba(25,25,21,.018)',stroke:selected||routed?C.red:C.ink,'stroke-width':selected?1.5:routed?1.15:.75,'stroke-opacity':selected||routed?.9:.42,class:'spinePlate'});
  const cols=clamp(Math.ceil(t.duration/5),1,12);for(let k=1;k<cols;k++){const rx=xx+(w/cols)*k;line(gg,rx,y+1,rx,y+59,{stroke:C.ink,'stroke-width':.28,'stroke-opacity':.13})}line(gg,xx-20,y+30,xx,y+30,{stroke:C.ink,'stroke-width':.75,'stroke-opacity':.45});add(gg,'circle',{cx:xx-29,cy:y+30,r:6.2,fill:C.paper,stroke:C.ink,'stroke-width':1});const hit=add(gg,'circle',{cx:xx-29,cy:y+30,r:13,fill:'transparent',class:'hot'});hit.addEventListener('click',e=>{e.stopPropagation();toggleDone(t.id)});
  txt(gg,xx+10,y+17,String(i+1).padStart(2,'0'),{class:'tiny',fill:C.ghost});const lines=textWrap(t.title,41).slice(0,2);txt(gg,xx+36,y+17,lines[0]||'',{class:'body',fill:C.ink,'font-weight':selected?'700':'500'});if(lines[1])txt(gg,xx+36,y+31,lines[1],{class:'body',fill:C.ink});txt(gg,xx+36,y+49,`${t.bucket} · ${t.earliest}–${t.latest} · ${t.duration}m`,{class:'tiny',fill:selected?C.red:C.ghost});if(routed){txt(gg,xx+w-10,y+18,`ROUTE ${routeIndex+1}`,{class:'tiny',fill:C.red,'text-anchor':'end'});line(gg,xx+w-64,y+23,xx+w-9,y+23,{stroke:C.red,'stroke-width':1})}
  if(data.state.sort==='manual'){const up=group(gg,{class:'ctrl'}),dn=group(gg,{class:'ctrl'});txt(up,xx+w-25,y+39,'↑',{class:'body',fill:C.graph,'text-anchor':'middle'});txt(dn,xx+w-10,y+39,'↓',{class:'body',fill:C.graph,'text-anchor':'middle'});add(up,'rect',{x:xx+w-34,y:y+24,width:18,height:20,fill:'transparent'});add(dn,'rect',{x:xx+w-18,y:y+24,width:18,height:20,fill:'transparent'});up.addEventListener('click',e=>{e.stopPropagation();moveManual(t.id,-1)});dn.addEventListener('click',e=>{e.stopPropagation();moveManual(t.id,1)})}
  gg.addEventListener('click',()=>{data.state.selected=t.id;event('FOCUS',t.id,'spine');render()});gg.addEventListener('dblclick',()=>openTask(t.id));gg.addEventListener('keydown',e=>{if(e.key==='Enter')openTask(t.id)});
 });
 const done=data.tasks.filter(t=>t.status==='done').slice(-5);if(done.length){txt(g,815,1505,'RESIDUAL / COMPLETED',{class:'smallcaps micro',fill:C.ghost});done.forEach((t,i)=>txt(g,815,1522+i*13,`— ${t.title.slice(0,35)}`,{class:'tiny',fill:C.ghost,'fill-opacity':.55}))}
}

function renderMargins(){clear('#marginLayer');const g=$('#marginLayer'),act=active();
 const contexts=['home','computer','phone','tools','printer','bench','errand','calls','low-energy'];let y=190;
 const foldShow=k=>!!(ui.folds&&ui.folds[k]);
 const foldRow=(k,title,witness)=>{const open=foldShow(k),gg=group(g,{class:'ctrl'});txt(gg,58,y,(open?'▾ ':'▸ ')+title,{class:'smallcaps label',fill:C.ink});if(witness)txt(gg,214,y,witness,{class:'micro',fill:C.ghost,'text-anchor':'end'});add(gg,'rect',{x:52,y:y-14,width:170,height:20,fill:'transparent'});gg.addEventListener('click',()=>{ui.folds=ui.folds||{};ui.folds[k]=!foldShow(k);render()});y+=22};
 foldRow('conditions','CONDITIONS',act.size?('● '+act.size):'—');
 if(foldShow('conditions')){contexts.forEach((c,i)=>{const yy=y+i*24,on=act.has(c),gg=group(g,{class:'ctrl'});add(gg,'circle',{cx:66,cy:yy-4,r:5.5,fill:on?C.ink:C.paper,stroke:C.ink,'stroke-width':.9});txt(gg,82,yy,c.toUpperCase(),{class:'micro',fill:on?C.ink:C.ghost});add(gg,'rect',{x:55,y:yy-16,width:145,height:22,fill:'transparent'});gg.addEventListener('click',()=>toggleContext(c))});y+=contexts.length*24+2}
 foldRow('range','RANGE',data.state.horizon===9999?'DAY':data.state.horizon+'m');
 if(foldShow('range')){[{n:'30 MIN',v:30},{n:'3 HOURS',v:180},{n:'REST OF DAY',v:9999}].forEach((o,i)=>{const yy=y+i*24,on=data.state.horizon===o.v,gg=group(g,{class:'ctrl'});add(gg,'circle',{cx:66,cy:yy-4,r:5.5,fill:on?C.red:C.paper,stroke:on?C.red:C.ink,'stroke-width':.9});txt(gg,82,yy,o.n,{class:'micro',fill:on?C.red:C.ghost});add(gg,'rect',{x:55,y:yy-16,width:145,height:22,fill:'transparent'});gg.addEventListener('click',()=>{checkpoint('HORIZON');data.state.horizon=o.v;event('HORIZON','',String(o.v));render()})});y+=3*24+2}
 foldRow('order','ORDER',{focus:'FOCUS',time:'TIME',manual:'MANUAL'}[data.state.sort]||'FOCUS');
 if(foldShow('order')){[{n:'FOCUS / ADAPTIVE',v:'focus'},{n:'TIME',v:'time'},{n:'MANUAL',v:'manual'}].forEach((o,i)=>{const yy=y+i*24,on=data.state.sort===o.v,gg=group(g,{class:'ctrl'});add(gg,'rect',{x:60,y:yy-10,width:11,height:11,fill:on?C.ink:C.paper,stroke:C.ink,'stroke-width':.8});txt(gg,82,yy,o.n,{class:'micro',fill:on?C.ink:C.ghost});add(gg,'rect',{x:55,y:yy-17,width:155,height:22,fill:'transparent'});gg.addEventListener('click',()=>{checkpoint('SORT');data.state.sort=o.v;event('SORT','',o.v);render()})});y+=3*24+2}
 foldRow('ink','INK',{quiet:'CALM',structure:'ATLAS',full:'FABRIC'}[data.state.ink]||'ATLAS');
 if(foldShow('ink')){[{n:'CALM',v:'quiet'},{n:'ATLAS',v:'structure'},{n:'FULL FABRIC',v:'full'}].forEach((o,i)=>{const yy=y+i*24,on=data.state.ink===o.v,gg=group(g,{class:'ctrl'});add(gg,'rect',{x:60,y:yy-10,width:11,height:11,fill:on?C.red:C.paper,stroke:on?C.red:C.ink,'stroke-width':.8});txt(gg,82,yy,o.n,{class:'micro',fill:on?C.red:C.ghost});add(gg,'rect',{x:55,y:yy-17,width:155,height:22,fill:'transparent'});gg.addEventListener('click',()=>{checkpoint('INK');data.state.ink=o.v;event('INK','',o.v);render()})});y+=3*24+2}
 foldRow('lens','APERTURE',data.state.lens==='focus'?'FOCUS':'ATLAS');
 if(foldShow('lens')){[{n:'ATLAS / WHOLE FIELD',v:'atlas'},{n:'FOCUS / NEIGHBORHOOD',v:'focus'}].forEach((o,i)=>{const yy=y+i*24,on=data.state.lens===o.v,gg=group(g,{class:'ctrl'});add(gg,'circle',{cx:66,cy:yy-4,r:5.5,fill:on?C.red:C.paper,stroke:on?C.red:C.ink,'stroke-width':.9});txt(gg,82,yy,o.n,{class:'micro',fill:on?C.red:C.ghost});add(gg,'rect',{x:55,y:yy-16,width:165,height:22,fill:'transparent'});gg.addEventListener('click',()=>{checkpoint('LENS');data.state.lens=o.v;event('LENS','',o.v);render()})});y+=2*24+2}
 foldRow('scale','SCALE',ui.semanticScale.toUpperCase());
 if(foldShow('scale')){[{n:'AUTO',v:'auto'},{n:'DISTRICTS',v:'districts'},{n:'PARCELS',v:'parcels'}].forEach((o,i)=>{const yy=y+i*23,on=ui.semanticScale===o.v,gg=group(g,{class:'ctrl'});add(gg,'circle',{cx:66,cy:yy-4,r:5.2,fill:on?C.blue:C.paper,stroke:on?C.blue:C.ink,'stroke-width':.8});txt(gg,82,yy,o.n,{class:'micro',fill:on?C.blue:C.ghost});add(gg,'rect',{x:55,y:yy-16,width:145,height:21,fill:'transparent'});gg.addEventListener('click',()=>{ui.semanticScale=o.v;if(o.v==='districts')ui.district=null;render()})});y+=3*23+2}
 if(ui.district){const gg=group(g,{class:'ctrl'});txt(gg,58,y+14,`DISTRICT / ${ui.district.toUpperCase()}  × CLEAR`,{class:'tiny',fill:C.red});add(gg,'rect',{x:52,y,width:180,height:20,fill:'transparent'});gg.addEventListener('click',clearDistrict);y+=22}
 foldRow('method','METHOD / 法','');
 if(foldShow('method')){['DISTRICT = RAREST CONTEXT','HUB = SHARED CONTEXT','SCENARIO = NONCANONICAL Δ','SOURCE = PROVENANCE BIAS'].forEach((s,i)=>txt(g,58,y+18+i*16,s,{class:'tiny',fill:C.graph}));y+=4*16+10}
 y+=6;line(g,58,y,215,y,{stroke:C.line,'stroke-width':.8});y+=18;txt(g,58,y,'THIS VIEW HIDES:',{class:'micro',fill:C.ghost});y+=18;txt(g,58,y,semanticMode()==='districts'?'PARCEL MICRODETAIL':data.state.lens==='focus'?'UNRELATED RELATIONS + DETAIL':data.state.ink==='quiet'?'RELATION FABRIC + MICROSTRUCTURE':'NOTHING STRUCTURAL',{class:'tiny',fill:C.red});
 // anchors right
 txt(g,952,190,'ANCHORS / 锚点',{class:'smallcaps label',fill:C.ink});txt(g,952,208,'HARD CONSTRAINTS',{class:'micro',fill:C.ghost});data.anchors.forEach((a,i)=>{const y=238+i*64,gg=group(g,{class:'ctrl'});line(gg,952,y-10,1110,y-10,{stroke:C.red,'stroke-width':1.1,'stroke-opacity':.7});txt(gg,952,y+5,`${a.start}—${a.end}`,{class:'micro',fill:C.red});textWrap(a.title,28).slice(0,2).forEach((ss,k)=>txt(gg,952,y+22+k*13,ss,{class:'tiny',fill:C.ink}));add(gg,'rect',{x:945,y:y-16,width:175,height:55,fill:'transparent'});gg.addEventListener('click',()=>openAnchor(a.id))});const newA=group(g,{class:'ctrl'});txt(newA,952,370,'＋ NEW ANCHOR',{class:'micro',fill:C.red});add(newA,'rect',{x:945,y:356,width:120,height:22,fill:'transparent'});newA.addEventListener('click',newAnchor);
 const f=focus();txt(g,952,418,'FOCUS RECORD',{class:'smallcaps label',fill:C.ink});if(f){txt(g,952,438,f.id.toUpperCase(),{class:'tiny',fill:C.red});textWrap(f.title,28).slice(0,3).forEach((ss,k)=>txt(g,952,459+k*14,ss,{class:'body',fill:C.ink}));txt(g,952,511,`${f.bucket} · COST ${Math.round(f.cost)} · SCORE ${f.score}`,{class:'tiny',fill:C.ghost});txt(g,952,527,`${f.earliest}–${f.latest} · ${f.duration}m · GAP ${f.freeGap}m`,{class:'tiny',fill:f.gapFit?C.blue:C.ghost});
  txt(g,952,555,'WHY HERE / SCORE PARTS',{class:'micro',fill:C.graph});const parts=[['VALUE',f.why.value],['CONTEXT',f.why.context],['URGENCY',f.why.urgency],['SETUP',f.why.setup],['TIME',f.why.time],['BLOCK',f.why.dependencies],['LOOK',f.why.horizon],['GAP',f.why.gap],['SOURCE',f.why.source]];parts.forEach((p,i)=>{const y=573+i*14,v=p[1],w=clamp(Math.abs(v),0,40)*1.6;txt(g,952,y,p[0],{class:'tiny',fill:C.ghost});line(g,1000,y-3,1000+(v>=0?w:-w),y-3,{stroke:v>=0?(p[0]==='GAP'?C.blue:C.ink):C.red,'stroke-width':2,'stroke-opacity':.55})});
  txt(g,952,686,`SOURCE ${f.sourceClass||'USER'}${f.provenance?' · '+f.provenance.slice(0,18):''}`,{class:'tiny',fill:(f.sourceClass||'USER')==='USER'?C.ink:C.ghost});txt(g,952,700,'NEARBY IN STATE / PREVIEW',{class:'micro',fill:C.graph});bundleCandidates(f).forEach((b,i)=>{const y=719+i*31,gg=group(g,{class:'ctrl'});txt(gg,952,y,`+ ${b.x.title.slice(0,24)}`,{class:'tiny',fill:C.ink});txt(gg,962,y+12,`${b.shared.join('+')||'window'} · overlap ${b.ov}m${b.x.gapFit?' · gapfit':''}`,{class:'tiny',fill:b.x.gapFit?C.blue:C.ghost});add(gg,'rect',{x:945,y:y-12,width:175,height:27,fill:'transparent'});gg.addEventListener('click',()=>previewCandidate(b.x.id))});
  const routed=data.state.route.includes(f.id),acts=[{y:820,label:ui.previewBundle.length?`PREVIEW ${ui.previewBundle.length} · ACT → RUN`:'PREVIEW BEST BUNDLE',fn:()=>ui.previewBundle.length?actPreview():previewBundle(),accent:C.blue},{y:842,label:ui.previewBundle.length?'CLEAR PREVIEW':(routed?'REMOVE FROM RUN':`ACT FOCUS → RUN ${data.state.route.length}/3`),fn:()=>ui.previewBundle.length?clearPreview():routeToggle(f.id),accent:ui.previewBundle.length?C.blue:C.red},{y:864,label:'EDIT RECORD',fn:()=>openTask(f.id),accent:C.graph},{y:886,label:f.status==='done'?'REOPEN':'MARK DONE',fn:()=>toggleDone(f.id),accent:C.graph}];acts.forEach(a=>{const gg=group(g,{class:'ctrl'});txt(gg,952,a.y,a.label,{class:'micro',fill:a.accent});line(gg,952,a.y+4,1094,a.y+4,{stroke:C.line,'stroke-width':.7});add(gg,'rect',{x:945,y:a.y-13,width:155,height:22,fill:'transparent'});gg.addEventListener('click',a.fn)});
  txt(g,952,922,'PROPOSAL PIPELINE',{class:'smallcaps label',fill:C.ink});const pphase=ui.previewBundle.length?'PREVIEW':data.state.route.length?'ACT':'SEE';[['SEE','SEE'],['PREVIEW','PREVIEW'],['ACT','ACT'],['RETURN','RETURN']].forEach((st,i)=>{const x=952+i*40,on=pphase===st[1];txt(g,x,940,st[0],{class:'tiny',fill:on?(st[0]==='PREVIEW'?C.blue:C.red):C.ghost})});
  // Four-station work cycle imported from the operator grammar, kept secondary and operational.
  txt(g,952,972,'WORK CYCLE / OPERATOR',{class:'smallcaps label',fill:C.ink});const phase=phaseFor(f),stations=[['CONCH','RECEIVE','receive'],['KERIS','CUT','cut'],['W8','CARRY','carry'],['SPIRAL','RETURN','return']];line(g,964,991,964,1073,{stroke:C.line,'stroke-width':.8});stations.forEach((st,i)=>{const y=993+i*27,on=phase===st[2];add(g,'circle',{cx:964,cy:y,r:4.5,fill:on?C.red:C.paper,stroke:on?C.red:C.ink,'stroke-width':.8});txt(g,978,y+3,`${st[0]} / ${st[1]}`,{class:'micro',fill:on?C.red:C.graph})});
 }
 if(ui.scenario){const sd=scenarioDiffs(),sf=sd.find(d=>d.id===data.state.selected);txt(g,952,1104,'COUNTERFACTUAL / Δ FIELD',{class:'smallcaps label',fill:C.blue});if(sf){txt(g,952,1122,`${sf.current.bucket} → ${sf.future.bucket} · COST ${Math.round(sf.current.cost)} → ${Math.round(sf.future.cost)} · Δ ${sf.gain>=0?'+':''}${sf.gain}`,{class:'tiny',fill:C.blue})}sd.slice(0,4).forEach((d,i)=>txt(g,952,1140+i*14,`${d.gain>=0?'GAIN':'LOSS'} ${String(Math.abs(d.gain)).padStart(2,'0')} · ${d.title.slice(0,23)}`,{class:'tiny',fill:d.gain>=0?C.blue:C.ghost}));const ap=group(g,{class:'ctrl'});txt(ap,952,1203,'APPLY SCENARIO',{class:'micro',fill:C.red});add(ap,'rect',{x:945,y:1189,width:115,height:22,fill:'transparent'});ap.addEventListener('click',()=>{const sim=ui.scenario;checkpoint('SCENARIO_APPLY');data.state.now=sim.now;data.state.contexts=[...sim.contexts];data.state.horizon=sim.horizon;event('SCENARIO_APPLY','',`${sim.now}|${sim.contexts.join('+')}`);ui.scenario=null;render()});const cp=group(g,{class:'ctrl'});txt(cp,1070,1203,'CLEAR',{class:'micro',fill:C.blue});add(cp,'rect',{x:1063,y:1189,width:55,height:22,fill:'transparent'});cp.addEventListener('click',()=>{ui.scenario=null;render()})}
 const gap=nextHardAnchor();txt(g,952,1230,'RUNWAY',{class:'smallcaps label',fill:C.ink});txt(g,952,1249,gap.kind==='inside'?`INSIDE ANCHOR · FREE GAP 0m`:`FREE GAP ${gap.minutes}m → ${gap.anchor?gap.anchor.start:data.meta.dayEnd}`,{class:'micro',fill:gap.minutes?C.blue:C.red});txt(g,952,1266,'LOOK-AHEAD ≠ FREE GAP',{class:'tiny',fill:C.ghost});
 // map key / utilities
 add(g,'rect',{x:930,y:1515,width:214,height:198,fill:'none',stroke:C.line,'stroke-width':.8});txt(g,944,1538,'MAP KEY / UTILITY',{class:'smallcaps label',fill:C.ink});[['━━━━','route / hard boundary',C.red],['━━━━','free gap / runway',C.blue],['────','dependency',C.ink],['┄P┄','preview / not canon',C.blue],['╭─╮','context hub relation',C.graph],['▱','semantic district',C.blue],['░','hidden / residual',C.ghost]].forEach((k,i)=>{txt(g,944,1561+i*14,k[0],{class:'micro',fill:k[2]});txt(g,990,1561+i*14,k[1],{class:'tiny',fill:C.graph})});[{y:1648,label:'∥ PAUSE / MARK INTERRUPT',fn:()=>{captureInterruption('manual');ui.resumeSeed=loadResumeSeed();ui.resumeStartedAt=Date.now();render();toast('Interruption seed saved')}},{y:1666,label:'↶ UNDO',fn:undo},{y:1684,label:'↥ JSON / EXPORT',fn:openJson},{y:1702,label:'⎙ PRINT ATLAS',fn:()=>window.print()}].forEach(a=>{const gg=group(g,{class:'ctrl'});txt(gg,944,a.y,a.label,{class:'micro',fill:a.label.includes('RETURN')||a.label.includes('NEW')?C.red:C.graph});add(gg,'rect',{x:938,y:a.y-13,width:165,height:18,fill:'transparent'});gg.addEventListener('click',a.fn)});
 txt(g,37,1240,'POSSIBILITY',{class:'smallcaps label',fill:C.red,'transform':'rotate(-90 37 1240)','text-anchor':'middle'});txt(g,1163,1240,'EXECUTION',{class:'smallcaps label',fill:C.red,'transform':'rotate(90 1163 1240)','text-anchor':'middle'});
}

function renderLedger(){clear('#ledgerLayer');const g=$('#ledgerLayer'),ev=data.evidence||{};add(g,'rect',{x:58,y:1530,width:250,height:220,fill:'none',stroke:C.line,'stroke-width':.8});txt(g,72,1553,'PROOF GATE / 实证',{class:'smallcaps label',fill:C.ink});txt(g,72,1570,'ORIENT · MISS · NOISE · FRICTION · RETURN',{class:'tiny',fill:C.ghost});const cats=[['ORIENT','orient'],['MISS','miss'],['NOISE','noise'],['FRICTION','friction'],['RETURN','return']];cats.forEach((c,i)=>{const y=1595+i*25,n=(ev[c[1]]||[]).length,gg=group(g,{class:'ctrl'});add(gg,'circle',{cx:78,cy:y-4,r:5.2,fill:i===0?C.red:C.paper,stroke:i===0?C.red:C.ink,'stroke-width':.9});txt(gg,94,y,c[0],{class:'micro',fill:i===0?C.red:C.ink});txt(gg,286,y,String(n).padStart(2,'0'),{class:'micro',fill:C.ghost,'text-anchor':'end'});add(gg,'rect',{x:68,y:y-15,width:222,height:20,fill:'transparent'});gg.addEventListener('click',()=>openEvidence(c[1],c[0]))});const orient=ui.firstActAt?Math.round((ui.firstActAt-ui.sessionStarted)/1000):null;txt(g,72,1727,`SESSION · ORIENT ${orient??'—'}s · REORIENT ${ui.lastReorientMs!=null?Math.round(ui.lastReorientMs/1000)+'s':'—'} · FOCUS ${ui.focusChanges} · CTX ${ui.contextChanges} · ACT ${ui.acts} · A/P ${ui.projectionActs.atlas}/${ui.projectionActs.plain}`,{class:'tiny',fill:C.ghost});txt(g,72,1742,'MEASURE → FALSIFY → PROMOTE / FREEZE.',{class:'tiny',fill:C.ghost});
 add(g,'rect',{x:330,y:1560,width:540,height:190,fill:'none',stroke:C.line,'stroke-width':.8});txt(g,348,1583,'RETURN LEDGER / 归还',{class:'smallcaps label',fill:C.ink});txt(g,348,1600,`RECENT CANONICAL EVENTS · UNDO ${data.undo?.length||0}/15`,{class:'tiny',fill:C.ghost});const recent=(data.events||[]).slice(-7).reverse();recent.forEach((e,i)=>{const y=1622+i*17,at=e.at?.slice(11,16)||'--:--';txt(g,348,y,at,{class:'tiny',fill:C.ghost});txt(g,390,y,e.type,{class:'tiny',fill:['ROUTE','DONE','RETURN'].includes(e.type)?C.red:C.graph});txt(g,458,y,(e.subject||e.detail||'').replace('t:','').slice(0,48),{class:'tiny',fill:C.graph})});
 const d=data.tasks.map(opportunity),open=d.filter(t=>t.status!=='done'),now=open.filter(t=>t.bucket==='NOW').length,blocked=open.filter(t=>t.bucket==='BLOCKED').length,missed=open.filter(t=>t.bucket==='MISSED').length,done=d.length-open.length,gap=nextHardAnchor();txt(g,348,1740,`OPEN ${open.length} · NOW ${now} · BLOCKED ${blocked} · MISSED ${missed} · DONE ${done} · GAP ${gap.minutes}m · ROUTE ${data.state.route.length}/3 · CHECK ${checksum()}`,{class:'tiny',fill:missed?C.red:C.ghost});
}

function forecastSamples(step=60){
 const out=[],lo=dayStart(),hi=dayEnd(),start=Math.ceil(lo/step)*step;
 for(let m=start;m<=hi;m+=step){
  const sim={now:mh(m),contexts:[...(data.state.contexts||[])],horizon:data.state.horizon};
  const candidates=data.tasks.filter(t=>t.status!=='done').map(t=>opportunityAt(t,sim)).filter(t=>t.bucket!=='MISSED').sort((a,b)=>b.score-a.score||a.cost-b.cost);
  const top=candidates[0]||null,cheap=candidates.filter(t=>t.inWindow&&t.cost<=18).length,soon=candidates.filter(t=>['NOW','SOON'].includes(t.bucket)).length;
  out.push({m,now:mh(m),top,cheap,soon,sim});
 }
 return out;
}
function renderForecast(){
 clear('#forecastLayer');const g=$('#forecastLayer'),samples=forecastSamples(),x0=58,x1=1142,y0=1910,y1=2177,w=(x1-x0)/Math.max(1,samples.length);
 line(g,58,1888,1142,1888,{stroke:C.ink,'stroke-width':.8,'stroke-opacity':.55});
 txt(g,58,1910,'TIDE / OPPORTUNITY FORECAST',{class:'smallcaps label',fill:C.ink});
 txt(g,58,1928,'NON-MUTATING HOURLY SWEEP · SAME CONTEXTS · TAP AN HOUR → SCENARIO',{class:'tiny',fill:C.ghost});
 samples.forEach((s,i)=>{
  const x=x0+i*w,gg=group(g,{class:'ctrl'}),selected=ui.scenario?.now===s.now;
  add(gg,'rect',{x:x+2,y:y0+38,width:Math.max(12,w-5),height:178,fill:selected?'rgba(82,108,119,.10)':'rgba(25,25,21,.012)',stroke:selected?C.blue:C.line,'stroke-width':selected?1.2:.55});
  txt(gg,x+w/2,y0+57,s.now,{class:'micro',fill:selected?C.blue:C.ink,'text-anchor':'middle'});
  const barH=clamp(s.cheap*10,0,55);add(gg,'rect',{x:x+w*.22,y:y0+69+(55-barH),width:w*.56,height:barH,fill:s.cheap?C.blue:C.line,'fill-opacity':s.cheap?.52:.25});
  txt(gg,x+w/2,y0+139,`${s.cheap} NOW · ${s.soon} NEAR`,{class:'tiny',fill:C.ghost,'text-anchor':'middle'});
  if(s.top){const lines=textWrap(s.top.title,18).slice(0,3);lines.forEach((t,k)=>txt(gg,x+w/2,y0+157+k*12,t,{class:'tiny',fill:C.graph,'text-anchor':'middle'}));txt(gg,x+w/2,y0+200,`COST ${Math.round(s.top.cost)}`,{class:'tiny',fill:s.top.cost<=18?C.blue:C.ghost,'text-anchor':'middle'})}
  add(gg,'rect',{x:x+2,y:y0+38,width:Math.max(12,w-5),height:178,fill:'transparent'});
  gg.addEventListener('click',()=>{ui.scenario={...s.sim};render();toast(`Preview ${s.now} · canon unchanged`)});
 });
 // canonical NOW marker across tide
 const span=Math.max(1,dayEnd()-dayStart()),nx=x0+clamp((hm(data.state.now)-dayStart())/span,0,1)*(x1-x0);line(g,nx,y0+31,nx,y1,{stroke:C.red,'stroke-width':1.3,'stroke-opacity':.78});txt(g,nx,y0+27,'NOW',{class:'tiny',fill:C.red,'text-anchor':'middle'});
 // hard anchors as red bands
 data.anchors.forEach(a=>{const ax=x0+clamp((hm(a.start)-dayStart())/span,0,1)*(x1-x0),bx=x0+clamp((hm(a.end)-dayStart())/span,0,1)*(x1-x0);add(g,'rect',{x:ax,y:y1-16,width:Math.max(2,bx-ax),height:5,fill:C.red,'fill-opacity':.7});});
 txt(g,58,2200,'TIDE IS A FORECAST, NOT A SCHEDULE. BLUE = CHEAP OPPORTUNITY; RED = CANONICAL NOW / HARD ANCHOR.',{class:'tiny',fill:C.ghost});
}


function routeMetrics(ids=data.state.route,startNow=hm(data.state.now)){
 const gap=nextHardAnchor(startNow),available=gap.kind==='open'?Math.max(0,dayEnd()-startNow):gap.minutes;
 let cursor=startNow,switches=0,deadlineRisk=0,prev=null,used=0;const legs=[];
 for(const id of ids){const t=taskById(id);if(!t)continue;const dur=+t.duration||15;if(prev&&sharedContexts(prev,t).length===0)switches++;cursor+=dur;used+=dur;const late=cursor>hm(t.latest);if(late)deadlineRisk++;legs.push({id,title:t.title,end:cursor,late,shared:prev?sharedContexts(prev,t):[]});prev=t}
 const slack=available-used;return{gap,available,used,slack,fit:slack>=0&&gap.kind!=='inside',switches,deadlineRisk,legs};
}
function proposeGapPack(){
 const cap=Math.max(0,3-data.state.route.length);if(cap<=0){toast('RUN full: 3/3');return}
 const now=hm(data.state.now),gap=nextHardAnchor(now),available=gap.kind==='open'?Math.max(0,dayEnd()-now):gap.minutes;if(available<=0){toast('No free gap before hard anchor');return}
 let remain=available;const picked=[],act=active();
 const candidates=data.tasks.filter(t=>t.status!=='done'&&!data.state.route.includes(t.id)).map(t=>opportunity(t)).filter(t=>!['MISSED','BLOCKED'].includes(t.bucket)&&hm(t.earliest)<=now+available&&(+t.duration||15)<=available).sort((a,b)=>{const aa=(a.hits?.length||0)*7+a.score,bb=(b.hits?.length||0)*7+b.score;return bb-aa||a.cost-b.cost});
 for(const t of candidates){if(picked.length>=cap)break;const dur=+t.duration||15;if(dur<=remain){picked.push(t.id);remain-=dur}}
 ui.previewBundle=picked;render();toast(picked.length?`Previewed ${picked.length} task pack · ${available-remain}/${available}m`:'No coherent pack found');
}
function stressPreview(minutes=30){const now=clamp(hm(data.state.now)+minutes,dayStart(),dayEnd());ui.scenario={now:mh(now),contexts:[...(data.state.contexts||[])],horizon:data.state.horizon};render();toast(`Stress preview +${minutes}m · canon unchanged`)}
function stressSummary(minutes=30){
 const sim={now:mh(clamp(hm(data.state.now)+minutes,dayStart(),dayEnd())),contexts:[...(data.state.contexts||[])],horizon:data.state.horizon};
 const current=data.tasks.filter(t=>t.status!=='done').map(t=>opportunity(t)),future=data.tasks.filter(t=>t.status!=='done').map(t=>opportunityAt(t,sim));
 const map=new Map(current.map(t=>[t.id,t]));const newlyMissed=future.filter(t=>t.bucket==='MISSED'&&map.get(t.id)?.bucket!=='MISSED');const worsened=future.filter(t=>{const c=map.get(t.id);return c&&t.cost-c.cost>=20&&t.bucket!=='MISSED'});
 const route=routeMetrics(data.state.route,hm(sim.now));return{sim,newlyMissed,worsened,route};
}
function renderStrategy(){
 clear('#strategyLayer');const g=$('#strategyLayer'),y=2240,rm=routeMetrics(),stress=stressSummary(30),gap=rm.gap;
 line(g,58,y-18,1142,y-18,{stroke:C.ink,'stroke-width':.8,'stroke-opacity':.55});
 txt(g,58,y,'RUN FIT / ROBUSTNESS',{class:'smallcaps label',fill:C.ink});txt(g,58,y+18,'TEMPORARY ROUTE MUST FIT THE REAL GAP · PREVIEWS NEVER MUTATE CANON',{class:'tiny',fill:C.ghost});
 add(g,'rect',{x:58,y:y+34,width:510,height:158,fill:'none',stroke:C.line,'stroke-width':.8});
 txt(g,76,y+58,`FREE GAP ${rm.available}m · RUN ${data.state.route.length}/3 · USED ${rm.used}m`,{class:'micro',fill:C.graph});
 txt(g,76,y+80,`SLACK ${rm.slack>=0?'+':''}${rm.slack}m · SWITCHES ${rm.switches} · DEADLINE RISK ${rm.deadlineRisk}`,{class:'micro',fill:rm.fit&&rm.deadlineRisk===0?C.blue:C.red});
 txt(g,76,y+103,gap.anchor?`NEXT HARD ANCHOR ${gap.anchor.start} · ${gap.anchor.title.slice(0,38)}`:'NO FURTHER HARD ANCHOR',{class:'tiny',fill:C.ghost});
 const fitLabel=rm.fit&&rm.deadlineRisk===0?'ROUTE FITS':'ROUTE NEEDS REPAIR';txt(g,76,y+130,fitLabel,{class:'smallcaps body',fill:fitLabel==='ROUTE FITS'?C.blue:C.red});
 const pack=group(g,{class:'ctrl'});txt(pack,76,y+166,'◇ PREVIEW GAP PACK',{class:'micro',fill:C.blue});add(pack,'rect',{x:69,y:y+150,width:140,height:24,fill:'transparent'});pack.addEventListener('click',proposeGapPack);
 const actp=group(g,{class:'ctrl'});txt(actp,232,y+166,'ACT PREVIEW → RUN',{class:'micro',fill:ui.previewBundle.length?C.red:C.ghost});add(actp,'rect',{x:225,y:y+150,width:145,height:24,fill:'transparent'});actp.addEventListener('click',actPreview);
 const clearp=group(g,{class:'ctrl'});txt(clearp,392,y+166,'CLEAR PREVIEW',{class:'micro',fill:C.graph});add(clearp,'rect',{x:385,y:y+150,width:118,height:24,fill:'transparent'});clearp.addEventListener('click',clearPreview);
 add(g,'rect',{x:590,y:y+34,width:552,height:158,fill:'none',stroke:C.line,'stroke-width':.8});
 txt(g,608,y+58,'DELAY STRESS / +30 MIN',{class:'smallcaps micro',fill:C.ink});
 txt(g,608,y+80,`NEWLY MISSED ${stress.newlyMissed.length} · COST +20 ${stress.worsened.length} · ROUTE SLACK ${stress.route.slack>=0?'+':''}${stress.route.slack}m`,{class:'micro',fill:(stress.newlyMissed.length||stress.route.slack<0)?C.red:C.blue});
 const risk=[...stress.newlyMissed,...stress.worsened].slice(0,3);risk.forEach((t,i)=>txt(g,608,y+104+i*15,`${t.bucket==='MISSED'?'MISS':'RISK'} · ${t.title.slice(0,42)}`,{class:'tiny',fill:t.bucket==='MISSED'?C.red:C.graph}));if(!risk.length)txt(g,608,y+104,'NO MATERIAL +30m DEGRADATION DETECTED',{class:'tiny',fill:C.ghost});
 const st=group(g,{class:'ctrl'});txt(st,608,y+166,'◇ PREVIEW +30m',{class:'micro',fill:C.blue});add(st,'rect',{x:600,y:y+150,width:120,height:24,fill:'transparent'});st.addEventListener('click',()=>stressPreview(30));
 const st60=group(g,{class:'ctrl'});txt(st60,744,y+166,'◇ PREVIEW +60m',{class:'micro',fill:C.blue});add(st60,'rect',{x:736,y:y+150,width:120,height:24,fill:'transparent'});st60.addEventListener('click',()=>stressPreview(60));
 txt(g,58,2440,'FIT IS A CHECK, NOT AN OPTIMIZER. PACK / STRESS ARE SCENARIOS UNTIL ACT OR APPLY. DATA STAYS LOCAL UNLESS YOU EXPORT / COPY A CAPSULE.',{class:'tiny',fill:C.ghost});
}

function renderOverlay(){clear('#overlayLayer');const g=$('#overlayLayer'),issues=validateState(data);if(ui.resumeSeed){const s=ui.resumeSeed,away=Math.max(1,Math.round((s.away||Date.now()-Date.parse(s.at))/60000)),t=taskById(s.selected);add(g,'rect',{x:270,y:137,width:660,height:54,fill:'rgba(244,239,228,.94)',stroke:C.blue,'stroke-width':1.1});txt(g,288,157,`RESUME APERTURE · AWAY ${away}m · RUN ${s.route?.length||0}/3`,{class:'smallcaps micro',fill:C.blue});txt(g,288,175,`FOCUS ${t?t.title.slice(0,43):'—'} · SAVED NOW ${s.now}`,{class:'tiny',fill:C.graph});const r1=group(g,{class:'ctrl'});txt(r1,754,157,'RESTORE FOCUS',{class:'micro',fill:C.red});add(r1,'rect',{x:744,y:144,width:105,height:20,fill:'transparent'});r1.addEventListener('click',()=>resumeFocus(false));const r2=group(g,{class:'ctrl'});txt(r2,754,176,'SYNC NOW + RESUME',{class:'micro',fill:C.blue});add(r2,'rect',{x:744,y:164,width:118,height:20,fill:'transparent'});r2.addEventListener('click',()=>resumeFocus(true));const r3=group(g,{class:'ctrl'});txt(r3,888,176,'DISMISS',{class:'micro',fill:C.ghost});add(r3,'rect',{x:878,y:164,width:50,height:20,fill:'transparent'});r3.addEventListener('click',dismissResume)}txt(g,58,1812,'OPERATIONS',{class:'smallcaps micro',fill:C.ink});txt(g,58,1832,'CLICK = FOCUS · DOUBLE CLICK = EDIT · STATUS = COMPLETE · DRAG NOW = TIME · DRAG E/L = WINDOW',{class:'tiny',fill:C.graph});txt(g,58,1850,'KEYS [ ] ±15m · ↑↓ FOCUS · ENTER EDIT · C ACT · V ABLATE · U UNDO · Q SCENARIO · G GAP PACK',{class:'tiny',fill:C.graph});txt(g,1010,1812,issues.length?`SELFTEST ${issues.length} ISSUE${issues.length===1?'':'S'}`:'SELFTEST OK',{class:'micro',fill:issues.length?C.red:C.graph,'text-anchor':'end'});txt(g,1140,1850,'I-01',{class:'tiny',fill:C.ghost,'text-anchor':'end'});bindDrag()}

function checksum(){let h=2166136261,s=JSON.stringify({tasks:data.tasks,anchors:data.anchors,state:data.state});for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function toggleContext(c){checkpoint('CONTEXT');const a=active();data.state.contexts=a.has(c)?data.state.contexts.filter(x=>x!==c):[...data.state.contexts,c];ui.contextChanges++;event('CONTEXT','',`${c}:${a.has(c)?'off':'on'}`);render()}
function toggleDone(id){const t=taskById(id);if(!t)return;checkpoint(t.status==='done'?'REOPEN':'DONE');t.status=t.status==='done'?'open':'done';if(t.status==='done')data.state.route=data.state.route.filter(x=>x!==id);event(t.status==='done'?'DONE':'REOPEN',id);if(data.state.selected===id&&t.status==='done')data.state.selected=ordered()[0]?.id||id;render()}
function routeToggle(id,forceAdd=false){const i=data.state.route.indexOf(id);if(i>=0&&!forceAdd){checkpoint('UNROUTE');data.state.route.splice(i,1);event('UNROUTE',id)}else if(i<0){if(data.state.route.length>=3){toast('RUN cap: 3');return}checkpoint('ACT');data.state.route.push(id);ui.acts++;recordProjectionAct();if(!ui.firstActAt)ui.firstActAt=Date.now();event('ACT',id,`${data.state.route.length}|${ui.projection}`)}ui.previewBundle=ui.previewBundle.filter(x=>x!==id);render()}
function moveManual(id,d){const i=data.tasks.findIndex(t=>t.id===id),j=clamp(i+d,0,data.tasks.length-1);if(i<0||i===j)return;checkpoint('REORDER');const[m]=data.tasks.splice(i,1);data.tasks.splice(j,0,m);event('REORDER',id,String(j));data.state.selected=id;render()}
function newTask(){taskIsNew=true;editId=null;taskDraft={id:'t:'+Date.now().toString(36),title:'New task',contexts:[...data.state.contexts.slice(0,2)],duration:15,value:3,earliest:data.state.now,latest:data.meta.dayEnd,setup:1,depends:[],status:'open',sourceClass:'USER',provenance:'direct-day-plan',notes:''};fillTaskDialog(taskDraft,true)}
function openTask(id,isNew=false){const t=taskById(id);if(!t)return;taskIsNew=false;editId=id;taskDraft=clone(t);fillTaskDialog(taskDraft,false)}
function fillTaskDialog(t,isNew){$('#taskDialogTitle').textContent=isNew?'NEW TASK RECORD':'EDIT TASK RECORD';$('#fTitle').value=t.title;$('#fEarliest').value=t.earliest;$('#fLatest').value=t.latest;$('#fDuration').value=t.duration;$('#fValue').value=t.value;$('#fContexts').value=(t.contexts||[]).join(', ');$('#fSetup').value=t.setup;$('#fStatus').value=t.status;$('#fDepends').value=(t.depends||[]).join(', ');$('#fSourceClass').value=t.sourceClass||'USER';$('#fProvenance').value=t.provenance||'';$('#fNotes').value=t.notes||'';$('#deleteTask').style.visibility=isNew?'hidden':'visible';$('#duplicateTask').style.visibility=isNew?'hidden':'visible';$('#taskDialog').showModal();setTimeout(()=>$('#fTitle').select(),20)}
function saveTask(){if(!taskDraft)return;const t=clone(taskDraft);t.title=$('#fTitle').value.trim()||'Untitled';t.earliest=$('#fEarliest').value||data.meta.dayStart;t.latest=$('#fLatest').value||data.meta.dayEnd;if(hm(t.latest)<=hm(t.earliest))t.latest=mh(clamp(hm(t.earliest)+5,dayStart(),dayEnd()));t.duration=Math.max(1,+$('#fDuration').value||15);t.value=clamp(+$('#fValue').value||3,1,5);t.contexts=$('#fContexts').value.split(',').map(x=>x.trim()).filter(Boolean);t.setup=clamp(+$('#fSetup').value||0,0,5);t.status=$('#fStatus').value;t.sourceClass=$('#fSourceClass').value||'USER';t.provenance=$('#fProvenance').value.trim();t.depends=$('#fDepends').value.split(',').map(x=>x.trim()).filter(Boolean);t.notes=$('#fNotes').value.trim();checkpoint(taskIsNew?'CREATE':'EDIT');if(taskIsNew){data.tasks.push(t);data.state.selected=t.id;event('CREATE',t.id)}else{const live=taskById(editId);Object.assign(live,t);event('EDIT',live.id)}taskDraft=null;taskIsNew=false;$('#taskDialog').close();render()}
function deleteTask(){if(!editId||taskIsNew)return;checkpoint('DELETE');data.tasks=data.tasks.filter(t=>t.id!==editId);data.state.route=data.state.route.filter(x=>x!==editId);event('DELETE',editId);if(data.state.selected===editId)data.state.selected=ordered()[0]?.id||null;taskDraft=null;$('#taskDialog').close();render()}
function duplicateTask(){const t=taskById(editId);if(!t)return;taskIsNew=true;editId=null;taskDraft=clone(t);taskDraft.id='t:'+Date.now().toString(36);taskDraft.title+=' — copy';taskDraft.status='open';$('#taskDialog').close();fillTaskDialog(taskDraft,true)}
function newAnchor(){anchorIsNew=true;anchorEditId=null;anchorDraft={id:'a:'+Date.now().toString(36),start:data.state.now,end:mh(clamp(hm(data.state.now)+60,dayStart(),dayEnd())),title:'New anchor',note:''};fillAnchorDialog(anchorDraft,true)}
function openAnchor(id,isNew=false){const a=data.anchors.find(x=>x.id===id);if(!a)return;anchorIsNew=false;anchorEditId=id;anchorDraft=clone(a);fillAnchorDialog(anchorDraft,false)}
function fillAnchorDialog(a,isNew){$('#anchorDialogTitle').textContent=isNew?'NEW ANCHOR':'EDIT ANCHOR';$('#aTitle').value=a.title;$('#aStart').value=a.start;$('#aEnd').value=a.end;$('#aNote').value=a.note||'';$('#deleteAnchor').style.visibility=isNew?'hidden':'visible';$('#anchorDialog').showModal()}
function saveAnchor(){if(!anchorDraft)return;const a=clone(anchorDraft);a.title=$('#aTitle').value.trim()||'Anchor';a.start=$('#aStart').value||data.state.now;a.end=$('#aEnd').value||a.start;if(hm(a.end)<hm(a.start))a.end=a.start;a.note=$('#aNote').value.trim();checkpoint(anchorIsNew?'ANCHOR_CREATE':'ANCHOR_EDIT');if(anchorIsNew){data.anchors.push(a);event('ANCHOR_CREATE',a.id)}else{Object.assign(data.anchors.find(x=>x.id===anchorEditId),a);event('ANCHOR_EDIT',a.id)}anchorDraft=null;anchorIsNew=false;$('#anchorDialog').close();render()}
function deleteAnchor(){if(!anchorEditId||anchorIsNew)return;checkpoint('ANCHOR_DELETE');const id=anchorEditId;data.anchors=data.anchors.filter(a=>a.id!==id);event('ANCHOR_DELETE',id);anchorDraft=null;$('#anchorDialog').close();render()}
function openEvidence(kind,label){evidenceKind=kind;$('#evidenceTitle').textContent=label+' / PROOF GATE';$('#evidenceText').value='';$('#evidenceDialog').showModal();setTimeout(()=>$('#evidenceText').focus(),20)}
function saveEvidence(){const s=$('#evidenceText').value.trim();if(!s)return;data.evidence[evidenceKind]=data.evidence[evidenceKind]||[];data.evidence[evidenceKind].push({at:new Date().toISOString(),task:data.state.selected,note:s});event('EVIDENCE',evidenceKind,s.slice(0,36));$('#evidenceDialog').close();render()}
function openJson(){$('#jsonText').value=JSON.stringify(data,null,2);$('#jsonDialog').showModal()}

function encodeCapsule(core=coreSnapshot()){
 const bytes=new TextEncoder().encode(JSON.stringify(core));let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
}
function decodeCapsule(token){
 const b64=token.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(token.length/4)*4,'=');const bin=atob(b64),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes));
}
function capsuleUrl(){const u=new URL(location.href);u.hash='state='+encodeCapsule();return u.toString()}
async function copyCapsule(){
 const url=capsuleUrl();try{await navigator.clipboard.writeText(url);toast('Snapshot capsule copied · local state encoded in URL')}catch{window.prompt('Copy snapshot capsule URL',url)}
}
function maybeLoadCapsule(){
 const m=location.hash.match(/^#state=(.+)$/);if(!m)return false;try{const core=decodeCapsule(m[1]),issues=validateState(core);if(issues.length)throw Error(issues[0]);if(!window.confirm('Load this shared Atlas Dayline capsule into local browser state?'))return false;data={...clone(sample),...core,events:[],undo:[]};normalize(data);ui.previewBundle=[];ui.scenario=null;localStorage.setItem(STORE,JSON.stringify(data));history.replaceState(null,'',location.pathname+location.search);return true}catch(e){toast('Capsule rejected: '+e.message);return false}
}

function svgLocal(evt){const svg=$('#atlas'),pt=svg.createSVGPoint();pt.x=evt.clientX;pt.y=evt.clientY;return pt.matrixTransform(svg.getScreenCTM().inverse())}
function setTimePoint(p){const a=Math.atan2(p.y-500,p.x-600),m=angleMinute(a);data.state.now=mh(m)}
function setWindowPoint(id,kind,p){const t=taskById(id);if(!t)return;const a=Math.atan2(p.y-500,p.x-600),m=angleMinute(a),start=hm(t.earliest),end=hm(t.latest);if(kind==='start')t.earliest=mh(clamp(m,dayStart(),end-5));else t.latest=mh(clamp(m,start+5,dayEnd()))}
function bindDrag(){const svg=$('#atlas');[...svg.querySelectorAll('[data-dragkind]')].forEach(h=>h.onpointerdown=e=>{e.stopPropagation();checkpoint(h.dataset.dragkind==='now'?'TIME':'WINDOW');drag={kind:h.dataset.dragkind,id:h.dataset.id||null,pointer:e.pointerId,checkpointed:true};svg.setPointerCapture?.(e.pointerId)});svg.onpointermove=e=>{if(!drag.kind)return;const p=svgLocal(e);if(drag.kind==='now')setTimePoint(p);else setWindowPoint(drag.id,drag.kind,p);render()};svg.onpointerup=e=>{if(!drag.kind)return;event(drag.kind==='now'?'TIME':'WINDOW',drag.id||'',drag.kind);drag={kind:null,id:null,pointer:null,checkpointed:false};svg.releasePointerCapture?.(e.pointerId);render()}}


/* FIELD LIVE bridge API.
   Repo/CURRENT remains read-only authority. Promotion into Dayline is explicit and browser-local. */
function bridgeAddTask(input={},sourceClass='IMPORTED'){
 const title=String(input.title||'').trim();if(!title)throw Error('title required');
 const now=hm(data.state.now),hi=dayEnd(),lo=dayStart();
 const stem=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,34)||'item';
 const prefix=sourceClass==='USER'?'capture':'field';let id='t:'+prefix+'-'+stem,n=2;while(taskById(id))id='t:'+prefix+'-'+stem+'-'+(n++);
 const earliestM=clamp(input.earliest?hm(input.earliest):now,lo,Math.max(lo,hi-5)),latestM=clamp(input.latest?hm(input.latest):hi,earliestM+5,hi),earliest=mh(earliestM),latest=mh(latestM),duration=clamp(Number(input.duration)||25,5,Math.max(5,latestM-earliestM));
 checkpoint(sourceClass==='USER'?'QUICK_CAPTURE':'FIELD_IMPORT');
 const task={id,title,contexts:Array.isArray(input.contexts)&&input.contexts.length?input.contexts:['computer'],duration,value:clamp(Number(input.value)||4,1,5),earliest,latest,setup:clamp(Number(input.setup)||1,0,5),depends:Array.isArray(input.depends)?input.depends:[],status:'open',sourceClass,provenance:String(input.provenance|| (sourceClass==='USER'?'atlas-live-capture':'FIELD /control/CURRENT.json')),notes:String(input.notes||''),fieldRef:input.sourceRef||null,fieldUpdated:input.sourceUpdated||null};
 data.tasks.push(task);data.state.selected=id;ui.previewBundle=[];event(sourceClass==='USER'?'CAPTURE':'FIELD_IMPORT',id,task.fieldRef||task.provenance);save();render();return clone(task)
}
window.AtlasDayline=Object.freeze({
 version:'branch-i-field-live-0.2.1',
 snapshot:()=>clone(data),
 addFieldTask:input=>bridgeAddTask(input,'IMPORTED'),
 capture:input=>bridgeAddTask(typeof input==='string'?{title:input}:input,'USER'),
 applyContexts:input=>{
   const xs=[...new Set((input?.contexts||[]).map(x=>String(x||'').trim()).filter(Boolean))];if(!xs.length)throw Error('contexts required');
   const prefix=String(input?.replacePrefix||''),base=(data.state.contexts||[]).filter(x=>!prefix||!String(x).startsWith(prefix));
   checkpoint('CONTEXT_HANDOFF');data.state.contexts=[...new Set([...base,...xs])];
   event('CONTEXT_HANDOFF',String(input?.sourceRef||''),xs.join(','));save();render();return [...data.state.contexts]
 },
 lastReturn:()=>{try{return JSON.parse(localStorage.getItem(RETURN_STORE)||'null')}catch{return null}},
 feedback:()=>{
   const ids=new Set([...(data.state.route||[]),data.state.selected].filter(Boolean));
   const tasks=(data.tasks||[]).filter(t=>ids.has(t.id)).map(t=>({id:t.id,title:t.title,status:t.status,contexts:t.contexts,duration:t.duration,earliest:t.earliest,latest:t.latest,sourceClass:t.sourceClass,provenance:t.provenance,fieldRef:t.fieldRef||null}));
   return{schema:'atlas-dayline-feedback/v0.2',generated_at:new Date().toISOString(),authority:'NONE',trigger:'USER_EXPLICIT_COPY',current_host:'/atlas-dayline/?live=1',sources:['/llms.txt','/control/CURRENT.json','browser-local Atlas Dayline DayState'],daystate:{now:data.state.now,contexts:[...(data.state.contexts||[])],route:[...(data.state.route||[])],selected:data.state.selected||null},projection:{view:ui.mobileView,lens:data.state.lens,projection:ui.projection},focus_tasks:tasks,last_return:window.AtlasDayline?.lastReturn?.()||null,evidence:Object.fromEntries(Object.entries(data.evidence||{}).map(([k,v])=>[k,(v||[]).slice(-5)])),recent_events:(data.events||[]).slice(-30),worker_boundary:'Evidence only. Recover live FIELD authority before acting; this packet does not authorize repo/calendar/comms/device/account mutation.'}
 }
});
window.dispatchEvent(new CustomEvent('atlas-dayline:ready',{detail:{version:window.AtlasDayline.version}}));

[...document.querySelectorAll('[data-close]')].forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#saveTask').onclick=saveTask;$('#deleteTask').onclick=deleteTask;$('#duplicateTask').onclick=duplicateTask;$('#saveAnchor').onclick=saveAnchor;$('#deleteAnchor').onclick=deleteAnchor;$('#saveEvidence').onclick=saveEvidence;$('#saveTime').onclick=()=>{if($('#timeInput').value){checkpoint('TIME');data.state.now=$('#timeInput').value;event('TIME','',data.state.now)}$('#timeDialog').close();render()};
$('#syncNowBtn').onclick=syncDeviceNow;$('#formatJson').onclick=()=>{try{$('#jsonText').value=JSON.stringify(JSON.parse($('#jsonText').value),null,2)}catch(e){toast(e.message)}};$('#applyJson').onclick=()=>{try{const x=JSON.parse($('#jsonText').value);if(!x.tasks||!x.state||!x.anchors)throw Error('Expected tasks/state/anchors');normalize(x);const issues=validateState(x);if(issues.length)throw Error(issues[0]);checkpoint('JSON_APPLY');data=x;event('JSON_APPLY');$('#jsonDialog').close();render()}catch(e){toast(e.message)}};$('#exportJson').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='poly-atlas-daystate-branch-i-public.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('#printAtlas').onclick=()=>window.print();$('#resetData').onclick=()=>{checkpoint('RESET');const undoKeep=data.undo;data=clone(sample);normalize(data);data.undo=undoKeep;event('RESET');$('#jsonDialog').close();render();toast('Sample restored')};
$('#shareCapsuleBtn').onclick=copyCapsule;$('#shareCapsuleJson').onclick=copyCapsule;$('#atlasProjectionBtn').onclick=()=>setProjection('atlas');$('#plainProjectionBtn').onclick=()=>setProjection('plain');$('#scenarioBtn').onclick=openScenario;$('#quickNewBtn').onclick=newTask;$('#quickReturnBtn').onclick=returnReceipt;$('#quickReplayBtn').onclick=replayLastReturn;$('#previewScenario').onclick=previewScenario;$('#applyScenario').onclick=applyScenario;$('#clearScenario').onclick=clearScenario;
document.querySelectorAll('[data-mobile-view]').forEach(b=>b.addEventListener('click',()=>{ui.mobileView=b.dataset.mobileView;applyMobileViewport()}));window.addEventListener('resize',applyMobileViewport);
window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;const now=hm(data.state.now);if(e.key==='['){checkpoint('TIME');data.state.now=mh(clamp(now-15,dayStart(),dayEnd()));event('TIME','',data.state.now);render()}else if(e.key===']'){checkpoint('TIME');data.state.now=mh(clamp(now+15,dayStart(),dayEnd()));event('TIME','',data.state.now);render()}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const a=ordered();if(!a.length)return;let i=Math.max(0,a.findIndex(t=>t.id===data.state.selected));i=(i+(e.key==='ArrowDown'?1:-1)+a.length)%a.length;data.state.selected=a[i].id;ui.previewBundle=[];ui.focusChanges++;event('FOCUS',a[i].id,'keyboard');render()}else if(e.key==='Enter'&&data.state.selected)openTask(data.state.selected);else if(e.key.toLowerCase()==='c'&&data.state.selected)routeToggle(data.state.selected);else if(e.key.toLowerCase()==='p')previewBundle();else if(e.key.toLowerCase()==='x')actPreview();else if(e.key.toLowerCase()==='f'){checkpoint('LENS');data.state.lens=data.state.lens==='atlas'?'focus':'atlas';event('LENS','',data.state.lens);render()}else if(e.key.toLowerCase()==='s'){const seq=['auto','districts','parcels'],i=seq.indexOf(ui.semanticScale);ui.semanticScale=seq[(i+1)%seq.length];ui.district=null;render()}else if(e.key.toLowerCase()==='q')openScenario();else if(e.key.toLowerCase()==='g')proposeGapPack();else if(e.key.toLowerCase()==='d')stressPreview(30);else if(e.key.toLowerCase()==='v')setProjection(ui.projection==='atlas'?'plain':'atlas');else if(e.key.toLowerCase()==='u')undo();else if(e.key.toLowerCase()==='n')newTask();else if(e.key.toLowerCase()==='a')newAnchor()});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')captureInterruption('hidden');else maybeOfferResume()});window.addEventListener('pagehide',()=>captureInterruption('pagehide'));const loadedCapsule=maybeLoadCapsule();sessionStart=coreSnapshot();sessionEventStart=(data.events||[]).length;render();setProjection(ui.projection);if(loadedCapsule)setTimeout(()=>toast('Capsule loaded locally · no server persistence'),80);else setTimeout(maybeOfferResume,40);if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
