import {
  bearings,bearingLabel,clamp,hm,ft,deepCopy,defaultState,normalizeTask,normalizeState,
  terrainFor,measuredDuration,gapInfo,score,reach,reachBand,rankedTasks,explainFit,tailRoute
} from './core.js';

const NS='http://www.w3.org/2000/svg';
const STORAGE_KEY='poly-forward-field-pages-v1';
const LEGACY_KEYS=['poly-forward-field-locus-v0.9','poly-forward-field-semantic-painting-v0.8'];
const $=id=>document.getElementById(id);
const svg=$('worldSvg');
const frame=$('worldFrame');
let state=loadState();
let simulationTimer=null, sessionTimer=null, toastTimer=null, deferredInstall=null;
let taskPositions=new Map();

const svgEl=(tag,attrs={},text=null)=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));if(text!==null)n.textContent=text;return n;};
const polar=(cx,cy,r,a)=>[cx+Math.cos(a)*r,cy+Math.sin(a)*r];
const bearingAngle=b=>-Math.PI/2+(bearings.indexOf(b)*Math.PI)/4;
const nowMinutes=()=>{const d=new Date();return d.getHours()*60+d.getMinutes();};
const previewNow=()=>clamp(nowMinutes()+state.previewMin,0,1439);
const selectedTask=()=>state.tasks.find(t=>t.id===state.selected)||state.tasks[0];
const hash=text=>{let v=2166136261;for(let i=0;i<text.length;i++){v^=text.charCodeAt(i);v=Math.imul(v,16777619);}return v>>>0;};

function logEvent(kind,label,meta=''){
  state.eventLog.push({id:`e:${Date.now()}:${Math.random().toString(36).slice(2,6)}`,at:new Date().toISOString(),kind,label,meta});
  state.eventLog=state.eventLog.slice(-500);
}
function loadState(){
  try{
    const direct=localStorage.getItem(STORAGE_KEY); if(direct)return normalizeState(JSON.parse(direct));
    for(const key of LEGACY_KEYS){const raw=localStorage.getItem(key);if(raw){const migrated=normalizeState(JSON.parse(raw));migrated.firstRun=false;return migrated;}}
  }catch{}
  return normalizeState(null);
}
function saveState(){
  try{
    const snapshot=deepCopy(state); snapshot.simulating=false;
    if(snapshot.activeSession?.running && snapshot.activeSession.lastStartMs){snapshot.activeSession.activeMs+=Date.now()-snapshot.activeSession.lastStartMs;snapshot.activeSession.running=false;snapshot.activeSession.lastStartMs=null;}
    localStorage.setItem(STORAGE_KEY,JSON.stringify(snapshot));
  }catch{toast('Local save failed — export if this persists.');}
}
function toast(message){const n=$('toast');n.textContent=message;n.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('show'),2400);}
function makeInteractive(node,label,handler){node.setAttribute('tabindex','0');node.setAttribute('role','button');node.setAttribute('aria-label',label);node.addEventListener('click',handler);node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();handler();}});}

function contour(group,baseY,amp,phase,opacity){let d=`M 0 ${baseY}`;for(let x=0;x<=1000;x+=25){const y=baseY-(Math.sin(x*.018+phase)*.6+Math.sin(x*.041+phase*1.7)*.35+1.1)*amp;d+=` L ${x} ${y.toFixed(1)}`;}group.append(svgEl('path',{d,fill:'none',stroke:'#8f8779','stroke-width':.65,opacity}));}
function drawUnderpainting(group){contour(group,155,54,.2,.23);contour(group,185,42,1.7,.17);contour(group,670,73,.9,.2);contour(group,720,54,2.3,.14);for(let i=0;i<40;i++){const x=48+((i*83)%900),y=210+((i*47)%390),h=18+(hash(`u${i}`)%68);group.append(svgEl('rect',{x,y:y-h,width:5+(i%4),height:h,fill:'none',stroke:'#aaa090','stroke-width':.45,opacity:.16}));}}
function drawArc(group,cx,cy,r,startMin,endMin,color,width,dash=''){const sa=-Math.PI/2+(startMin/1440)*Math.PI*2,ea=-Math.PI/2+(endMin/1440)*Math.PI*2,[x1,y1]=polar(cx,cy,r,sa),[x2,y2]=polar(cx,cy,r,ea),large=endMin-startMin>720?1:0;const p=svgEl('path',{d:`M ${x1.toFixed(2)} ${y1.toFixed(2)} A ${r} ${r} 0 ${large} 1 ${x2.toFixed(2)} ${y2.toFixed(2)}`,fill:'none',stroke:color,'stroke-width':width,'stroke-linecap':'butt'});if(dash)p.setAttribute('stroke-dasharray',dash);group.append(p);}
function taskPosition(task,at=previewNow()){const same=state.tasks.filter(c=>c.home===task.home);const li=same.findIndex(c=>c.id===task.id);const jitter=((hash(task.id)%1000)/1000-.5)*.17+(li-(same.length-1)/2)*.035;const angle=bearingAngle(task.home)+jitter;const radius=82+reach(state,task,at)*215;return polar(500,350,radius,angle);}

function drawWorld(){
  svg.replaceChildren(); taskPositions=new Map();
  svg.append(svgEl('rect',{x:0,y:0,width:1000,height:1120,fill:'#efe7d8'}));
  const under=svgEl('g',{'aria-hidden':'true'});drawUnderpainting(under);svg.append(under);
  svg.append(svgEl('text',{x:34,y:44,class:'svg-title'},"YOU'RE AWAKE // FORWARD FIELD"));
  svg.append(svgEl('text',{x:36,y:65,class:'svg-sub'},'BEARINGS · REACH · CONSTRAINT · MEASURED TERRAIN · RETURN'));
  const cx=500,cy=350;
  [82,142,202,262,306].forEach((r,i)=>svg.append(svgEl('circle',{cx,cy,r,class:i===4?'svg-rule':'svg-fine','stroke-dasharray':i===4?'':'2 5'})));
  bearings.forEach(b=>{
    const a=bearingAngle(b),[x2,y2]=polar(cx,cy,315,a);svg.append(svgEl('line',{x1:cx,y1:cy,x2,y2,class:state.context===b?'svg-red':'svg-fine'}));
    const [lx,ly]=polar(cx,cy,338,a),g=svgEl('g',{class:'svg-task'});g.append(svgEl('text',{x:lx,y:ly,class:'svg-label','text-anchor':'middle',fill:state.context===b?'#aa402b':'#171713'},bearingLabel[b][0]));g.append(svgEl('text',{x:lx,y:ly+13,class:'svg-micro','text-anchor':'middle'},bearingLabel[b][1]));makeInteractive(g,`Set context ${bearingLabel[b][0]}`,()=>{state.context=b;logEvent('context',bearingLabel[b][0]);saveState();render();});svg.append(g);
  });
  const solar=svgEl('g');svg.append(solar);
  for(let h=0;h<24;h++){const a=-Math.PI/2+(h/24)*Math.PI*2,[x1,y1]=polar(cx,cy,316,a),[x2,y2]=polar(cx,cy,h%6===0?328:323,a);solar.append(svgEl('line',{x1,y1,x2,y2,class:h%6===0?'svg-rule':'svg-fine'}));if(h%6===0){const[tX,tY]=polar(cx,cy,348,a);solar.append(svgEl('text',{x:tX,y:tY+3,class:'svg-micro','text-anchor':'middle'},String(h).padStart(2,'0')));}}
  state.hardAnchors.forEach(a=>drawArc(solar,cx,cy,322,hm(a.start),hm(a.end),a.kind==='work'?'#285982':'#aa402b',9));
  if(state.proposal)drawArc(solar,cx,cy,334,state.proposal.start,state.proposal.end,'#285982',5,'4 3');
  const liveAt=nowMinutes(),liveA=-Math.PI/2+(liveAt/1440)*Math.PI*2,[liveX,liveY]=polar(cx,cy,338,liveA);solar.append(svgEl('line',{x1:cx,y1:cy,x2:liveX,y2:liveY,class:'svg-red'}));
  if(state.previewMin>0){const a=-Math.PI/2+(previewNow()/1440)*Math.PI*2,[px,py]=polar(cx,cy,338,a);solar.append(svgEl('line',{x1:cx,y1:cy,x2:px,y2:py,class:'svg-blue','stroke-dasharray':'5 4'}));}
  const gap=gapInfo(state,previewNow());if(gap.mode==='free'&&gap.minutes>0)drawArc(solar,cx,cy,309,previewNow(),previewNow()+gap.minutes,'#285982',3,'2 2');
  svg.append(svgEl('circle',{cx,cy,r:54,fill:'#efe7d8',stroke:'#aa402b','stroke-width':1.2}));
  svg.append(svgEl('text',{x:cx,y:cy-7,class:'svg-label','text-anchor':'middle',fill:'#aa402b','font-size':19},'NOW'));
  svg.append(svgEl('text',{x:cx,y:cy+11,class:'svg-micro','text-anchor':'middle'},`${ft(previewNow())} · ${state.context.toUpperCase()}`));
  svg.append(svgEl('text',{x:cx,y:cy+27,class:'svg-micro','text-anchor':'middle'},gap.mode==='free'?`${gap.minutes}m FREE`:gap.mode==='occupied'?'OCCUPIED':'OPEN DAY'));

  state.tasks.filter(t=>t.status!=='done').forEach(task=>{
    const[x,y]=taskPosition(task);taskPositions.set(task.id,{x,y});const terrain=terrainFor(state,task),isSelected=task.id===state.selected,isParked=task.status==='parked';const height=22+task.value*5+Math.min(34,measuredDuration(state,task)*.6),width=13+Math.min(18,task.duration*.35),g=svgEl('g',{class:'svg-task',opacity:isParked?.28:1});
    if(terrain.n<2)g.append(svgEl('circle',{cx:x,cy:y-height*.45,r:30,fill:'#dce5e9',opacity:terrain.n===0?.32:.18}));
    if(isSelected)g.append(svgEl('line',{x1:cx,y1:cy,x2:x,y2:y,class:'svg-red','stroke-dasharray':'5 4'}));
    g.append(svgEl('path',{d:`M ${x-width/2} ${y} L ${x-width/2} ${y-height} L ${x-width*.18} ${y-height-9} L ${x+width*.18} ${y-height-9} L ${x+width/2} ${y-height} L ${x+width/2} ${y} Z`,fill:isSelected?'#efd8cb':'#efe7d8',stroke:isSelected?'#aa402b':'#171713','stroke-width':isSelected?2:.9,class:'task-outline'}));
    g.append(svgEl('line',{x1:x,y1:y-height-9,x2:x,y2:y-height-20,class:task.returned?'svg-red':'svg-fine'}));if(task.returned)g.append(svgEl('rect',{x:x-4,y:y-height-29,width:8,height:8,fill:'#aa402b'}));
    const active=state.activeSession?.taskId===task.id;if(active&&!state.activeSession.running){g.append(svgEl('path',{d:`M ${x+5} ${y-height-15} q 13 -9 25 -1`,class:'svg-red'}));g.append(svgEl('circle',{cx:x+31,cy:y-height-15,r:3,fill:'#aa402b'}));}
    if(state.depth!=='world'||isSelected){const anchor=Math.cos(bearingAngle(task.home))>0?'start':'end',dx=anchor==='start'?11:-11;g.append(svgEl('text',{x:x+dx,y:y-height/2,class:'svg-micro','text-anchor':anchor,fill:isSelected?'#aa402b':'#756d60'},task.title));if(state.depth==='task'||state.depth==='return')g.append(svgEl('text',{x:x+dx,y:y-height/2+12,class:'svg-micro','text-anchor':anchor},`${measuredDuration(state,task)}m · ${reachBand(state,task,previewNow())}`));}
    makeInteractive(g,`${task.title}, ${reachBand(state,task,previewNow())}`,()=>{state.selected=task.id;saveState();render();});svg.append(g);
  });
  drawTailRoute(); drawExecutionSpine(); drawDecoder(); updateViewBox();
}
function drawTailRoute(){const route=tailRoute(state,state.selected,previewNow(),2);if(!route.length)return;const start=taskPositions.get(state.selected);if(!start)return;let prev=start;for(const task of route){const pos=taskPositions.get(task.id);if(!pos)continue;svg.append(svgEl('path',{d:`M ${prev.x} ${prev.y} Q ${(prev.x+pos.x)/2} ${Math.min(prev.y,pos.y)-28} ${pos.x} ${pos.y}`,class:'svg-blue','stroke-dasharray':'5 5'}));prev=pos;}const last=route.at(-1),pos=taskPositions.get(last.id);if(pos)svg.append(svgEl('text',{x:pos.x+10,y:pos.y+18,class:'svg-micro',fill:'#285982'},'TAIL · PROPOSAL ONLY'));}
function drawExecutionSpine(){const top=rankedTasks(state,previewNow()).slice(0,5),startY=760;svg.append(svgEl('text',{x:228,y:716,class:'svg-sub'},'DAYLINE / EXECUTION TERRACES'));svg.append(svgEl('line',{x1:500,y1:695,x2:500,y2:1050,class:'svg-red'}));top.forEach((task,i)=>{const y=startY+i*58,sel=task.id===state.selected,g=svgEl('g',{class:'svg-task'});g.append(svgEl('path',{d:`M ${292-i*7} ${y-22} L ${708+i*7} ${y-22} L ${684+i*4} ${y+23} L ${316-i*4} ${y+23} Z`,fill:sel?'#efd8cb':'#efe7d8',stroke:sel?'#aa402b':'#9f9586','stroke-width':sel?1.5:.8,class:'task-outline'}));g.append(svgEl('circle',{cx:500,cy:y,r:4.5,fill:sel?'#aa402b':'#efe7d8',stroke:'#aa402b','stroke-width':1}));g.append(svgEl('text',{x:330,y:y-3,class:'svg-micro',fill:sel?'#aa402b':'#756d60'},String(i+1).padStart(2,'0')));g.append(svgEl('text',{x:366,y:y-3,class:'svg-label',fill:sel?'#aa402b':'#171713'},task.title));g.append(svgEl('text',{x:366,y:y+12,class:'svg-micro'},`${task.home.toUpperCase()} · ${measuredDuration(state,task)}m · ${reachBand(state,task,previewNow())}`));makeInteractive(g,`Execution ${i+1}: ${task.title}`,()=>{state.selected=task.id;saveState();render();});svg.append(g);});}
function drawDecoder(){const g=svgEl('g',{transform:'translate(36 1000)'});g.append(svgEl('text',{x:0,y:0,class:'svg-sub'},'VISUAL DECODER'));[['#aa402b','fact / commitment / return'],['#285982','forecast / proposal / derived'],['#171713','task / stable identity'],['#dce5e9','uncertainty / unmeasured terrain']].forEach(([c,l],i)=>{g.append(svgEl('line',{x1:0,y1:18+i*17,x2:28,y2:18+i*17,stroke:c,'stroke-width':i===3?7:2,opacity:i===3?.7:1}));g.append(svgEl('text',{x:38,y:21+i*17,class:'svg-micro'},l));});svg.append(g);}
function effectiveProjection(){return state.projection!=='auto'?state.projection:(matchMedia('(max-width:760px)').matches?'aperture':'atlas');}
function updateViewBox(){const projection=effectiveProjection();frame.dataset.projection=projection;if(projection==='atlas'){svg.setAttribute('viewBox','0 0 1000 1120');return;}const p=taskPositions.get(state.selected)||{x:500,y:350},depths={world:{width:700,height:720,yBias:20},district:{width:560,height:620,yBias:15},task:{width:410,height:500,yBias:-10},return:{width:500,height:560,yBias:160}},lens=depths[state.depth]||depths.world,focusY=state.depth==='return'?820:p.y+lens.yBias,x=clamp(p.x-lens.width/2,0,1000-lens.width),y=clamp(focusY-lens.height/2,0,1120-lens.height);svg.setAttribute('viewBox',`${x.toFixed(1)} ${y.toFixed(1)} ${lens.width} ${lens.height}`);$('edgeDepth').textContent=state.depth.toUpperCase();$('edgeBearing').textContent=selectedTask().home.toUpperCase();}

function renderCenterMass(){const task=selectedTask(),rank=rankedTasks(state,previewNow()),index=rank.findIndex(t=>t.id===task.id),gap=gapInfo(state,previewNow()),duration=measuredDuration(state,task),terrain=terrainFor(state,task),active=state.activeSession?.taskId===task.id,fit=explainFit(state,task,previewNow()),tail=tailRoute(state,task.id,previewNow(),2);$('selectedIndex').textContent=String(Math.max(0,index)+1).padStart(2,'0');$('selectedBearing').textContent=task.home.toUpperCase();$('selectedState').textContent=`${task.status.toUpperCase()} · ${task.returned?'RETURNED':'TASK · NOT EVIDENCE'}`;$('selectedTitle').textContent=task.title;$('selectedWhy').textContent=task.long;$('selectedMeta').textContent=`${task.earliest}–${task.latest} · ${duration}m measured-plan · ${reachBand(state,task,previewNow())} · terrain ×${Number(terrain.factor||1).toFixed(2)} n${terrain.n||0}`;$('whyNow').textContent=fit.reasons.join(' · ')||'no positive fit signal';$('frictionNow').textContent=fit.friction.join(' · ')||'low friction';$('tailRoute').textContent=tail.length?`TAIL // ${tail.map(t=>`${t.title} ${measuredDuration(state,t)}m`).join(' → ')} · uncommitted`:'TAIL // no same-context route inside the current horizon';$('startBtn').textContent=active?(state.activeSession.running?'RUNNING':'RESUME'):'START';$('startBtn').classList.toggle('active',Boolean(active));$('parkBtn').textContent=task.status==='parked'?'UNPARK':'PARK';$('placeBtn').textContent=state.proposal?.taskId===task.id?'COMMIT':'PLACE';}
function renderTime(){ $('clockReadout').textContent=ft(nowMinutes());const gap=gapInfo(state,previewNow());$('previewRange').value=String(state.previewMin);$('previewReadout').textContent=state.previewMin?`LOOKAHEAD +${state.previewMin}m · ${ft(previewNow())}`:'LIVE STATE';$('horizonReadout').textContent=gap.mode==='occupied'?`${gap.minutes}m INSIDE ${gap.anchor.title}`:gap.minutes!==null?`${gap.minutes}m → ${gap.anchor.title}`:'OPEN DAY';$('simulateBtn').textContent=state.simulating?'STOP':'SIMULATE';$('simulateBtn').classList.toggle('active',state.simulating);}
function renderContextButtons(){const root=$('contextButtons');root.replaceChildren();bearings.forEach(b=>{const btn=document.createElement('button');btn.type='button';btn.textContent=bearingLabel[b][0];btn.setAttribute('aria-pressed',String(state.context===b));btn.addEventListener('click',()=>{state.context=b;logEvent('context',bearingLabel[b][0]);saveState();render();});root.append(btn);});}
function renderForms(){const t=selectedTask();$('taskTitle').value=t.title;$('taskDuration').value=String(t.duration);$('taskBearing').value=t.home;$('taskEarliest').value=t.earliest;$('taskLatest').value=t.latest;$('taskDoneWhen').value=t.doneWhen;$('taskReturnTarget').value=t.returnTarget;$('sessionCue').value=state.activeSession?.taskId===t.id?state.activeSession.cue||'':'';$('returnResidue').value=t.returnResidue||'';$('captureBearing').value=state.context;}
function renderTerrain(){const root=$('terrainTable');root.replaceChildren();bearings.forEach(b=>{const row=document.createElement('div');row.className='terrain-row';const t=state.terrain[b]||{factor:1,n:0};row.innerHTML=`<span>${b.toUpperCase()}</span><span>×${Number(t.factor||1).toFixed(2)}</span><span>n${t.n||0}</span>`;root.append(row);});}
function renderRoom(){const t=selectedTask(),same=rankedTasks(state,previewNow()).filter(c=>c.home===t.home&&c.id!==t.id).slice(0,2),gap=gapInfo(state,previewNow()),faces=[['-X','INPUT',`context ${t.home}; criterion ${t.doneWhen||'missing'}`],['+X','OUTPUT',t.returnTarget||'missing return'],['-Y','CONTEXT',state.context.toUpperCase()],['+Y','COMPOSE',same.length?same.map(x=>x.title).join(' / '):'no same-bearing neighbor'],['-Z','OPEN',t.earliest],['+Z','CLOSE',gap.minutes===null?t.latest:`${t.latest}; horizon ${gap.minutes}m`]];const root=$('roomDiagram');root.replaceChildren();faces.forEach(([axis,name,value])=>{const f=document.createElement('button');f.type='button';f.className='room-face';f.innerHTML=`<strong>${axis} ${name}</strong><span>${value}</span>`;f.addEventListener('click',()=>toast(`${axis} ${name}: ${value}`));root.append(f);});}
function renderReturnTags(){const t=selectedTask(),opts=['moved forward','kept promise','learned','reduced friction','measured reality','worth remembering'],root=$('returnTags');root.replaceChildren();opts.forEach(label=>{const b=document.createElement('button');b.type='button';b.className='return-tag';const on=t.returnTags.includes(label);b.setAttribute('aria-pressed',String(on));b.textContent=label;b.addEventListener('click',()=>{const set=new Set(t.returnTags);set.has(label)?set.delete(label):set.add(label);t.returnTags=[...set];saveState();renderReturnTags();});root.append(b);});}
function renderSession(){const task=selectedTask(),s=state.activeSession;if(!s){$('sessionReadout').textContent='No active trace. START measures terrain; PAUSE preserves a re-entry thread.';$('pauseBtn').disabled=true;$('finishBtn').disabled=true;return;}const activeMs=s.activeMs+(s.running&&s.lastStartMs?Date.now()-s.lastStartMs:0),minutes=Math.max(0,activeMs/60000),title=state.tasks.find(x=>x.id===s.taskId)?.title||s.taskId;$('sessionReadout').textContent=`${s.running?'RUNNING':'PAUSED'} · ${title} · ${minutes.toFixed(1)} active min${s.cue?` · thread: ${s.cue}`:''}`;$('pauseBtn').disabled=!s.running;$('finishBtn').disabled=false;if(s.taskId!==task.id)$('sessionCue').value='';}
function renderProjectionControls(){document.querySelectorAll('[data-projection]').forEach(b=>b.classList.toggle('active',b.dataset.projection===state.projection));document.querySelectorAll('[data-depth]').forEach(b=>b.classList.toggle('active',b.dataset.depth===state.depth));}
function renderLedger(){const root=$('eventLedger');root.replaceChildren();const events=state.eventLog.slice(-8).reverse();if(!events.length){root.textContent='No receipts yet.';return;}events.forEach(e=>{const d=document.createElement('div');d.className='event-item';d.innerHTML=`<strong>${e.kind.toUpperCase()} · ${e.label}</strong><span>${new Date(e.at).toLocaleString()}${e.meta?` · ${e.meta}`:''}</span>`;root.append(d);});}
function render(){renderCenterMass();renderTime();renderContextButtons();renderForms();renderTerrain();renderRoom();renderReturnTags();renderSession();renderProjectionControls();renderLedger();drawWorld();saveState();}

function selectAdjacent(dir){const ranked=rankedTasks(state,previewNow()),i=ranked.findIndex(t=>t.id===state.selected);if(!ranked.length)return;state.selected=ranked[(Math.max(0,i)+dir+ranked.length)%ranked.length].id;saveState();render();}
function changeDepth(delta){const depths=['world','district','task','return'];let i=depths.indexOf(state.depth);i=clamp(i+delta,0,depths.length-1);if(depths[i]!==state.depth){state.depth=depths[i];saveState();render();}}
function startOrResume(){const task=selectedTask(),existing=state.activeSession;if(existing&&existing.taskId!==task.id){toast('Pause or finish the existing trace first.');return;}if(!existing){state.activeSession={taskId:task.id,running:true,lastStartMs:Date.now(),activeMs:0,cue:''};logEvent('start',task.title);}else if(!existing.running){existing.running=true;existing.lastStartMs=Date.now();logEvent('resume',task.title,existing.cue||'');}saveState();render();startSessionTicker();}
function pauseSession(){const s=state.activeSession;if(!s||!s.running)return;s.activeMs+=Date.now()-s.lastStartMs;s.lastStartMs=null;s.running=false;s.cue=$('sessionCue').value.trim().slice(0,100);logEvent('pause',state.tasks.find(t=>t.id===s.taskId)?.title||s.taskId,s.cue);saveState();render();toast('Paused. Re-entry thread retained.');}
function finishSession(){const s=state.activeSession;if(!s)return;if(s.running&&s.lastStartMs)s.activeMs+=Date.now()-s.lastStartMs;const minutes=s.activeMs/60000,task=state.tasks.find(t=>t.id===s.taskId);if(!task)return;state.sessions.push({taskId:task.id,activeMin:Number(minutes.toFixed(2)),finishedAt:new Date().toISOString(),cue:s.cue||''});state.sessions=state.sessions.slice(-300);if(minutes>=1){const terrain=state.terrain[task.home]||{factor:1,n:0,totalMin:0},observed=clamp(minutes/Math.max(1,task.duration),.65,1.8),nextN=(terrain.n||0)+1;terrain.factor=clamp(((terrain.factor||1)*(terrain.n||0)+observed)/nextN,.65,1.8);terrain.n=nextN;terrain.totalMin=(terrain.totalMin||0)+minutes;state.terrain[task.home]=terrain;toast(`Measured ${minutes.toFixed(1)}m; ${task.home.toUpperCase()} terrain ×${terrain.factor.toFixed(2)} n${terrain.n}.`);}else toast('Trace logged under one minute; not used to calibrate terrain.');logEvent('finish',task.title,`${minutes.toFixed(1)}m`);state.activeSession=null;saveState();render();}
function startSessionTicker(){clearInterval(sessionTimer);sessionTimer=setInterval(()=>{if(!state.activeSession?.running){clearInterval(sessionTimer);return;}renderSession();},1000);}
function togglePark(){const t=selectedTask();t.status=t.status==='parked'?'open':'parked';logEvent(t.status==='parked'?'park':'unpark',t.title);saveState();render();}
function markDone(){const t=selectedTask();if(state.activeSession?.taskId===t.id)finishSession();t.status='done';logEvent('done',t.title);const next=rankedTasks(state,previewNow())[0];if(next)state.selected=next.id;saveState();render();toast(`Done: ${t.title}. Return remains explicit.`);}
function openReturn(){state.depth='return';$('instrumentDrawer').open=true;setTimeout(()=>{$('returnInstrument').scrollIntoView({behavior:'smooth',block:'center'});$('returnResidue').focus();},30);$('returnMsg').textContent=`Target: ${selectedTask().returnTarget||'declare a durable residue'}`;render();}
function commitReturn(){const t=selectedTask(),residue=$('returnResidue').value.trim();if(!residue){$('returnMsg').textContent='Write one concrete residue before stamping the return.';return;}t.returnResidue=residue.slice(0,220);t.returned=true;logEvent('return',t.title,t.returnResidue);$('returnMsg').textContent='Returned. The red seal belongs to this stable task identity.';saveState();render();}
function placeOrCommit(){const t=selectedTask();if(state.proposal?.taskId===t.id){const p=state.proposal,overlap=state.hardAnchors.some(a=>p.start<hm(a.end)&&p.end>hm(a.start));if(overlap){toast('Proposal overlaps a commitment. Move the horizon or task.');return;}state.hardAnchors.push({id:`work:${Date.now()}`,title:t.title,start:ft(p.start),end:ft(p.end),bearing:t.home,kind:'work'});state.proposal=null;logEvent('commit',t.title,`${ft(p.start)}–${ft(p.end)}`);saveState();render();toast('Committed as a blue work block.');return;}const start=previewNow(),duration=measuredDuration(state,t),end=Math.min(1439,start+duration);state.proposal={taskId:t.id,start,end};logEvent('proposal',t.title,`${ft(start)}–${ft(end)}`);saveState();render();toast(`Proposal only: ${ft(start)}–${ft(end)}. Press COMMIT to schedule.`);}
function submitAnchor(e){e.preventDefault();const title=$('anchorTitle').value.trim(),start=$('anchorStart').value,end=$('anchorEnd').value,bearing=$('anchorBearing').value;if(!title){$('anchorMsg').textContent='Title is required.';return;}if(!start||!end||hm(end)<=hm(start)){$('anchorMsg').textContent='End must be later than start.';return;}state.hardAnchors.push({id:`fact:${Date.now()}`,title:title.slice(0,40),start,end,bearing,kind:'fact'});logEvent('anchor',title,`${start}–${end}`);$('anchorForm').reset();$('anchorBearing').value=state.context;$('anchorMsg').textContent='Hard fact added to the solar ring.';saveState();render();}
function submitTask(e){e.preventDefault();const t=selectedTask(),title=$('taskTitle').value.trim(),duration=Number($('taskDuration').value),earliest=$('taskEarliest').value,latest=$('taskLatest').value;if(!title||!Number.isFinite(duration)||duration<1||!earliest||!latest||hm(latest)<=hm(earliest)){toast('Task needs a title, duration, and valid window.');return;}t.title=title.slice(0,60);t.duration=clamp(duration,1,360);t.home=bearings.includes($('taskBearing').value)?$('taskBearing').value:t.home;t.earliest=earliest;t.latest=latest;t.doneWhen=$('taskDoneWhen').value.trim().slice(0,100);t.returnTarget=$('taskReturnTarget').value.trim().slice(0,100);logEvent('edit',t.title);saveState();render();toast('Task updated without changing its stable ID.');}
function submitCapture(e){e.preventDefault();const title=$('captureTitle').value.trim(),duration=Number($('captureDuration').value),home=$('captureBearing').value;if(!title||!Number.isFinite(duration)||duration<1){$('captureMsg').textContent='Give the path a title and positive duration.';return;}const now=nowMinutes(),task=normalizeTask({id:`t:user:${Date.now()}`,title,long:title,home,duration,value:3,earliest:ft(Math.max(0,now-30)),latest:'23:30',status:'open',anchor:'Learn',doneWhen:'',returnTarget:'',returned:false,returnResidue:'',returnTags:[],manualBias:0});state.tasks.push(task);state.selected=task.id;state.context=home;logEvent('capture',task.title,`${duration}m · ${home}`);$('captureForm').reset();$('captureDuration').value='20';$('captureBearing').value=state.context;$('captureMsg').textContent='Added to the field.';saveState();render();toast('Path added.');}
function openCapture(){$('instrumentDrawer').open=true;setTimeout(()=>{$('captureTitle').focus();$('captureTitle').select();},30);}
function openRoom(){state.depth='task';$('instrumentDrawer').open=true;setTimeout(()=>$('roomInstrument').scrollIntoView({behavior:'smooth',block:'center'}),30);render();}
function exportState(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='forward-field-state.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importState(file){if(!file)return;const r=new FileReader();r.addEventListener('load',()=>{try{state=normalizeState(JSON.parse(String(r.result||'')));logEvent('import','state');saveState();render();toast('Imported state. Stable IDs preserved where present.');}catch{toast('Import failed: invalid JSON state.');}});r.readAsText(file);}
function resetState(){if(!confirm('Reset Forward Field local state? Export first if needed.'))return;state=normalizeState(null);localStorage.removeItem(STORAGE_KEY);render();toast('Reset to seed terrain.');}
function simulate(){state.simulating=!state.simulating;clearInterval(simulationTimer);if(!state.simulating){render();return;}simulationTimer=setInterval(()=>{state.previewMin+=15;if(state.previewMin>240){state.previewMin=0;state.simulating=false;clearInterval(simulationTimer);}render();},650);render();}
function shareSelected(){const t=selectedTask(),text=`${t.title}\n${t.long}\n${measuredDuration(state,t)}m · ${t.home.toUpperCase()} · ${reachBand(state,t,previewNow())}${t.returned?`\nRETURN: ${t.returnResidue}`:''}`;if(navigator.share)navigator.share({title:'Forward Field',text}).catch(()=>{});else{navigator.clipboard?.writeText(text).then(()=>toast('Task copied.')).catch(()=>toast('Share not available.'));}}
function populateSelects(){['anchorBearing','taskBearing','captureBearing'].forEach(id=>{const select=$(id);select.replaceChildren();bearings.forEach(b=>{const o=document.createElement('option');o.value=b;o.textContent=bearingLabel[b][0];select.append(o);});});$('anchorBearing').value=state.context;$('captureBearing').value=state.context;}
function handleShareTarget(){const q=new URLSearchParams(location.search),flag=q.has('share')||q.has('title')||q.has('text')||q.has('url');if(!flag)return;const title=(q.get('title')||q.get('text')||q.get('url')||'SHARED PATH').trim(),long=[q.get('text'),q.get('url')].filter(Boolean).join(' · ').slice(0,180),task=normalizeTask({id:`t:share:${Date.now()}`,title:title.slice(0,60),long:long||title,home:state.context,duration:10,value:3,earliest:ft(Math.max(0,nowMinutes()-30)),latest:'23:30',status:'open',anchor:'Explore',doneWhen:'',returnTarget:'',returned:false,returnResidue:'',returnTags:[],manualBias:0});state.tasks.push(task);state.selected=task.id;logEvent('share-capture',task.title);saveState();history.replaceState(null,'',location.pathname);toast('Shared item captured into the field.');}

function wireEvents(){
  document.querySelectorAll('[data-projection]').forEach(b=>b.addEventListener('click',()=>{state.projection=b.dataset.projection;saveState();render();}));
  document.querySelectorAll('[data-depth]').forEach(b=>b.addEventListener('click',()=>{state.depth=b.dataset.depth;saveState();render();}));
  $('liveNowBtn').addEventListener('click',()=>{state.previewMin=0;state.simulating=false;clearInterval(simulationTimer);render();});$('minus30Btn').addEventListener('click',()=>{state.previewMin=clamp(state.previewMin-30,0,240);render();});$('plus30Btn').addEventListener('click',()=>{state.previewMin=clamp(state.previewMin+30,0,240);render();});$('previewRange').addEventListener('input',e=>{state.previewMin=clamp(Number(e.target.value)||0,0,240);render();});$('simulateBtn').addEventListener('click',simulate);
  $('prevTaskBtn').addEventListener('click',()=>selectAdjacent(-1));$('nextTaskBtn').addEventListener('click',()=>selectAdjacent(1));$('captureBtn').addEventListener('click',openCapture);$('roomBtn').addEventListener('click',openRoom);
  $('startBtn').addEventListener('click',startOrResume);$('pauseBtn').addEventListener('click',pauseSession);$('finishBtn').addEventListener('click',finishSession);$('parkBtn').addEventListener('click',togglePark);$('doneBtn').addEventListener('click',markDone);$('placeBtn').addEventListener('click',placeOrCommit);$('returnBtn').addEventListener('click',openReturn);$('commitReturnBtn').addEventListener('click',commitReturn);
  $('anchorForm').addEventListener('submit',submitAnchor);$('taskForm').addEventListener('submit',submitTask);$('captureForm').addEventListener('submit',submitCapture);$('sessionCue').addEventListener('input',()=>{if(state.activeSession?.taskId===selectedTask().id){state.activeSession.cue=$('sessionCue').value.trim().slice(0,100);saveState();}});$('returnResidue').addEventListener('input',()=>{selectedTask().returnResidue=$('returnResidue').value.slice(0,220);});$('shareBtn').addEventListener('click',shareSelected);$('exportBtn').addEventListener('click',exportState);$('importInput').addEventListener('change',e=>importState(e.target.files?.[0]));$('resetBtn').addEventListener('click',resetState);window.addEventListener('resize',updateViewBox);
  let swipeStart=null;$('worldCrop').addEventListener('pointerdown',e=>{swipeStart={x:e.clientX,y:e.clientY};});$('worldCrop').addEventListener('pointerup',e=>{if(!swipeStart||effectiveProjection()!=='aperture'){swipeStart=null;return;}const dx=e.clientX-swipeStart.x,dy=e.clientY-swipeStart.y;swipeStart=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.25)selectAdjacent(dx<0?1:-1);else if(Math.abs(dy)>65&&Math.abs(dy)>Math.abs(dx)*1.2)changeDepth(dy<0?1:-1);});
  document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key.toLowerCase()==='j')selectAdjacent(1);if(e.key.toLowerCase()==='k')selectAdjacent(-1);if(e.key==='Enter')startOrResume();if(e.key.toLowerCase()==='p')togglePark();if(e.key.toLowerCase()==='r')openReturn();if(e.key.toLowerCase()==='c')openCapture();});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn').hidden=false;});$('installBtn').addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('installBtn').hidden=true;});
}

function registerServiceWorker(){if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{}));}

populateSelects();wireEvents();handleShareTarget();render();startSessionTicker();registerServiceWorker();
setInterval(()=>{$('clockReadout').textContent=ft(nowMinutes());if(!state.previewMin&&!state.simulating){renderTime();drawWorld();}},30000);
