// Exercise real bundled handlers with a DOM/device stub; not a visual browser test.
import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.style={};this.attributes={};this.value='';this.hidden=false;this.disabled=false;this.open=false;this.textContent='';this.className='';this.clientWidth=300;this.offsetLeft=0;this.offsetWidth=48;}setAttribute(k,v){this.attributes[k]=String(v);}getAttribute(k){return this.attributes[k];}append(...x){this.children.push(...x);}replaceChildren(...x){this.children=x;}addEventListener(k,fn){(this.listeners??={})[k]=fn;}click(){return this.onclick?.({target:this});}focus(){}showModal(){this.open=true;}close(){this.open=false;}getBoundingClientRect(){return{left:0,top:0,width:390,height:540,right:390,bottom:540};}}
async function boot(){const html=fs.readFileSync(new URL('../public/painting.html',import.meta.url),'utf8'),els=Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element()]));const timers=new Map();let serial=0,voices=[],utterances=[],savedBlob;
const speech={getVoices:()=>voices,cancel(){},addEventListener(){},speak:u=>utterances.push(u)};const sandbox={console,Intl,Math,Number,String,Array,JSON,Map,Set,Error,Promise,Blob,structuredClone,crypto:{randomUUID:()=>`id-${++serial}`},window:{speechSynthesis:speech},speechSynthesis:speech,SpeechSynthesisUtterance:class{constructor(text){this.text=text;}},Image:class{constructor(){this.width=3056;this.height=1968;}set src(v){Promise.resolve().then(()=>this.onload());}},ResizeObserver:class{observe(){}},location:{protocol:'file:'},document:{getElementById:id=>els[id],createElement:t=>new Element(t),createElementNS:(_,t)=>new Element(t),addEventListener(){}},URL:{createObjectURL:b=>{savedBlob=b;return'blob:example';},revokeObjectURL(){}},setTimeout:fn=>{timers.set(++serial,fn);return serial;},clearTimeout:id=>timers.delete(id)};const c=vm.createContext(sandbox);for(const m of html.matchAll(/<script[^>]*>(.*?)<\/script>/gs))vm.runInContext(m[1],c);for(let i=0;i<10;i++)await Promise.resolve();return{els,run:s=>vm.runInContext(s,c),setVoices:v=>voices=v,utterances,timers,blob:()=>savedBlob};}
test('first action, projection change and return use real handlers without losing selection',async()=>{const b=await boot();assert.equal(b.run('ready'),true);assert.equal(b.els.pins.children.length,4);b.els.read.click();assert.equal(b.els.reader.hidden,false);assert.equal(b.els.word.textContent,'先看');b.els.next.click();assert.equal(b.els.word.textContent,'台阶前的两只孔雀。');b.els.listMode.click();assert.equal(b.run('state.selected'),'birds');assert.equal(b.els.plain.hidden,false);b.els.plain.children[2].click();assert.equal(b.run('state.selected'),'window');assert.equal(b.els.word.textContent,'窗框');b.run("act('return',{note:'The gesture crosses the window frame.'})");assert.equal(b.run('state.returns.length'),1);b.run('showReturns()');assert.equal(b.els.sheet.open,true);});
test('late speech completion cannot advance after stop; current speech follows units',async()=>{const b=await boot();b.setVoices([{localService:true,lang:'zh-CN',name:'Local test'}]);b.els.read.click();b.els.speak.click();assert.equal(b.utterances.length,1);const u=b.utterances[0];u.onstart();b.els.speak.click();u.onend();assert.equal(b.utterances.length,1);assert.equal(b.run('readIndex'),0);b.els.speak.click();b.utterances[1].onstart();b.utterances[1].onend();assert.equal(b.utterances.length,3);b.utterances[2].onstart();assert.equal(b.run('readIndex'),1);});
test('long reading material keeps the aperture bounded and route remains manual',async()=>{const b=await boot();b.run("state.regions[0].text=Array(2000).fill('one').join('|')");b.els.read.click();assert.equal(b.run('readUnits.length'),2000);assert.ok(b.els.textStrip.children.length<=27);b.run('showUnit(1200)');assert.ok(b.els.textStrip.children.length<=27);b.els.addRoute.click();b.els.routeGo.click();assert.equal(b.run('state.route.index'),0);assert.equal(b.run('state.route.running'),true);b.run('openReader();showUnit(readUnits.length-1);flowing=true;tick()');assert.equal(b.run('state.route.running'),true);assert.equal(b.run('state.route.index'),0);});
test('export restores current state and a rejected import leaves work untouched',async()=>{const b=await boot();b.run("act('return',{note:'Preserve this finding'})");b.run('exportPack()');const pack=JSON.parse(await b.blob().text());assert.equal(pack.state.returns[0].note,'Preserve this finding');assert.ok(pack.assets['spring-dawn'].startsWith('data:image/jpeg'));await b.els.sessionInput.onchange({target:{files:[{size:20,text:async()=>'{"version":7}'}],value:'x'}});assert.equal(b.run('state.returns[0].note'),'Preserve this finding');assert.match(b.els.message.textContent,/not replaced/);});
