export const LAB_FIELD_IDS = [
  "switchyard",
  "proof",
  "window",
  "rsvp",
  "bounty",
  "commons",
  "jue",
  "grammar",
  "countertrace",
  "scroll",
  "scale",
  "kite",
] as const;

export type LabFieldId = (typeof LAB_FIELD_IDS)[number];

export type LabInstrument = {
  id: LabFieldId;
  index: string;
  title: string;
  law: string;
  verb: string;
  pressure: string;
  origin: string;
  route: string;
  state: "DEEP KERNEL" | "PLAYABLE STUDY";
};

const genericRoute = (id: LabFieldId) => `/lab/instrument?id=${id}`;

export const LAB_INSTRUMENTS: readonly LabInstrument[] = [
  { id: "switchyard", index: "01", title: "SWITCHYARD", law: "A route is good only while its destination can still receive it.", verb: "READ → ROUTE → RECOVER", pressure: "Two valid destinations, three unequal recovery clocks, one accumulating system.", origin: "Continuous network pressure; no borrowed map or transit skin.", route: genericRoute("switchyard"), state: "PLAYABLE STUDY" },
  { id: "proof", index: "02", title: "PROOF LOOM", law: "A result counts when the exact chain that produced it remains inspectable.", verb: "COMPOSE → RUN → PROVE", pressure: "Four operations, four positions, and a target generated by a recoverable witness.", origin: "Solution-as-artifact; no factory costume.", route: genericRoute("proof"), state: "PLAYABLE STUDY" },
  { id: "window", index: "03", title: "FOLDING WINDOW", law: "The image is the operator: four layers make one exact statement.", verb: "ROTATE → OVERLAY → MATCH", pressure: "Every layer alters the same nine-cell composite through exclusive overlap.", origin: "Compositional operation; no imitation of another work's panels.", route: genericRoute("window"), state: "PLAYABLE STUDY" },
  { id: "rsvp", index: "04", title: "RSVP // SURF", law: "Speed may compress attention; regression remains lawful.", verb: "READ → STEER → CAPTURE / REGRESS", pressure: "Untimed text becomes a five-lane course; a local track may project its pulse.", origin: "Player-owned audio as course data; not an Audiosurf clone.", route: "/lab/rsvp", state: "DEEP KERNEL" },
  { id: "bounty", index: "05", title: "BOUNTY PROOF", law: "A compact answer returns with the exact material that certifies it.", verb: "SELECT → TEST → CERTIFY", pressure: "Reach a seeded target with at most four weighted source fragments.", origin: "Short problem, durable proof; no points treadmill.", route: genericRoute("bounty"), state: "PLAYABLE STUDY" },
  { id: "commons", index: "06", title: "COMMONS", law: "A contribution must expose uncertainty, provenance, and the cost of checking.", verb: "WEIGH → VERIFY → COMMIT", pressure: "Three fallible witnesses, two exact probes, seven synthetic claims.", origin: "Calibration rehearsal only; it never calls the player's sentence scientific truth.", route: genericRoute("commons"), state: "PLAYABLE STUDY" },
  { id: "jue", index: "07", title: "JUE / JU", law: "A second meaning counts only when it predicts a second move.", verb: "READ → COMPOSE → SATISFY", pressure: "Three outcome conditions must be inferred through eight distinct glyph-laws.", origin: "Rule manipulation through a jointly evolved eight-position system.", route: "/lab/jue", state: "DEEP KERNEL" },
  { id: "grammar", index: "08", title: "TRANSFER GRAMMAR", law: "A grammar is learned only when it survives a new surface without its legend.", verb: "INFER → PROBE → TRANSFER", pressure: "Demonstrations reveal relations; checks report only total correspondence.", origin: "Rule transfer; no borrowed line-grid language.", route: genericRoute("grammar"), state: "PLAYABLE STUDY" },
  { id: "countertrace", index: "09", title: "COUNTERTRACE", law: "Changing an earlier event must recompute everything it could affect.", verb: "REWIND → INTERVENE → REPLAY", pressure: "Six coupled moments, four interventions, one demanded final state.", origin: "Causal rereading; no platforming or time-reversal costume.", route: genericRoute("countertrace"), state: "PLAYABLE STUDY" },
  { id: "scroll", index: "10", title: "SCROLL PATH", law: "A continuous world is a record of choices, not an endless decorative surface.", verb: "SURVEY → TRAVERSE → INSCRIBE", pressure: "Adjacent passage, finite breath, and three marks reward reading the whole field.", origin: "Procedural continuity and negative space; not copied ink scenery.", route: genericRoute("scroll"), state: "PLAYABLE STUDY" },
  { id: "scale", index: "11", title: "SCALE WALK", law: "To enter an image, its pixels must decide where passage is possible.", verb: "INSPECT → ENTER → RESCALE", pressure: "Brightness and edge density generate five compositional decisions from an image.", origin: "A local image is analyzed in-browser; the painting is data, not backdrop.", route: genericRoute("scale"), state: "PLAYABLE STUDY" },
  { id: "kite", index: "12", title: "GO FLY KITE", law: "The wind lifts; the player negotiates the line.", verb: "FORECAST → HOLD / RELEASE → CARRY", pressure: "A moving safe band and remembered residue make regulation consequential.", origin: "A Sleeper-native kite law; not a balloon reskin.", route: "/lab/kite", state: "DEEP KERNEL" },
] as const;

export function isLabFieldId(value: unknown): value is LabFieldId {
  return typeof value === "string" && (LAB_FIELD_IDS as readonly string[]).includes(value);
}

export function labInstrument(field: LabFieldId) {
  return LAB_INSTRUMENTS.find((instrument) => instrument.id === field) ?? LAB_INSTRUMENTS[0];
}

export function labRoute(field: LabFieldId) {
  return labInstrument(field).route;
}
