'use strict';
function elapsed(ms){const t=Math.max(0,Math.floor(ms/1000));return`${Math.floor(t/60)}:${String(t%60).padStart(2,'0')}`}
let game=null,raf=0,last=0,projection='city',logLines=[],activeTool=null,lastSaved=0;
function newGame(source,cellId,figureId){const layout=buildCity(source,cellId,figureId),now=performance.now();return{...layout,player:{...layout.start,direction:0},gateCount:0,returnOpen:false,keys:new Set(),path:[{...layout.start}],signature:[],lastPathPoint:{...layout.start},steps:0,startedAt:now,lastMovedAt:now,anchor:null,pulseUntil:0,flashUntil:0,kerisReadyAt:0,projection:'city',proofs:[],operatorCounts:{conch:0,keris:0,w8:0,spiral:0},measureMs:0,retrievalArmed:false,retrievalDeparted:false,finished:false,routeEvents:[],routeRuns:[],lastRouteDir:null,lastRouteRun:0,ghost:null}}
function addLog(s){logLines=[s,...logLines].slice(0,12);$('#log').innerHTML=logLines.map(x=>`<div>${escapeHtml(x)}</div>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function recordEvent(type,data={}){if(!game)return;game.routeEvents.push({step:game.steps,t:Math.round(performance.now()-game.startedAt),type,...data})}
function recordDirection(dx,dy){let dir=Math.abs(dx)>Math.abs(dy)?(dx>0?'R':'L'):(dy>0?'D':'U');game.signature.push(dir);if(game.lastRouteDir===dir)game.lastRouteRun++;else{if(game.lastRouteDir)game.routeRuns.push([game.lastRouteDir,game.lastRouteRun]);game.lastRouteDir=dir;game.lastRouteRun=1}}
function snapshotWitness(){if(!game)return null;const runs=[...game.routeRuns];if(game.lastRouteDir)runs.push([game.lastRouteDir,game.lastRouteRun]);return{schema:'sleeper-route-witness/v1',worldKey:game.law.key,worldRevision:'city-engine-v0.2-static-port-2026-10-03',figure:game.law.figure.id,origin:[game.start.x,game.start.y],route:runs,events:game.routeEvents.slice(),measures:{steps:game.steps,elapsedMs:Math.round(performance.now()-game.startedAt),pathPoints:game.path.length},path:game.path.map(p=>[+p.x.toFixed(3),+p.y.toFixed(3)])}}
function saveWitness(){const w=snapshotWitness();if(!w)return;try{localStorage.setItem(`sleeper:witness:${w.worldKey}`,JSON.stringify(w));localStorage.setItem('sleeper:last',JSON.stringify({source:game.law.source,cell:game.law.cell.id,figure:game.law.figure.id}))}catch{}}
function loadGhost(key){try{const x=JSON.parse(localStorage.getItem(`sleeper:witness:${key}`)||'null');return typeof SleeperEncounter!=='undefined'&&SleeperEncounter.validGhost(x,key)?x:null}catch{return null}}
function openGate(gate,method,note){if(!game||gate.collected||game.finished)return false;const now=performance.now();gate.collected=true;gate.progress=1;game.gateCount++;const proof={gate:gate.name,token:gate.token,method,step:game.steps,elapsedMs:Math.round(now-game.startedAt),note};game.proofs.push(proof);recordEvent('gate',{gate:gate.name,token:gate.token,method});game.returnOpen=game.gateCount===8;game.flashUntil=now+500;addLog(`${gate.name} / ${gate.token}: ${gate.line}`);renderHUD();if(game.returnOpen)addLog('EIGHT PROOFS HOLD. RETURN TO ORIGIN.');return true}
function evaluateToolGate(gate,tool,effect){const primary=PRIMARY[tool];if(gate.name===primary)return effect?{status:'open',note:NOTES[tool]}:{status:'none'};if(gate.name!=='TRANSFER'||tool!==game.law.transferTool)return{status:'none'};if(!game.proofs.some(p=>p.gate===primary))return{status:'blocked',line:`TRANSFER LOCKED: PROVE ${primary} FIRST.`};return{status:'open',note:`${tool.toUpperCase()} transferred into a second Gate law.`}}
function uiPaused(){return typeof document!=='undefined'&&(!$('#modal').classList.contains('hidden')||$('#side').classList.contains('show'))}
function useTool(tool){if(!game||game.finished||!TOOLS.includes(tool)||uiPaused())return;const now=performance.now();game.lastMovedAt=now;let effect=true;if(tool!=='keris')game.operatorCounts[tool]++;activeTool=tool;recordEvent('operator',{operator:tool});$$('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));setTimeout(()=>{$$('.tool').forEach(b=>b.classList.remove('active'));activeTool=null},220);
if(tool==='conch'){game.pulseUntil=now+game.law.figure.conchMs;addLog(`CONCH / source field visible for ${(game.law.figure.conchMs/1000).toFixed(1)}s.`)}
if(tool==='spiral'){projection=projection==='city'?'disc':'city';game.projection=projection;$('#projectionLabel').textContent=projection.toUpperCase();addLog(`SPIRAL / ${projection.toUpperCase()} PROJECTION. SAME STATE.`)}
if(tool==='w8'){
 if(!game.anchor){game.anchor={x:game.player.x,y:game.player.y,direction:game.player.direction};const retrieval=game.gates.find(g=>g.name==='RETRIEVAL'&&!g.collected);game.retrievalArmed=!!retrieval&&Math.hypot(game.player.x-retrieval.x,game.player.y-retrieval.y)<=1.45;game.retrievalDeparted=false;effect=false;addLog('W8 / COORDINATE HELD. LEAVE IT.');recordEvent('anchor',{x:+game.player.x.toFixed(3),y:+game.player.y.toFixed(3)})}
 else{effect=game.retrievalArmed&&game.retrievalDeparted;game.player={...game.anchor};game.anchor=null;game.retrievalArmed=false;game.retrievalDeparted=false;game.flashUntil=now+600;addLog('W8 / COORDINATE RECOVERED. MARK RELEASED.');recordEvent('recover',{x:+game.player.x.toFixed(3),y:+game.player.y.toFixed(3)})}
}
if(tool==='keris'){
 if(now<game.kerisReadyAt){addLog(`KERIS REFORMING / ${((game.kerisReadyAt-now)/1000).toFixed(1)}s`);return}
 const hit=castRay(game,game.player.direction,1.5);let cut=false;if(hit.distance<1.35&&hit.mapX>0&&hit.mapY>0&&hit.mapX<game.size-1&&hit.mapY<game.size-1&&game.grid[hit.mapY][hit.mapX]>0&&game.grid[hit.mapY][hit.mapX]!==9){game.grid[hit.mapY][hit.mapX]=0;cut=true;game.kerisReadyAt=now+game.law.figure.kerisCooldownMs;addLog(`KERIS / WALL ${hit.mapX},${hit.mapY} CUT.`);recordEvent('cut',{x:hit.mapX,y:hit.mapY})}else addLog('KERIS / NO CUTTABLE WALL IN REACH.');
 if(!cut)return;game.operatorCounts.keris++;
}
const ng=nearestGate(game,2.25);if(ng){const decision=evaluateToolGate(ng.gate,tool,effect);if(decision.status==='open')openGate(ng.gate,tool,decision.note);else if(decision.status==='blocked')addLog(decision.line)}
renderHUD()}
function updateProofs(now,dt){if(!game||game.finished)return;for(const gate of game.gates){if(gate.collected)continue;const d=Math.hypot(game.player.x-gate.x,game.player.y-gate.y);
 if(gate.name==='TRUTH'){const acting=game.keys.size>0||activeTool!==null;gate.progress=(d>1.18||acting)?0:clamp((now-game.lastMovedAt)/game.law.figure.truthHoldMs,0,1);if(gate.progress>=1)openGate(gate,'stillness','The figure held still while the field moved.')}
 else if(gate.name==='MEASURE'){const held=d>=game.law.figure.measureMin&&d<=game.law.figure.measureMax;game.measureMs=held?game.measureMs+dt:Math.max(0,game.measureMs-dt*.75);gate.progress=clamp(game.measureMs/game.law.figure.measureHoldMs,0,1);if(gate.progress>=1)openGate(gate,'distance','The required distance band was held as evidence.')}
 else if(gate.name==='RESILIENCE'&&d<.62){if(!gate.relocated){gate.x=gate.alternate.x;gate.y=gate.alternate.y;gate.relocated=true;gate.progress=.5;addLog(`RESILIENCE / ${gate.token} MOVED. RECOVER SAME TOKEN.`);recordEvent('relocate',{gate:'RESILIENCE',token:gate.token})}else openGate(gate,'relocation','The same token was recovered after its coordinate failed.')}
 }
 if(game.anchor&&game.retrievalArmed&&!game.retrievalDeparted&&Math.hypot(game.player.x-game.anchor.x,game.player.y-game.anchor.y)>=3.1){game.retrievalDeparted=true;addLog('W8 / ANCHOR NOW OUT OF RANGE. RECOVERY ARMED.')}
}
function move(now,dt){if(!game||game.finished)return;const k=game.keys,turn=((k.has('d')||k.has('arrowright'))?1:0)-((k.has('a')||k.has('arrowleft'))?1:0);if(turn){game.player.direction=normalAngle(game.player.direction+turn*dt*.0022);game.lastMovedAt=now}
const forward=((k.has('w')||k.has('arrowup'))?1:0)-((k.has('s')||k.has('arrowdown'))?1:0),strafe=(k.has('e')?1:0)-(k.has('q')?1:0);if(!forward&&!strafe)return;const speed=game.law.figure.movementSpeed*dt/1000,dx=(Math.cos(game.player.direction)*forward+Math.cos(game.player.direction+Math.PI/2)*strafe)*speed,dy=(Math.sin(game.player.direction)*forward+Math.sin(game.player.direction+Math.PI/2)*strafe)*speed;let moved=false,ox=game.player.x,oy=game.player.y;if(isOpen(game,game.player.x+dx,game.player.y)){game.player.x+=dx;moved=true}if(isOpen(game,game.player.x,game.player.y+dy)){game.player.y+=dy;moved=true}if(moved){game.lastMovedAt=now;const dist=Math.hypot(game.player.x-game.lastPathPoint.x,game.player.y-game.lastPathPoint.y);if(dist>.28){game.path.push({x:game.player.x,y:game.player.y});game.steps++;recordDirection(game.player.x-game.lastPathPoint.x,game.player.y-game.lastPathPoint.y);game.lastPathPoint={x:game.player.x,y:game.player.y}}
 if(game.returnOpen&&Math.hypot(game.player.x-game.start.x,game.player.y-game.start.y)<.7)finishReturn()
}}
function drawCity(ctx,w,h,now){ctx.fillStyle='rgba(5,7,7,.96)';ctx.fillRect(0,0,w,h);const cols=clamp(Math.floor(w/(w<720?6.7:8.2)),72,148),rows=clamp(Math.floor(h/(w<720?11.8:13.1)),38,76),cw=w/cols,ch=h/rows,fov=Math.PI/2.9,layers=Array.from({length:6},()=>Array.from({length:rows},()=>Array(cols).fill(' '))),collected=new Set(game.gates.filter(x=>x.collected).map(x=>x.name)),palette=collected.has('COMPRESSION')&&game.gateCount<6?REDUCED:DENSITY,moving=game.keys.has('w')||game.keys.has('s')||game.keys.has('arrowup')||game.keys.has('arrowdown'),bob=moving&&!globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches?Math.sin(now*.011)*ch*.16:0;
for(let c=0;c<cols;c++){const camera=c/cols-.5,ra=game.player.direction+camera*fov,hit=castRay(game,ra),cd=Math.max(.08,hit.distance*Math.cos(ra-game.player.direction)),wh=Math.min(rows*2.1,(rows*.88)/cd),top=Math.floor(rows/2-wh/2+bob/ch),bottom=Math.ceil(rows/2+wh/2+bob/ch),base=clamp(Math.floor(5.7-cd*.42-hit.side*.7),0,5);for(let r=0;r<rows;r++){let glyph=' ',shade=0;if(r>=top&&r<=bottom){const v=(r-top)/Math.max(1,bottom-top),grain=Math.sin((hit.texture*21+v*13+hit.mapX*1.7+hit.mapY)*2.3),bright=clamp(base+grain*.8-Math.abs(v-.5)*.8,0,5);shade=Math.floor(bright);const di=clamp(Math.floor((bright/5)*(palette.length-1)+Math.abs(grain)*2),1,palette.length-1),th=Math.abs((hit.mapX*31+hit.mapY*17+r*7+c)%29);if(th===0||(collected.has('PROVENANCE')&&th%11===0))glyph=game.sourceChars[(hit.mapX*5+hit.mapY*3+r)%game.sourceChars.length];else if(hit.cell===2&&th%7===0)glyph='│';else if(hit.cell===3&&th%9===0)glyph='─';else glyph=palette[di]}else if(r>bottom){const fd=(r-rows/2)/(rows/2);shade=clamp(Math.floor((1-fd)*3.2),0,3);const p=(r*11+c*7+Math.floor(now/340))%31;glyph=p===0?'/':p<4?'·':p===8?'_':' '}else{const sp=(r*37+c*13+game.gateCount*5)%233;if(sp===0){shade=2;glyph='·'}if(game.gateCount>0&&sp===19){const t=game.law.cellTokens[(c+r)%game.law.cellTokens.length];shade=2;glyph=Array.from(t)[(c+r)%Math.max(1,Array.from(t).length)]||'·'}}layers[shade][r][c]=glyph}}
const shades=['rgba(214,207,185,.10)','rgba(214,207,185,.23)','rgba(222,215,193,.38)','rgba(230,222,199,.56)','rgba(238,230,207,.76)','rgba(248,239,214,.96)'];ctx.textBaseline='top';ctx.font=`${ch*1.04}px "Courier New",monospace`;const sx=cw/Math.max(1,ctx.measureText('M').width);for(let s=0;s<layers.length;s++){ctx.fillStyle=shades[s];ctx.save();ctx.scale(sx,1);for(let r=0;r<rows;r++)ctx.fillText(layers[s][r].join(''),0,r*ch);ctx.restore()}drawGateSprites(ctx,w,h,game,now,fov);ctx.strokeStyle='rgba(238,217,167,.65)';ctx.beginPath();ctx.moveTo(w/2-7,h/2);ctx.lineTo(w/2+7,h/2);ctx.moveTo(w/2,h/2-7);ctx.lineTo(w/2,h/2+7);ctx.stroke();if(game.pulseUntil>now){const prog=1-(game.pulseUntil-now)/game.law.figure.conchMs;ctx.strokeStyle=`rgba(123,190,201,${.48*(1-prog)})`;for(let r=0;r<3;r++){ctx.beginPath();ctx.arc(w/2,h/2,((prog+r/3)%1)*Math.max(w,h),0,TAU);ctx.stroke()}}}
function drawGateSprites(ctx,w,h,g,now,fov){for(const gate of g.gates){if(gate.collected)continue;const dx=gate.x-g.player.x,dy=gate.y-g.player.y,d=Math.hypot(dx,dy),a=normalAngle(Math.atan2(dy,dx)-g.player.direction),through=g.pulseUntil>now;if(Math.abs(a)>fov*.65&&!through)continue;const visible=lineOfSight(g,gate.x,gate.y);if(!visible&&!through)continue;const x=w/2+(a/(fov/2))*(w/2);if(x<-50||x>w+50)continue;const size=clamp((h*.34)/Math.max(d,.45),14,h*.28),y=h/2+(globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches?0:Math.sin(now*.002+gate.x)*5);ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor=gate.color;ctx.shadowBlur=visible?22:6;ctx.fillStyle=gate.color;ctx.globalAlpha=visible?1:clamp(1-d/22,.18,.68);ctx.font=`${size}px "Courier New",monospace`;ctx.fillText(gate.glyph,x,y);if(d<3.2||through){ctx.shadowBlur=0;ctx.font=`${clamp(size*.17,8,12)}px "Courier New",monospace`;ctx.fillText(gate.name,x,y+size*.72);ctx.globalAlpha*=.72;ctx.font=`${clamp(size*.14,8,11)}px Georgia,serif`;ctx.fillText(gate.token,x,y+size*.94)}ctx.restore()}
if(g.returnOpen){const dx=g.start.x-g.player.x,dy=g.start.y-g.player.y,d=Math.hypot(dx,dy),a=normalAngle(Math.atan2(dy,dx)-g.player.direction);if(Math.abs(a)<fov*.65||g.pulseUntil>now){const x=w/2+(a/(fov/2))*(w/2),size=clamp((h*.44)/Math.max(d,.45),18,h*.34);ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor='#f0c66f';ctx.shadowBlur=30;ctx.fillStyle='#f3d78f';ctx.font=`${size}px serif`;ctx.fillText('回',x,h/2);ctx.restore()}}}
function drawDisc(ctx,w,h,now){ctx.fillStyle='rgba(7,8,8,.97)';ctx.fillRect(0,0,w,h);const cx=w/2,cy=h/2,scale=Math.min(w,h)/(game.size*1.52),center=(game.size-1)/2,twist=.095+(globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches?0:Math.sin(now*.00037)*.008),project=p=>{const dx=p.x-center,dy=p.y-center,r=Math.hypot(dx,dy),a=Math.atan2(dy,dx)+r*twist;return{x:cx+Math.cos(a)*r*scale,y:cy+Math.sin(a)*r*scale*.72}};ctx.strokeStyle='rgba(218,205,172,.13)';for(let ring=2;ring<game.size/2;ring+=2){ctx.beginPath();ctx.ellipse(cx,cy,ring*scale,ring*scale*.72,0,0,TAU);ctx.stroke()}
ctx.font=`${clamp(scale*.82,5,10)}px "Courier New",monospace`;ctx.textAlign='center';ctx.textBaseline='middle';for(let y=1;y<game.size-1;y++)for(let x=1;x<game.size-1;x++)if(game.grid[y][x]===0){const p=project({x:x+.5,y:y+.5}),si=Math.abs((x*17+y*31)%game.sourceChars.length);ctx.fillStyle='rgba(220,211,187,.34)';ctx.fillText((x+y)%11===0?game.sourceChars[si]:'·',p.x,p.y)}
if(game.ghost?.path?.length>1){ctx.beginPath();game.ghost.path.forEach((xy,i)=>{const p=project({x:xy[0],y:xy[1]});i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});ctx.strokeStyle='rgba(124,183,191,.20)';ctx.setLineDash([3,4]);ctx.stroke();ctx.setLineDash([])}
if(game.path.length>1){ctx.beginPath();game.path.forEach((p,i)=>{p=project(p);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});ctx.strokeStyle='rgba(224,143,84,.58)';ctx.lineWidth=1.2;ctx.stroke()}for(const gate of game.gates){const p=project(gate);ctx.fillStyle=gate.collected?'rgba(222,214,191,.22)':gate.color;ctx.shadowColor=gate.color;ctx.shadowBlur=gate.collected?0:10;ctx.font=`${gate.collected?11:17}px "Courier New",monospace`;ctx.fillText(gate.collected?'·':gate.glyph,p.x,p.y)}ctx.shadowBlur=0;const pp=project(game.player);ctx.fillStyle='#f1d487';ctx.beginPath();ctx.arc(pp.x,pp.y,4.5,0,TAU);ctx.fill();if(game.anchor){const a=project(game.anchor);ctx.strokeStyle='rgba(125,188,198,.85)';ctx.strokeRect(a.x-5,a.y-5,10,10)}ctx.textAlign='left';ctx.fillStyle='rgba(229,220,195,.7)';ctx.font='10px "Courier New",monospace';ctx.fillText('RECTILINEAR STATE / RADIAL PROJECTION',20,22);ctx.fillStyle='rgba(229,220,195,.38)';ctx.fillText('THE MAP HAS NOT MOVED. YOUR READING HAS.',20,39);if(game.ghost)ctx.fillText('GHOST: PREVIOUS SAME-WORLD ROUTE / EVIDENCE ONLY',20,56)}
function resizeCanvas(){const c=$('#view'),r=c.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2);const W=Math.max(1,Math.floor(r.width*ratio)),H=Math.max(1,Math.floor(r.height*ratio));if(c.width!==W||c.height!==H){c.width=W;c.height=H}return{ctx:c.getContext('2d'),w:r.width,h:r.height,ratio}}
function render(now){if(!game)return;const{ctx,w,h,ratio}=resizeCanvas();ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,h);projection==='city'?drawCity(ctx,w,h,now):drawDisc(ctx,w,h,now)}
function renderHUD(){if(!game)return;$('#worldKey').textContent=game.law.key;$('#gateCount').textContent=`${game.gateCount}/8`;$('#stepCount').textContent=game.steps;$('#returnBtn').disabled=!game.returnOpen;$('#returnBtn').textContent=game.returnOpen?'RETURN TO ORIGIN':'RETURN SEALED';const ng=nearestGate(game,5);if(ng){$('#nearGate').innerHTML=`<span class="gold">${ng.gate.glyph} ${ng.gate.name}</span><br><span class="tiny dim">${escapeHtml(ng.gate.token)} · ${ng.distance.toFixed(2)}u</span><br><span class="tiny">${escapeHtml(ng.gate.instruction)}</span>`;$('#gateProgress').style.width=`${Math.round(ng.gate.progress*100)}%`}else{$('#nearGate').textContent='NO GATE IN RANGE';$('#gateProgress').style.width='0%'}
$('#gates').innerHTML=game.gates.map(g=>`<div class="gate ${g.collected?'open':''} ${ng?.gate===g?'current':''}"><span>${g.collected?'✓':g.glyph}</span><span>${g.name}<span class="token dim"> / ${escapeHtml(g.token)}</span></span><span>${g.collected?'PROVED':g.method.toUpperCase()}</span></div>`).join('');$('#proofs').innerHTML=game.proofs.length?game.proofs.map((p,i)=>`${String(i+1).padStart(2,'0')} ${p.gate} · ${p.method.toUpperCase()}<br><span class="dim">${escapeHtml(p.note)}</span>`).join('<br>'):'NO PROOFS YET.'}
function frame(now){if(!last)last=now;const dt=Math.min(48,now-last);last=now;if(!uiPaused()){move(now,dt);updateProofs(now,dt);if(game?.returnOpen&&!game.finished&&Math.hypot(game.player.x-game.start.x,game.player.y-game.start.y)<.7)finishReturn()}render(now);if(game){$('#timeCount').textContent=elapsed(now-game.startedAt);if(now-game.lastHudAt>120){game.lastHudAt=now;renderHUD()}if(now-lastSaved>3000){lastSaved=now;saveWitness()}}raf=requestAnimationFrame(frame)}

