'use strict';
function dominantOperator(counts,seed){return [...TOOLS].sort((a,b)=>counts[b]-counts[a]||((hashString(`${seed}:${a}`)%97)-(hashString(`${seed}:${b}`)%97)))[0]}
function returnedSource(source,op,sig){const words=source.trim().split(/\s+/).filter(Boolean);if(!words.length)return'RETURNED';if(words.length===1)return`${words[0]} / RETURNED`;const pivot=hashString(`${sig}:${op}`)%words.length;if(op==='conch')return[...words.slice(pivot),words[pivot],...words.slice(0,pivot)].join(' ');if(op==='keris')return[...words.slice(0,pivot),'—',...words.slice(pivot)].join(' ');if(op==='w8')return[...words.slice(pivot),...words.slice(0,pivot)].join(' ');return[...words].reverse().join(' ')}
function makeArtifact(){const pathSignature=game.signature.slice(-36).join('')||'•',dominant=dominantOperator(game.operatorCounts,game.law.seed),witness=(game.proofs.map(p=>p.token).join(' · ')||game.law.cellTokens.join(' · ')),instructions={conch:'Listen for a signal and name its source before answering.',keris:'Make the smallest cut that changes the next possible action.',w8:'Name the constraint that must survive the next change.',spiral:'Change the representation; verify that the underlying thing survives.'};return{schema:'sleeper.one-return',version:2,worldKey:game.law.key,source:game.law.source,returnedSource:returnedSource(game.law.source,dominant,pathSignature),cell:{id:game.law.cell.id,source:game.law.cell.text,provenance:game.law.cell.provenance,witness},figure:game.law.figure.id,dominantOperator:dominant,transferInstruction:instructions[dominant],pathSignature,operatorCounts:{...game.operatorCounts},proofs:game.proofs.map(x=>({...x})),measures:{steps:game.steps,elapsedMs:Math.round(performance.now()-game.startedAt)}}}
const engineSnapshotWitness=snapshotWitness;
function traceSidecar(raw=engineSnapshotWitness()){if(!raw)return null;return{...raw,schema:'sleeper.native-route-trace/v0.1',authority:'EVIDENCE_ONLY',law:'CONTINUOUS ROUTE TRACE != CANONICAL GATE PROOF. This native float-path sidecar records one traversal only; it does not replace sleeper.route-witness/v0.1 or satisfy ONE RETURN v2 Gates.'}}
snapshotWitness=function(){return traceSidecar(engineSnapshotWitness())};
function finishReturn(){if(!game||game.finished||game.gateCount<8)return;game.finished=true;recordEvent('return',{x:+game.player.x.toFixed(3),y:+game.player.y.toFixed(3)});const artifact=makeArtifact(),trace=snapshotWitness();saveWitness();showReturn(artifact,trace)}
function showReturn(artifact,trace){const prev=game.ghost,shared=prev?.path?.length?routeOverlap(prev.path,trace.path):null;const bundle={schema:'sleeper.one-return.bundle/v3-native',artifact,nativeRouteTrace:trace,authority:{artifact:'recovered-v2-law/static-port',nativeRouteTrace:'EVIDENCE_ONLY / CONTINUOUS SIDECAR'}};$('#modalCard').innerHTML=`<h1>RETURN // ${artifact.worldKey}</h1><div class="small">${escapeHtml(artifact.returnedSource)}</div><div class="compare"><div class="metric"><b>${artifact.measures.steps}</b><span>STEPS</span></div><div class="metric"><b>${artifact.proofs.length}/8</b><span>PROOFS</span></div><div class="metric"><b>${artifact.dominantOperator.toUpperCase()}</b><span>DOMINANT OP</span></div><div class="metric"><b>${shared==null?'—':Math.round(shared*100)+'%'}</b><span>GHOST OVERLAP</span></div></div><div class="small cyan">${escapeHtml(artifact.transferInstruction)}</div><h1 style="margin-top:18px">RETURN ARTIFACT v2 + NATIVE ROUTE TRACE</h1><pre class="artifact">${escapeHtml(JSON.stringify(bundle,null,2))}</pre><div class="modal-actions"><button id="copyBundle">COPY BUNDLE</button><button id="downloadBundle">DOWNLOAD JSON</button><button id="again">SAME WORLD / AGAIN</button><button id="newWorld">NEW WORLD</button></div><div class="provenance">The artifact preserves the recovered v2 schema and derivation. The continuous native route trace is a separate EVIDENCE_ONLY sidecar; it is not sleeper.route-witness/v0.1 and can never fabricate or replace Gate proof. A previous same-world trace appears as a faint DISC ghost and as a TRACE comparison/playback layer.</div>`;$('#modal').classList.remove('hidden');$('#copyBundle').onclick=()=>navigator.clipboard?.writeText(JSON.stringify(bundle,null,2));$('#downloadBundle').onclick=()=>download(`${artifact.worldKey}-one-return.json`,JSON.stringify(bundle,null,2));$('#again').onclick=()=>{const s=game.law.source,c=game.law.cell.id,f=game.law.figure.id;$('#modal').classList.add('hidden');start(s,c,f)};$('#newWorld').onclick=()=>location.reload()}
function routeOverlap(a,b){const A=new Set(a.map(([x,y])=>`${Math.floor(x*2)/2},${Math.floor(y*2)/2}`)),B=new Set(b.map(([x,y])=>`${Math.floor(x*2)/2},${Math.floor(y*2)/2}`));let n=0;for(const k of B)if(A.has(k))n++;return B.size?n/B.size:0}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function preview(){const law=compile($('#source').value,$('#cell').value,$('#figure').value);$('#worldPreview').innerHTML=law.facts.map((x,i)=>`<div><span class="gold">${i===0?law.key:'·'}</span> ${escapeHtml(x)}</div>`).join('')}
function start(source,cell,figure){cancelAnimationFrame(raf);game=newGame(source,cell,figure);game.lastHudAt=0;game.ghost=loadGhost(game.law.key);projection='city';logLines=[];addLog(`WORLD ${game.law.key} / ${game.law.cell.label} / ${game.law.figure.label}`);addLog(`TRANSFER ASSIGNS ${game.law.transferTool.toUpperCase()}.`);if(game.ghost)addLog('SAME-WORLD ROUTE TRACE FOUND / GHOST ARMED.');$('#boot').classList.add('hidden');$('#app').classList.remove('hidden');$('#projectionLabel').textContent='CITY';renderHUD();last=0;raf=requestAnimationFrame(frame)}
function showField(){game.keys.clear();game.lastMovedAt=performance.now();if(innerWidth<=820){$('#side').classList.toggle('show');return}const html=`<h1>FIELD / ${game.law.key}</h1><div class="small">${escapeHtml(game.law.cell.law)}</div><pre class="artifact">${escapeHtml(game.law.facts.join('\n'))}\n\nCONTROLS\nW/S move · A/D turn · Q/E strafe\nC CONCH · K KERIS · 8 W8 · P SPIRAL\n\n${game.gates.map(g=>`${g.glyph} ${g.name}\n${g.instruction}`).join('\n\n')}</pre><div class="modal-actions"><button id="closeField">CLOSE</button><button id="exportWitness">EXPORT CURRENT TRACE</button></div>`;$('#modalCard').innerHTML=html;$('#modal').classList.remove('hidden');$('#closeField').onclick=()=>{$('#modal').classList.add('hidden');game.lastMovedAt=performance.now()};$('#exportWitness').onclick=()=>download(`${game.law.key}-native-route-trace.json`,JSON.stringify(snapshotWitness(),null,2))}
function init(){for(const c of CELLS)$('#cell').insertAdjacentHTML('beforeend',`<option value="${c.id}">${c.label} — ${escapeHtml(c.text)}</option>`);for(const f of FIGURES)$('#figure').insertAdjacentHTML('beforeend',`<option value="${f.id}">${f.mark} ${f.label} — ${f.line}</option>`);['input','change'].forEach(ev=>{$('#source').addEventListener(ev,preview);$('#cell').addEventListener(ev,preview);$('#figure').addEventListener(ev,preview)});preview();try{const last=JSON.parse(localStorage.getItem('sleeper:last')||'null');if(last){$('#resume').classList.remove('hidden');$('#resume').textContent='REENTER LAST WORLD';$('#resume').title='Recompile the same source / cell / figure; play position and proofs are not restored.';$('#resume').onclick=()=>start(last.source,last.cell,last.figure)}}catch{}
$('#enter').onclick=()=>start($('#source').value,$('#cell').value,$('#figure').value);$('#menuBtn').onclick=showField;$('#returnBtn').onclick=()=>addLog('RETURN / FOLLOW 回 TO THE ORIGIN COORDINATE.');$$('[data-tool]').forEach(b=>b.onclick=()=>useTool(b.dataset.tool));
addEventListener('keydown',e=>{if(!game||uiPaused())return;const k=e.key.toLowerCase();if(['w','a','s','d','q','e','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();game.keys.add(k)}if(e.repeat)return;if(k==='c')useTool('conch');if(k==='k')useTool('keris');if(k==='8')useTool('w8');if(k==='p')useTool('spiral')});addEventListener('keyup',e=>game?.keys.delete(e.key.toLowerCase()));
$$('[data-hold]').forEach(b=>{const k=b.dataset.hold;const on=e=>{e.preventDefault();game?.keys.add(k)},off=e=>{e.preventDefault();game?.keys.delete(k)};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});$('#view').addEventListener('pointermove',e=>{if(game&&!uiPaused()&&e.buttons===1){game.player.direction=normalAngle(game.player.direction+e.movementX*.004);game.lastMovedAt=performance.now()}});addEventListener('blur',()=>game?.keys.clear());$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){$('#modal').classList.add('hidden');if(game)game.lastMovedAt=performance.now()}});}
init();
