'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const TAU=Math.PI*2, WORLD_SIZE=27, DENSITY=' .·,:;i1tfLCG08@', REDUCED='  ·:+#@';
const TOOLS=['conch','keris','w8','spiral'];
const CANON=['PROVENANCE','TRUTH','COMPRESSION','RETRIEVAL','OPERATION','MEASURE','TRANSFER','RESILIENCE'];
const CELLS=[
{id:'doors',label:'DOORS',text:'ALL MAPS ARE WRONG. SOME BECOME DOORS.',provenance:'Sleeper field line / current working canon',law:'A wrong model may still become a useful passage.',loopBias:5,gateOrder:CANON},
{id:'one-return',label:'ONE RETURN',text:'GOOD FOR ONE RETURN.',provenance:'Sleeper return line / current working canon',law:'A useful artifact must survive one changed context.',loopBias:-3,gateOrder:['PROVENANCE','RETRIEVAL','TRUTH','OPERATION','COMPRESSION','TRANSFER','MEASURE','RESILIENCE']},
{id:'four-verbs',label:'FOUR VERBS',text:'LISTEN. CUT. CARRY. RETURN.',provenance:'Recovered Sleeper operator sequence',law:'Perception becomes action only when something can be carried back.',loopBias:1,gateOrder:['TRUTH','PROVENANCE','OPERATION','RETRIEVAL','TRANSFER','MEASURE','COMPRESSION','RESILIENCE']},
{id:'eighth-position',label:'EIGHTH POSITION',text:'未始来时末已示空',provenance:'Jointly evolved working line; philological status remains open',law:'Read eight positions as a structure, not as borrowed authority.',loopBias:8,gateOrder:['PROVENANCE','COMPRESSION','TRUTH','MEASURE','OPERATION','RETRIEVAL','RESILIENCE','TRANSFER']},
{id:'wind',label:'WIND',text:'SOME REPLIES TAKE WIND.',provenance:'Sleeper kite line / current working canon',law:'Hold enough tension to carry; release enough to remain responsive.',loopBias:3,gateOrder:['MEASURE','TRUTH','PROVENANCE','OPERATION','RETRIEVAL','COMPRESSION','RESILIENCE','TRANSFER']},
{id:'question',label:'QUESTION',text:'ASK BETTER.',provenance:'Sleeper oracle line / current working canon',law:'The returned question should improve the next operation.',loopBias:-5,gateOrder:['TRUTH','MEASURE','PROVENANCE','OPERATION','RESILIENCE','COMPRESSION','RETRIEVAL','TRANSFER']}
];
const FIGURES=[
{id:'urchin',label:'URCHIN',mark:'✣',line:'EDGE / QUICK CUT',effect:'Moves quickly; Keris reforms sooner.',movementSpeed:2.75,conchMs:4200,kerisCooldownMs:1600,truthHoldMs:1500,measureHoldMs:2100,measureMin:1.75,measureMax:2.65},
{id:'slothcake',label:'SLOTHCAKE',mark:'◒',line:'PATIENCE / LONG ECHO',effect:'Conch lasts longer; stillness resolves sooner.',movementSpeed:2.25,conchMs:5600,kerisCooldownMs:2500,truthHoldMs:1050,measureHoldMs:2300,measureMin:1.6,measureMax:2.55},
{id:'kite',label:'KITE',mark:'◇',line:'TENSION / WIDE MEASURE',effect:'Travels lightly; the distance band is wider.',movementSpeed:2.55,conchMs:4000,kerisCooldownMs:2200,truthHoldMs:1700,measureHoldMs:1800,measureMin:1.35,measureMax:3.05}
];
const GATES={
PROVENANCE:{glyph:'◉',color:'#e9c16f',method:'conch',line:'THE SIGNAL NAMED WHERE IT CAME FROM.',instruction:'Stand near the Gate and sound CONCH.'},
TRUTH:{glyph:'◌',color:'#d9e0d7',method:'stillness',line:'YOU LET THE FIELD MOVE WITHOUT INVENTING A MOVE.',instruction:'Stand close. Release every control and wait.'},
COMPRESSION:{glyph:'◆',color:'#e18e64',method:'spiral',line:'THE SAME CITY SURVIVED ANOTHER READING.',instruction:'Stand near the Gate and switch projection with SPIRAL.'},
RETRIEVAL:{glyph:'⌁',color:'#7cb7bf',method:'w8',line:'THE COORDINATE WAS RECOVERED AFTER LEAVING IT.',instruction:'Place W8 here, travel away, then invoke W8 again.'},
OPERATION:{glyph:'†',color:'#e9c16f',method:'keris',line:'THE MAP BECAME A VERB.',instruction:'Make a real wall-cut with KERIS while close to the Gate.'},
MEASURE:{glyph:'△',color:'#8ebfc8',method:'distance',line:'DISTANCE BECAME EVIDENCE, NOT DECORATION.',instruction:'Hold the figure inside the indicated distance band.'},
TRANSFER:{glyph:'⇄',color:'#df8d57',method:'conch',line:'ONE OPERATOR WORKED IN A SECOND CONTEXT.',instruction:'Reuse the world-assigned operator near this Gate.'},
RESILIENCE:{glyph:'∞',color:'#c9d7d2',method:'relocation',line:'THE TOKEN SURVIVED A FAILED COORDINATE.',instruction:'Find it once. When it moves, retrieve the same token again.'}
};
const PRIMARY={conch:'PROVENANCE',keris:'OPERATION',w8:'RETRIEVAL',spiral:'COMPRESSION'};
const NOTES={conch:'The nearby signal was revealed and sourced.',keris:'A wall changed the next possible route.',w8:'The marked coordinate was left, held, and recovered.',spiral:'The city survived a change of representation.'};
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function hashString(value){let h=2166136261;for(const ch of value.normalize('NFC')){h^=ch.codePointAt(0)||0;h=Math.imul(h,16777619)}return h>>>0}
function seedFromSource(s){return hashString(s.trim().replace(/\s+/g,' ').toUpperCase())}
function rng(seed){let state=seed||0x6d2b79f5;return()=>{state+=0x6d2b79f5;let v=state;v=Math.imul(v^(v>>>15),v|1);v^=v+Math.imul(v^(v>>>7),v|61);return((v^(v>>>14))>>>0)/4294967296}}
function tokens(cell){if(cell.id==='eighth-position')return Array.from(cell.text).slice(0,8);const g=Array.from(cell.text.match(/[\p{L}\p{N}]+|[^\s]/gu)||[]);if(!g.length)return['RETURN'];return Array.from({length:8},(_,i)=>g[i%g.length])}
function compile(source,cellId,figureId){const normalized=source.trim().replace(/\s+/g,' ')||CELLS[0].text;const cell=CELLS.find(x=>x.id===cellId)||CELLS[0];const figure=FIGURES.find(x=>x.id===figureId)||FIGURES[0];const seed=seedFromSource(`${normalized}\u241f${cell.id}\u241f${figure.id}`);const transferTool=TOOLS[seed%TOOLS.length];const loops=Math.max(14,Math.min(38,24+cell.loopBias+(seed%7)-3));const alpha=Array.from(normalized.toUpperCase()).filter(c=>/[\p{L}\p{N}]/u.test(c));const wallAlphabet=alpha.length?alpha:Array.from('RETURN');const key=seed.toString(36).toUpperCase().padStart(7,'0');return{source:normalized,seed,key,loops,wallAlphabet,cell,figure,cellTokens:tokens(cell),gateOrder:cell.gateOrder,transferTool,facts:[`PHRASE ${key} fixes maze topology, ${loops} extra passages, Gate coordinates, and the wall alphabet.`,`VERSE CELL “${cell.label}” supplies the eight tokens, their order, and the governing law.`,`FIGURE ${figure.label} changes movement and timing: ${figure.effect}`,`WORLD KEY sets the tonal center and requires ${transferTool.toUpperCase()} at TRANSFER.`]}}
function gateInstruction(law,name){if(name==='TRANSFER')return`First prove ${PRIMARY[law.transferTool]}, then reuse ${law.transferTool.toUpperCase()} here.`;if(name==='MEASURE')return`Hold between ${law.figure.measureMin.toFixed(1)}–${law.figure.measureMax.toFixed(1)} units for ${(law.figure.measureHoldMs/1000).toFixed(1)} seconds.`;if(name==='TRUTH')return`Stand close. Release every control for ${(law.figure.truthHoldMs/1000).toFixed(1)} seconds.`;return GATES[name].instruction}
function shuffle(items,random){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function distances(grid,sx,sy){const n=grid.length,d=Array.from({length:n},()=>Array(n).fill(-1)),q=[{x:sx,y:sy}];d[sy][sx]=0;for(let h=0;h<q.length;h++){const c=q[h];for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const x=c.x+dx,y=c.y+dy;if(x>=0&&x<n&&y>=0&&y<n&&grid[y][x]===0&&d[y][x]<0){d[y][x]=d[c.y][c.x]+1;q.push({x,y})}}}return d}
function buildCity(source,cellId,figureId){const law=compile(source,cellId,figureId),random=rng(law.seed),size=WORLD_SIZE,grid=Array.from({length:size},()=>Array(size).fill(1)),stack=[{x:1,y:1}];grid[1][1]=0;while(stack.length){const c=stack[stack.length-1],opts=shuffle([[2,0],[-2,0],[0,2],[0,-2]],random).filter(([dx,dy])=>{const x=c.x+dx,y=c.y+dy;return x>0&&x<size-1&&y>0&&y<size-1&&grid[y][x]!==0});if(!opts.length){stack.pop();continue}const[dx,dy]=opts[0];grid[c.y+dy/2][c.x+dx/2]=0;grid[c.y+dy][c.x+dx]=0;stack.push({x:c.x+dx,y:c.y+dy})}
let loopsMade=0,attempts=0;while(loopsMade<law.loops&&attempts<800){attempts++;const x=1+Math.floor(random()*(size-2)),y=1+Math.floor(random()*(size-2));if(grid[y][x]!==1)continue;const h=grid[y][x-1]===0&&grid[y][x+1]===0,v=grid[y-1][x]===0&&grid[y+1][x]===0;if(h!==v){grid[y][x]=0;loopsMade++}}
for(let y=0;y<size;y++)for(let x=0;x<size;x++){if(x===0||y===0||x===size-1||y===size-1)grid[y][x]=9;else if(grid[y][x]!==0)grid[y][x]=1+Math.floor(random()*3)}
const dist=distances(grid,1,1),candidates=[];for(let y=1;y<size-1;y++)for(let x=1;x<size-1;x++)if(dist[y][x]>=5)candidates.push({x,y,distance:dist[y][x]});candidates.sort((a,b)=>a.distance-b.distance);const selected=[];for(let gi=0;gi<law.gateOrder.length;gi++){const target=Math.floor(((gi+1)/(law.gateOrder.length+1))*candidates.length);let chosen=null;for(let r=0;r<candidates.length&&!chosen;r++)for(const ci of[target+r,target-r]){const c=candidates[ci];if(c&&selected.every(p=>Math.hypot(p.x-c.x,p.y-c.y)>=4.25)){chosen=c;break}}selected.push(chosen||candidates[Math.min(target,candidates.length-1)]||{x:1,y:1})}
const used=[];const gates=law.gateOrder.map((name,i)=>{const def=GATES[name];const alt=candidates.slice().reverse().find(c=>selected.every(p=>Math.hypot(p.x-c.x,p.y-c.y)>=3.5)&&used.every(p=>Math.hypot(p.x-c.x,p.y-c.y)>=3.5))||candidates[candidates.length-1]||{x:1,y:1};used.push(alt);return{...def,name,method:name==='TRANSFER'?law.transferTool:def.method,instruction:gateInstruction(law,name),x:selected[i].x+.5,y:selected[i].y+.5,alternate:{x:alt.x+.5,y:alt.y+.5},token:law.cellTokens[i],collected:false,relocated:false,progress:0}});return{law,size,grid,start:{x:1.5,y:1.5},gates,sourceChars:law.wallAlphabet}}
function normalAngle(a){while(a>Math.PI)a-=TAU;while(a<-Math.PI)a+=TAU;return a}
function isOpen(g,x,y){const r=.19;return[[x-r,y-r],[x+r,y-r],[x-r,y+r],[x+r,y+r]].every(([px,py])=>g.grid[Math.floor(py)]?.[Math.floor(px)]===0)}
function castRay(g,angle,max=40){const rx=Math.cos(angle),ry=Math.sin(angle);let mx=Math.floor(g.player.x),my=Math.floor(g.player.y);const dx=Math.abs(1/(Math.abs(rx)<.00001?.00001:rx)),dy=Math.abs(1/(Math.abs(ry)<.00001?.00001:ry)),sx=rx<0?-1:1,sy=ry<0?-1:1;let sideX=rx<0?(g.player.x-mx)*dx:(mx+1-g.player.x)*dx,sideY=ry<0?(g.player.y-my)*dy:(my+1-g.player.y)*dy,side=0,cell=9;for(let i=0;i<80;i++){if(sideX<sideY){sideX+=dx;mx+=sx;side=0}else{sideY+=dy;my+=sy;side=1}if(mx<0||my<0||mx>=g.size||my>=g.size)break;cell=g.grid[my][mx];if(cell>0)break}const distance=side===0?sideX-dx:sideY-dy,wp=side===0?g.player.y+distance*ry:g.player.x+distance*rx;return{distance:Math.min(Math.abs(distance),max),side,cell,mapX:mx,mapY:my,texture:wp-Math.floor(wp)}}
function lineOfSight(g,x,y){const dx=x-g.player.x,dy=y-g.player.y,d=Math.hypot(dx,dy);return castRay(g,Math.atan2(dy,dx),d+1).distance>=d-.28}
function nearestGate(g,max=Infinity){let n=null;for(const gate of g.gates){if(gate.collected)continue;const d=Math.hypot(g.player.x-gate.x,g.player.y-gate.y);if(d<=max&&(!n||d<n.distance))n={gate,distance:d}}return n}
