
"use strict";
const $=s=>document.querySelector(s), TAU=Math.PI*2, clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const THEMES={HOUSE:{bg:'#05070b',fg:'#f4f6fb',mut:'#8d98aa',hair:'rgba(255,255,255,.12)',glass:'rgba(8,11,17,.82)',a:'#ff9b58',b:'#72bfff',c:'#78dfb4'},SUMI:{bg:'#0a0a08',fg:'#efebe2',mut:'#a8a08f',hair:'rgba(239,235,226,.12)',glass:'rgba(16,14,10,.82)',a:'#d29c62',b:'#98c8b3',c:'#c8b36d'},OP:{bg:'#020407',fg:'#fbfdff',mut:'#91a6b9',hair:'rgba(255,255,255,.18)',glass:'rgba(6,9,14,.88)',a:'#ffffff',b:'#72bfff',c:'#ff9b58'},IRIS:{bg:'#060915',fg:'#f5f6fb',mut:'#b0bad4',hair:'rgba(255,255,255,.13)',glass:'rgba(11,14,25,.86)',a:'#e9c86b',b:'#6ea0ff',c:'#d8dfff'}};
const DISC=[["first","FIRST BLOOM","the organism answered"],["constellation","CONSTELLATION","chain of five or more"],["mirror","MIRROR PAIR","a bloom crossed the fold"],["memory","MEMORY LOOP","history changed future adjacency"],["byte","BYTE SONG","bit-law formed a four-cell phrase"],["return","RETURN","a tier-five cell changed species"]];
const CH=[{name:'ALIGN',need:6,text:'Identity first: place like under like.'},{name:'POLARITY',need:8,text:'Seeds can now arrive from either pole.'},{name:'ECHO',need:10,text:'Some successful events answer from the opposite side.'},{name:'FOLD',need:12,text:'Distance can collapse: opposite cells become causally linked.'},{name:'CASCADE',need:16,text:'Neighbor relations propagate. Shape the board before impact.'},{name:'OPEN BLOOM',need:24,text:'All laws coexist. Cultivation becomes the deeper game.'}];
const LAWSET=['FOLD','INTERFERENCE','BYTE','ATTRACTOR','FEEDBACK']; const N=12, shapes=['circle','square','triangle'], glyphs=['○','□','△'], baseHue=[28,205,158];
const gene0={law:'FOLD',sym:7,hue:10,warp:.24,memory:.10,topology:'LOCAL',scale:0,voice:'GLASS',rhythm:'PULSE',tempo:92,seed:1337};
let gene={...gene0}, cells=[], seed=null, rotation=0, rotVel=0, snapTarget=0, snapping=false, drag=false, lastX=0, lastT=0;
let score=0,combo=1,bestCombo=1,blooms=0,chapter=0,chapterBlooms=0,generation=0,misses=0,bestChain=0,chainNow=0,controlMode='FLOW',garden=false,pace=1,pressure=.75,pins={BODY:false,PATH:false,VOICE:false},theme='HOUSE';
let eventTape=[],lineage=[],discoveries=new Set(),lawStats={},fieldTime=0,fieldImpulse=0,breath=0,pendingChapter=null,mapMode='GENOME',futureQueue=[],lensTopology='BASE',lensScope=3,lensDomain='TEXT',activeOperator='⊗',receipts=[],toolglassActive=false,toolglassIndex=0,toolglassScope=3,toolglassPointerId=null,toolglassStartX=0,toolglassStartY=0,pressureCache=[];
let audio=null,master=null,soundOn=true,musicTimer=null,droneTimer=null,volume=.55; const sinks=new Set();
const cv=$('#c'),g=cv.getContext('2d',{alpha:false}); let W=0,H=0,D=1,CX=0,CY=0,R=0,running=false,paused=false,last=performance.now();
function emit(kind,data={}){const ev={kind,...data,at:Date.now()}; sinks.forEach(fn=>{try{fn(ev)}catch(_){}})}
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;cv.width=W*D;cv.height=H*D;cv.style.width=W+'px';cv.style.height=H+'px';g.setTransform(D,0,0,D,0,0);CX=W/2;CY=H*.54;R=Math.min(W*.34,H*.24)} addEventListener('resize',resize); resize();
function rngFor(seedv){let a=seedv>>>0; return ()=>{a+=0x6D2B79F5; let t=a; t=Math.imul(t^t>>>15,t|1); t^=t+Math.imul(t^t>>>7,t|61); return ((t^t>>>14)>>>0)/4294967296}} let rng=rngFor(gene.seed); const rnd=(n=1)=>rng()*n;
function save(){try{localStorage.setItem('fb5-state',JSON.stringify({gene,cells,score,combo,bestCombo,blooms,chapter,chapterBlooms,generation,misses,bestChain,controlMode,garden,pace,pressure,pins,eventTape,lineage,discoveries:[...discoveries],volume,theme,lawStats,futureQueue,lensTopology,lensScope,lensDomain,activeOperator,receipts}))}catch(_){}}
function load(){try{const x=JSON.parse(localStorage.getItem('fb5-state')||'null'); if(!x)return; gene={...gene0,...x.gene}; cells=x.cells||cells; score=x.score||0; combo=x.combo||1; bestCombo=x.bestCombo||1; blooms=x.blooms||0; chapter=x.chapter||0; chapterBlooms=x.chapterBlooms||0; generation=x.generation||0; misses=x.misses||0; bestChain=x.bestChain||0; controlMode=x.controlMode||'FLOW'; garden=!!x.garden; pace=x.pace||1; pressure=x.pressure||.75; pins={...pins,...x.pins}; eventTape=x.eventTape||[]; lineage=x.lineage||[]; discoveries=new Set(x.discoveries||[]); volume=x.volume??.55; theme=x.theme||'HOUSE'; lawStats=x.lawStats||{}; futureQueue=x.futureQueue||[]; lensTopology=x.lensTopology||'BASE'; lensScope=x.lensScope??3; lensDomain=x.lensDomain||'TEXT'; activeOperator=x.activeOperator||'⊗'; receipts=x.receipts||[]; rng=rngFor(gene.seed)}catch(_){}}
function applyTheme(name){theme=name; const t=THEMES[name]||THEMES.HOUSE, rs=document.documentElement.style; rs.setProperty('--bg',t.bg);rs.setProperty('--fg',t.fg);rs.setProperty('--mut',t.mut);rs.setProperty('--hair',t.hair);rs.setProperty('--glass',t.glass);rs.setProperty('--a',t.a);rs.setProperty('--b',t.b);rs.setProperty('--c',t.c); $('#themeLabel').textContent=name; renderStyleCards(); save(); emit('STYLE',{theme})}
function renderStyleCards(){const box=$('#styleCards'); if(!box)return; box.innerHTML=''; Object.keys(THEMES).forEach(k=>{const b=document.createElement('button'); b.className='styleCard'+(theme===k?' on':''); b.innerHTML=`<b>${k}</b><span>${k==='HOUSE'?'balanced core palette':k==='SUMI'?'quieter ink field':k==='OP'?'sharper interference / contrast':'ultramarine + gold ceremonial glow'}</span>`; b.onclick=()=>applyTheme(k); box.appendChild(b)})}
function initBoard(){if(!cells.length)cells=Array.from({length:N},(_,i)=>({type:i%3,tier:1})); for(let t=0;t<3;t++)cells[t*4].type=t}
function resetRun(){gene={...gene0,seed:(Math.random()*2**32)>>>0}; rng=rngFor(gene.seed); cells=[]; score=0; combo=1; bestCombo=1; blooms=0; chapter=0; chapterBlooms=0; generation=0; misses=0; bestChain=0; chainNow=0; eventTape=[]; lineage=[]; discoveries.clear(); lawStats={}; pins={BODY:false,PATH:false,VOICE:false}; pressure=.75; futureQueue=[]; initBoard(); ensureQueue(); seed=null; spawn(); save(); updateHUD(); renderAnalytics()}
function slotAngle(i){return -Math.PI/2+rotation+i*TAU/N} function gateAngle(){return seed?.side===-1?Math.PI/2:-Math.PI/2}
function gateIndex(){const ga=gateAngle(); let best=0,bd=99; for(let i=0;i<N;i++){const d=Math.abs(Math.atan2(Math.sin(slotAngle(i)-ga),Math.cos(slotAngle(i)-ga))); if(d<bd){bd=d; best=i}} return best}
function aligned(){return !!seed&&cells[gateIndex()].type===seed.type}
function shapePath(ctx,shape,x,y,r){ctx.beginPath(); if(shape==='circle')ctx.arc(x,y,r,0,TAU); else if(shape==='square')ctx.rect(x-r*.82,y-r*.82,r*1.64,r*1.64); else {ctx.moveTo(x,y-r); ctx.lineTo(x+r*.92,y+r*.78); ctx.lineTo(x-r*.92,y+r*.78); ctx.closePath()}}
function chapterFlags(){return{polarity:chapter>=1,echo:chapter>=2,fold:chapter>=3,cascade:chapter>=4,open:chapter>=5}}
