function lawSignal(a,t,layer=0,gg=gene){ if(gg.law==='FOLD')return .62+.18*Math.sin(a*gg.sym+t*.43+layer*.7)+.07*Math.sin(a*2-t*.19); if(gg.law==='INTERFERENCE')return .55+.16*Math.sin(a*gg.sym+t*.47)+.13*Math.sin(a*(gg.sym+1)-t*.69+layer); if(gg.law==='BYTE'){const k=Math.floor((((a/TAU)%1+1)%1)*128),tt=Math.floor(t*7),z=((k*(3+layer))^(tt+(gg.seed&31))^(k>>((layer%2)+1)))&15; return .42+.033*z} if(gg.law==='ATTRACTOR'){let q=0; eventTape.slice(-8).forEach((e,j)=>{if(e.kind!=='BLOOM')return; const ha=-Math.PI/2+(e.slot%N)*TAU/N,d=Math.atan2(Math.sin(a-ha),Math.cos(a-ha)); q+=Math.exp(-d*d*(2.2+layer*.3))*(.65+.08*(e.chain||1))*(1-j*.07)}); return .48+.16*Math.sin(a*gg.sym*.55+t*.22+layer)+.19*clamp(q/2.8,0,1)} const mem=eventTape.slice(-10).reduce((q,e,j)=>q+Math.sin(a*(1+(e.chain||1))+e.type*1.8+t*.24)*(1-j*.06),0); return .52+.11*Math.sin(a*gg.sym+t*.24+layer)+mem*.018 }
function neighborSet(i,topology=gene.topology){ let out=topology==='SKIP'?[(i-2+N)%N,(i+2)%N]:gene.topology==='TRIAD'?[(i-1+N)%N,(i+1)%N,(i+N/3)%N]:topology==='MIRROR'?[(i-1+N)%N,(i+1)%N,(i+N/2)%N]:[(i-1+N)%N,(i+1)%N]; if(gene.law==='FOLD'&&topology!=='MIRROR')out.push((i+N/2)%N); if(gene.law==='BYTE'){const st=1+((gene.seed>>>(i%16))&1); out.push((i-st+N)%N,(i+st)%N)} if(gene.law==='ATTRACTOR')eventTape.slice(-3).filter(e=>e.kind==='BLOOM').forEach(e=>out.push(e.slot%N)); return [...new Set(out.map(x=>(x+N)%N))].filter(x=>x!==i)}
function predictedChain(start=gateIndex(),type=seed?.type,topology=gene.topology){ if(type==null||cells[start].type!==type)return []; const f=chapterFlags(),out=[start],seen=new Set(out); if(f.fold){const j=(start+N/2)%N; if(cells[j].type===type&&!seen.has(j)){out.push(j); seen.add(j)}} if(f.cascade){const q=[...out]; while(q.length&&out.length<9){const cur=q.shift(); for(const j of neighborSet(cur,topology)){if(seen.has(j))continue; if(cells[j].type===type){seen.add(j); out.push(j); q.push(j)}}}} return out }
function chooseSeedType(){if(blooms<3)return cells[Math.floor(rnd(N))].type; return rnd()<.74?cells[Math.floor(rnd(N))].type:Math.floor(rnd(3))}
function ensureQueue(){while(futureQueue.length<4)futureQueue.push(chooseSeedType()); updateQueueHUD()}
function takeQueuedType(){ensureQueue();const t=futureQueue.shift();ensureQueue();return t}
function updateQueueHUD(){const e=$('#queueHUD');if(e)e.textContent=futureQueue.map(t=>glyphs[t]).join(' ')}
function queueWeights(){return futureQueue.map((type,i)=>({type,weight:futureQueue.length-i}))}
function currentTopology(){return toolglassActive?['BASE','LOCAL','SKIP','TRIAD','MIRROR'][toolglassIndex]:lensTopology}
function previewTopology(){const tp=currentTopology(); return tp==='BASE'?gene.topology:tp}
function typeSupply(type){return cells.reduce((q,c)=>q+(c.type===type?(1+c.tier*.35):0),0)}
function pressureSnapshot(topology=previewTopology()){return [0,1,2].map(type=>{let bid=0; queueWeights().forEach(({type:t,weight})=>{if(t!==type)return; const p=bestPotential(type,topology); bid += weight*(1+p.chain*.85)}); const ask=typeSupply(type); const imbalance=+(bid-ask).toFixed(2); return {type,bid:+bid.toFixed(2),ask:+ask.toFixed(2),imbalance};}).sort((a,b)=>Math.abs(b.imbalance)-Math.abs(a.imbalance))}
function strongestPressure(){pressureCache=pressureSnapshot(); return pressureCache[0]||{type:0,imbalance:0}}
const DOMAIN_LADDER={TEXT:['LETTER','WORD','PHRASE','SENTENCE','PARAGRAPH','SECTION','CHAPTER','BOOK','LIBRARY'],ATLAS:['PULSE','TASK','ROUTE','SESSION','DAY','WEEK','PROJECT','PROGRAM','FEDERATION'],DAYLINE:['MOMENT','ACTION','BLOCK','ARC','DAY','WEEK','CYCLE','SEASON','HISTORY'],DATADISC:['CELL','FIELD','ROW','RECORD','TABLE','DATASET','CORPUS','WAREHOUSE','ECOSYSTEM'],OBJECT:['TRACE','FEATURE','PART','COMPONENT','MODULE','ASSEMBLY','MACHINE','LINE','FLEET']};
const WINDOW_LADDER=[1,2,3,4,6,8,12,16,24];
function scopeIndex(){return toolglassActive?toolglassScope:lensScope}
function scopeDomainList(domain=lensDomain){return DOMAIN_LADDER[domain]||DOMAIN_LADDER.TEXT}
function scopeLabel(domain=lensDomain,idx=scopeIndex()){const arr=scopeDomainList(domain); return arr[clamp(idx,0,arr.length-1)]}
function scopeWindow(idx=scopeIndex()){return WINDOW_LADDER[clamp(idx,0,WINDOW_LADDER.length-1)]}
function tapeChunks(size=scopeWindow()){const src=eventTape.slice(-Math.max(size*4,size)); const out=[]; for(let i=0;i<src.length;i+=size){const chunk=src.slice(i,i+size); if(!chunk.length)continue; const counts=[0,0,0]; let blooms=0,drifts=0; chunk.forEach(e=>{if(e.type!=null)counts[e.type]=(counts[e.type]||0)+1; if(e.kind==='BLOOM')blooms++; if(e.kind==='DRIFT')drifts++}); let dom=0; if(counts[1]>counts[dom])dom=1; if(counts[2]>counts[dom])dom=2; out.push({n:out.length+1,size:chunk.length,dominant:dom,blooms,drifts,chain:Math.max(...chunk.map(e=>e.chain||0),0)})} return out}
function scopeNeighbors(domain=lensDomain){const arr=scopeDomainList(domain),i=scopeIndex(); return {micro:arr[Math.max(0,i-1)],current:arr[i],macro:arr[Math.min(arr.length-1,i+1)]}}
const OPERATORS=[['⊙','SELECT'],['↔','ALIGN'],['⊗','COMPOSE'],['⇢','PROPAGATE'],['✓','COMMIT'],['↩','RETURN']];
function addReceipt(op,subject,result=''){const r={id:Date.now().toString(36),at:new Date().toISOString(),op,domain:lensDomain,scope:scopeLabel(),subject,result}; receipts.push(r); if(receipts.length>32)receipts.shift(); renderReceipts(); save(); return r}
function renderOperatorTabs(){const box=$('#operatorTabs');if(!box)return;box.innerHTML='';OPERATORS.forEach(([sym,name])=>{const b=document.createElement('button');b.textContent=`${sym} ${name}`;b.classList.toggle('on',activeOperator===sym);b.onclick=()=>{activeOperator=sym;addReceipt(sym,'operator',name);renderOperatorTabs();drawLens();};box.appendChild(b)})}
function renderReceipts(){const box=$('#receiptRows');if(!box)return;box.innerHTML='';receipts.slice(-6).reverse().forEach(r=>{const d=document.createElement('div');d.className='lawRow';d.innerHTML=`<b>${r.op}</b><span>${r.scope}</span><span>${r.domain}</span><span>${r.subject}</span><span>${r.result||'—'}</span>`;box.appendChild(d)}); if(!box.children.length){const d=document.createElement('div');d.className='note';d.textContent='No receipts yet.';box.appendChild(d)}}
function studioBridge(){try{const raw=localStorage.getItem('fb-lens-studio-packet'); if(!raw)return false; const p=JSON.parse(raw); if(!Array.isArray(p.items)||!p.items.length)return false; lensDomain=p.domain||'DATADISC'; lensScope=clamp(p.scope??3,0,8); futureQueue=p.items.slice(0,4).map(it=>Math.abs((it.hash||0)%3)); eventTape=p.items.slice(0,24).map((it,i)=>({kind:'BLOOM',slot:i%N,type:Math.abs((it.hash||i)%3),chain:1+Math.abs((it.hash||i)%4),tier:1+Math.abs((it.hash||i)%5),law:'IMPORT',label:it.label,address:it.address?.projection||it.id,provenance:it.provenance,schemaType:it.type,relations:it.relations})); addReceipt('↩','studio import',`${p.items.length} addressed atoms · ${p.source?.format||'data'}`); localStorage.removeItem('fb-lens-studio-packet'); return true}catch(_){return false}}
function bestPotential(type,topology=gene.topology){let best={chain:0,slot:0};for(let i=0;i<N;i++){if(cells[i].type!==type)continue;const ch=predictedChain(i,type,topology).length;if(ch>best.chain)best={chain:ch,slot:i}}return best}
