function spawn(forced=null){if(seed||paused)return; const f=chapterFlags(); let side=forced?.side??1; if(f.polarity&&!forced)side=(blooms+misses)%2?1:-1; seed={type:forced?.type??takeQueuedType(),side,p:0,echo:!!forced?.echo}}
function discover(id){if(discoveries.has(id))return; discoveries.add(id); toast(DISC.find(x=>x[0]===id)?.[1]||'DISCOVERED'); save(); emit('DISCOVER',{id})}
function pushEvent(e){eventTape.push({...e,at:blooms+misses}); if(eventTape.length>36)eventTape.shift(); const st=lawStats[e.law]||(lawStats[e.law]={blooms:0,drifts:0,chainSum:0,selects:0,best:0}); if(e.kind==='BLOOM'){st.blooms++; st.chainSum+=(e.chain||1); st.best=Math.max(st.best,e.chain||1)} if(e.kind==='DRIFT')st.drifts++; }
function doBloom(){ if(!seed)return; const i=gateIndex(),cell=cells[i],type=seed.type,side=seed.side,echo=seed.echo,path=predictedChain(i,type); chainNow=Math.max(1,path.length); bestChain=Math.max(bestChain,chainNow); const tier=cell.tier=Math.min(5,cell.tier+1),gain=Math.round(55*tier*combo*(1+(chainNow-1)*.17)); score+=gain; combo=Math.min(16,combo+1); bestCombo=Math.max(bestCombo,combo); blooms++; chapterBlooms++; pushEvent({kind:'BLOOM',slot:i,type,chain:chainNow,tier,law:gene.law}); fieldImpulse=Math.min(1.5,fieldImpulse+.08*chainNow+.04*tier); playBloom(type,tier,slotAngle(i),chainNow); haptic(7+chainNow*2); emit('BLOOM',{slot:i,type,chain:chainNow,tier,law:gene.law}); discover('first'); if(chainNow>=5){discover('constellation'); breath=1.5} const extras=path.slice(1); extras.forEach((j,k)=>{setTimeout(()=>{cells[j].tier=Math.min(5,cells[j].tier+1); score+=15*cells[j].tier*combo; playChain(type,cells[j].tier,k+1,slotAngle(j))},60*(k+1))}); if(chapter>=3&&extras.some(j=>j===(i+N/2)%N))discover('mirror'); if(gene.law==='ATTRACTOR'&&chainNow>=3)discover('memory'); if(gene.law==='BYTE'&&chainNow>=4)discover('byte'); if(cell.tier>=5){cell.tier=1; cell.type=(cell.type+1+(rnd()<.4?1:0))%3; score+=500*combo; discover('return'); toast('RETURN')} const oldSeed={type,side,echo}; seed=null; updateHUD(); save(); if(chapterBlooms>=CH[chapter].need&&chapter<CH.length-1){pendingChapter=chapter+1; setTimeout(openChapter,450); return} const breedEvery=chapter<3?6:8; if(blooms>0&&blooms%breedEvery===0){setTimeout(openBreed,450); return} if(chapterFlags().echo&&blooms%3===0&&side===1&&!echo){setTimeout(()=>spawn({type:oldSeed.type,side:-1,echo:true}),380)} else setTimeout(()=>spawn(),garden?250:420) }
function doDrift(){ if(!seed)return; const i=gateIndex(),cell=cells[i]; pushEvent({kind:'DRIFT',slot:i,type:seed.type,chain:0,tier:cell.tier,law:gene.law}); misses++; combo=1; score=Math.max(0,score-20); cell.type=(cell.type+seed.type+1)%3; cell.tier=Math.max(1,cell.tier-1); playMiss(); toast('DRIFT'); emit('DRIFT',{slot:i,type:seed.type,law:gene.law}); seed=null; updateHUD(); save(); setTimeout(()=>spawn(),garden?250:460) }
function resolve(){aligned()?doBloom():doDrift()}
function bodyFields(x){return{law:x.law,sym:x.sym,hue:x.hue,warp:x.warp}} function pathFields(x){return{topology:x.topology,scale:x.scale,memory:x.memory}} function voiceFields(x){return{voice:x.voice,rhythm:x.rhythm,tempo:x.tempo}}
function applyPins(candidate){const n={...candidate}; if(pins.BODY)Object.assign(n,bodyFields(gene)); if(pins.PATH)Object.assign(n,pathFields(gene)); if(pins.VOICE)Object.assign(n,voiceFields(gene)); return n}
function mutate(kind,i){ const n={...gene},p=pressure,laws=LAWSET,tops=['LOCAL','SKIP','TRIAD'],voices=['GLASS','WOOD','WIRE'],rhythms=['PULSE','DRIFT','STEP']; if(kind==='BODY'){const cur=laws.indexOf(n.law); n.law=laws[(cur+1+i)%laws.length]; n.sym=clamp(Math.round(n.sym+([-1,1,2][i]*p)),4,12); n.hue=(n.hue+[31,83,149][i]*p)%360; n.warp=clamp(n.warp+[.05,-.04,.10][i]*p,.05,.65)} if(kind==='PATH'){n.topology=tops[i]; n.scale=(n.scale+i+1)%3; n.memory=clamp(n.memory+[.04,-.025,.08][i]*p,.02,.32)} if(kind==='VOICE'){n.voice=voices[i]; n.rhythm=rhythms[i]; n.tempo=clamp(Math.round(n.tempo+[-8,4,12][i]*p),68,126)} n.seed=(n.seed*1664525+1013904223+i*7919+generation*31)>>>0; return applyPins(n) }
function buildOffspring(){const cyc=generation%3; return cyc===0?[['BODY',0],['PATH',1],['VOICE',2]]:cyc===1?[['VOICE',0],['BODY',2],['PATH',0]]:[['PATH',2],['VOICE',1],['BODY',1]]}
function geneName(x){return `${x.law} · ${x.topology} · ${x.voice}`} function geneImpact(x,kind){return kind==='BODY'?`${x.sym}-fold · field law ${x.law}`:kind==='PATH'?`${x.topology} propagation · scale ${x.scale}`:`${x.voice} · ${x.rhythm} · ${x.tempo} BPM`}
function previewGene(cvx,gg,t){const x=cvx.getContext('2d'),w=cvx.width,h=cvx.height; x.fillStyle='#04060a'; x.fillRect(0,0,w,h); x.save(); x.translate(w/2,h/2); for(let l=0;l<3;l++){x.beginPath(); for(let k=0;k<=120;k++){const a=k/120*TAU,rr=56*(1+.26*Math.sin(a*(gg.sym-l)+t*.001*(.3+l*.1))+gg.warp*Math.sin(a*2)); const px=Math.cos(a)*rr,py=Math.sin(a)*rr; k?x.lineTo(px,py):x.moveTo(px,py)} x.closePath(); x.strokeStyle=`hsla(${(gg.hue+l*68)%360},82%,${72-l*7}%,${.28-l*.05})`; x.lineWidth=1+l*.4; x.stroke()} for(let i=0;i<3;i++){const ang=i*TAU/3-Math.PI/2,px=Math.cos(ang)*48,py=Math.sin(ang)*48; x.fillStyle=`hsla(${[28,205,158][i]},88%,68%,.95)`; shapePath(x,shapes[i],px,py,9+i*2); x.fill()} x.restore()}
function previewSound(gg){ensureAudio().then(()=>{if(!audio)return; const t=audio.currentTime+.02, sc=[[0,2,5,7,9],[0,3,5,7,10],[0,2,4,7,9]][gg.scale%3], root=196, w=gg.law==='BYTE'?'square':gg.voice==='WOOD'?'triangle':gg.voice==='WIRE'?'sawtooth':'sine', gap=60/(gg.tempo||92)/4; [0,2,4,2].forEach((d,i)=>osc(root*Math.pow(2,sc[d%sc.length]/12),t+i*gap,.15,.026,w,(i-1.5)*.13))})}
function openBreed(){ paused=true; generation++; const grid=$('#breedGrid'); grid.innerHTML=''; const opts=buildOffspring().map(([k,i])=>({kind:k,g:mutate(k,i)})); opts.forEach((o,i)=>{const d=document.createElement('div'),cvv=document.createElement('canvas'),k=document.createElement('div'),b=document.createElement('b'),p=document.createElement('p'),acts=document.createElement('div'),aud=document.createElement('button'),ch=document.createElement('button'); d.className='offspring'; cvv.width=320; cvv.height=200; k.className='kind'; k.textContent=`${o.kind} · DESCENDANT ${'ABC'[i]}`; b.textContent=geneName(o.g); p.textContent=geneImpact(o.g,o.kind); acts.className='offActions'; aud.textContent='AUDITION'; ch.textContent=`CHOOSE ${'ABC'[i]} →`; ch.className='choose'; aud.onclick=()=>{previewSound(o.g); previewGene(cvv,o.g,performance.now())}; ch.onclick=()=>chooseOffspring(o); acts.append(aud,ch); d.append(cvv,k,b,p,acts); grid.appendChild(d); previewGene(cvv,o.g,performance.now()) }); $('#breedNote').textContent=`PINS: ${Object.entries(pins).filter(x=>x[1]).map(x=>x[0]).join(' · ')||'NONE'} · PRESSURE ${pressure.toFixed(2)}×`; $('#breed').classList.add('on'); updateHUD() }
