const lensNames=['BASE','LOCAL','SKIP','TRIAD','MIRROR']; function setToolglassFromX(x){const dx=x-toolglassStartX; toolglassIndex=clamp(Math.round(2+dx/46),0,lensNames.length-1); updateHUD()} function setToolglassFromY(y){const dy=toolglassStartY-y; toolglassScope=clamp(Math.round(lensScope+dy/42),0,8); updateHUD()} $('#glassBtn').addEventListener('pointerdown',e=>{if(!running)return; toolglassActive=true; toolglassPointerId=e.pointerId; toolglassStartX=e.clientX; toolglassStartY=e.clientY; toolglassIndex=Math.max(0,lensNames.indexOf(lensTopology)); toolglassScope=lensScope; $('#glassBtn').setPointerCapture?.(e.pointerId); updateHUD(); e.preventDefault()}); $('#glassBtn').addEventListener('pointermove',e=>{if(!toolglassActive||e.pointerId!==toolglassPointerId)return; setToolglassFromX(e.clientX); setToolglassFromY(e.clientY); if($('#lensLab').classList.contains('on')){drawLens(); renderScopeTabs();} e.preventDefault()}); function endToolglass(e){if(!toolglassActive||(e&&toolglassPointerId!=null&&e.pointerId!==toolglassPointerId))return; lensTopology=lensNames[toolglassIndex]; lensScope=toolglassScope; toolglassActive=false; toolglassPointerId=null; save(); updateHUD(); if($('#lensLab').classList.contains('on')){renderScopeTabs(); drawLens(); renderIsoRows();}} $('#glassBtn').addEventListener('pointerup',endToolglass); $('#glassBtn').addEventListener('pointercancel',endToolglass); cv.addEventListener('pointerdown',e=>{if(!running||paused)return; if(garden){garden=false; updateHUD()} drag=true; lastX=e.clientX; lastT=performance.now(); snapping=false; rotVel=0; cv.setPointerCapture?.(e.pointerId)}); cv.addEventListener('pointermove',e=>{if(!drag||paused)return; const now=performance.now(),dx=e.clientX-lastX,dt=Math.max(.008,(now-lastT)/1000),step=TAU/N; if(controlMode==='RATCHET'){const threshold=Math.max(24,W*.055); if(Math.abs(dx)>=threshold){snapTarget=Math.round(rotation/step)*step+(dx>0?step:-step); snapping=true; haptic(5); lastX=e.clientX}} else {const sens=TAU/(Math.max(W,340)*1.02); rotation+=dx*sens; rotVel=clamp(dx*sens/dt,-5,5); lastX=e.clientX} lastT=now}); cv.addEventListener('pointerup',()=>{drag=false; if(controlMode==='FLOW'){const step=TAU/N; snapTarget=Math.round(rotation/step)*step; snapping=true}}); cv.addEventListener('pointercancel',()=>{drag=false}); document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&soundOn)ensureAudio()}); addEventListener('pageshow',()=>{if(soundOn)ensureAudio()});
window.FoldBloom={state:()=>({chapter:CH[chapter]?.name||'ALIGN',generation,blooms,score,combo,pace,garden,controlMode,gene:{...gene},theme}),projection:()=>({chapter:CH[chapter]?.name||'ALIGN',law:gene.law,generation,blooms,score:Math.floor(score),combo,pace,garden,controlMode,style:theme,seed:seed?{type:seed.type,glyph:glyphs[seed.type],side:seed.side,p:+seed.p.toFixed(3),echo:!!seed.echo}:null,aligned:!!(seed&&aligned()),chain:seed?predictedChain().length:0,memory:eventTape.length,queue:[...futureQueue],lens:lensTopology,scope:lensScope,domain:lensDomain,pressure:pressureSnapshot()}),on:fn=>{sinks.add(fn);return()=>sinks.delete(fn)},step:dir=>{const step=TAU/N;snapTarget=Math.round(rotation/step)*step+(dir>0?step:-step);snapping=true;haptic(5)},setPace:v=>{pace=clamp(v,.55,1.65);updateHUD();startMusic();save()},garden:on=>{garden=!!on;updateHUD();save()},packet:()=>({schema:'foldbloom.return.v9',state:{score,blooms,chapter:CH[chapter].name,generation,bestChain,misses,bestCombo},gene,pins,pressure,theme,eventTape,lineage,discoveries:[...discoveries],lawStats,lensTopology,lensScope,lensDomain,activeOperator,receipts}),style:()=>({current:theme,available:Object.keys(THEMES)}),laws:()=>({available:LAWSET,current:gene.law,evidence:JSON.parse(JSON.stringify(lawStats))}),lineage:()=>lineage.map(r=>({gen:r.gen,name:r.name,gene:{...r.gene}}))};
load(); initBoard(); ensureQueue(); studioBridge(); applyTheme(theme); updateHUD(); renderStyleCards(); renderAnalytics();
if(new URLSearchParams(location.search).get('test')==='1'){
  setTimeout(()=>{
    try{
      begin('FLOW',false);
      setPaused(true);
      $('#cultivateBtn').click(); togglePin('BODY'); $('#cultivateClose').click();
      $('#analyticsBtn').click(); mapMode='SCALE'; renderAnalytics(); $('#analyticsClose').click();
      $('#lensBtn').click(); lensTopology='SKIP'; lensDomain='ATLAS'; lensScope=4; renderLensTabs(); renderScopeTabs(); renderDomainTabs(); drawLens();
      if(!$('#forecastBook').children.length||!$('#isoRows').children.length||!$('#operatorTabs').children.length)throw Error('lens rows empty'); addReceipt('✓','test','ok'); $('#glassBtn').dispatchEvent(new PointerEvent('pointerdown',{pointerId:9,clientX:100,clientY:180})); $('#glassBtn').dispatchEvent(new PointerEvent('pointermove',{pointerId:9,clientX:180,clientY:100})); $('#glassBtn').dispatchEvent(new PointerEvent('pointerup',{pointerId:9,clientX:180,clientY:100})); if(!$('#pressureHUD').textContent||!$('#scopeHUD').textContent)throw Error('scope hud');
      const sp=decodeSpore(makeSpore()); if(!sp?.g)throw Error('spore roundtrip');
      $('#lensBack').click(); setPaused(false);
      document.documentElement.dataset.fbTest='pass';
    }catch(e){document.documentElement.dataset.fbTest='fail';document.documentElement.dataset.fbError=String(e?.message||e)}
  },120);
}

