
'use strict';const $=s=>document.querySelector(s),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));const DOMAINS={TEXT:['LETTER','WORD','PHRASE','SENTENCE','PARAGRAPH','SECTION','CHAPTER','BOOK','LIBRARY'],ATLAS:['PULSE','TASK','ROUTE','SESSION','DAY','WEEK','PROJECT','PROGRAM','FEDERATION'],DAYLINE:['MOMENT','ACTION','BLOCK','ARC','DAY','WEEK','CYCLE','SEASON','HISTORY'],DATADISC:['CELL','FIELD','ROW','RECORD','TABLE','DATASET','CORPUS','WAREHOUSE','ECOSYSTEM'],OBJECT:['TRACE','FEATURE','PART','COMPONENT','MODULE','ASSEMBLY','MACHINE','LINE','FLEET']};
const WINDOWS=[1,2,4,8,16,32,64,128,256],OPS=[['⊙','SELECT'],['↔','ALIGN'],['⊗','COMPOSE'],['⇢','PROPAGATE'],['✓','COMMIT'],['↩','RETURN']];let atoms=[],domain='DATADISC',scope=3,activeOp='⊙',selected=0,receipts=[],displayScope=3,targetScope=3,anim=0;const cv=$('#cv'),g=cv.getContext('2d');
function hash(s){let h=2166136261;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function atom(label,value,raw,i){return{id:'a'+i,label:String(label??'').slice(0,80)||('item '+i),value:String(value??'').slice(0,120),raw,hash:hash(JSON.stringify(raw??label))}}
function csv(t){const lines=t.trim().split(/\r?\n/).filter(Boolean),head=(lines.shift()||'').split(',').map(x=>x.trim());return lines.map((ln,i)=>{const vals=ln.split(',');const o={};head.forEach((h,j)=>o[h||('f'+j)]=vals[j]?.trim()??'');return o})}
function parse(t,name='pasted'){let data;const s=t.trim();if(!s)return[];try{data=JSON.parse(s)}catch(_){if(s.includes(',')&&s.includes('\n'))data=csv(s);else data=s.split(/\n{2,}|(?<=[.!?])\s+/).filter(Boolean)}let arr=Array.isArray(data)?data:(typeof data==='object'?[...Object.entries(data).map(([k,v])=>({key:k,value:v}))]:[data]);return arr.map((r,i)=>{if(typeof r==='object'){const entries=Object.entries(r), lab=entries[0]?.[1]??entries[0]?.[0]??('row '+i), val=entries.slice(1,4).map(([k,v])=>k+': '+String(v)).join(' · ');return atom(lab,val,r,i)}return atom(String(r).slice(0,80),'',r,i)})}
function receipt(op,subject,result=''){receipts.push({at:new Date().toISOString(),op,domain,scope:DOMAINS[domain][scope],subject,result});if(receipts.length>40)receipts.shift();renderReceipts()}
function groups(level=scope){const n=WINDOWS[level],out=[];for(let i=0;i<atoms.length;i+=n){const items=atoms.slice(i,i+n);if(!items.length)continue;out.push({start:i,end:i+items.length-1,items,label:items[0].label,count:items.length,hash:items.reduce((q,a)=>q^a.hash,0)>>>0})}return out}
function renderOps(){const b=$('#ops');b.innerHTML='';OPS.forEach(([s,n])=>{const x=document.createElement('button');x.textContent=s+' '+n;x.classList.toggle('on',activeOp===s);x.onclick=()=>{activeOp=s;receipt(s,'operator',n);
renderOps();draw()};b.appendChild(x)})}
function renderDomains(){const b=$('#domains');b.innerHTML='';Object.keys(DOMAINS).forEach(d=>{const x=document.createElement('button');x.textContent=d;x.classList.toggle('on',domain===d);x.onclick=()=>{domain=d;receipt('↔','domain',d);renderDomains();renderScopes();renderIso();draw()};b.appendChild(x)})}
function renderScopes(){const b=$('#scopes');b.innerHTML='';DOMAINS[domain].forEach((n,i)=>{const x=document.createElement('button');x.textContent=n;x.classList.toggle('on',scope===i);x.onclick=()=>setScope(i);b.appendChild(x)})}
function setScope(i){i=clamp(i,0,8);if(i===scope)return;scope=i;targetScope=i;receipt('⇢','scope',DOMAINS[domain][i]);renderScopes();renderIso();renderSpec();anim=1}
function renderIso(){const b=$('#iso');b.innerHTML='';Object.keys(DOMAINS).forEach(d=>{const x=document.createElement('div');x.innerHTML='<b>'+d+'</b>'+DOMAINS[d][scope]+'<br><span>window ×'+WINDOWS[scope]+'</span>';b.appendChild(x)})}
function renderMetrics(){const b=$('#metrics');b.innerHTML='';[['atoms',atoms.length],['groups',groups().length],['window','×'+WINDOWS[scope]],['scope',DOMAINS[domain][scope]]].forEach(([k,v])=>{const x=document.createElement('div');x.innerHTML=k+'<b>'+v+'</b>';b.appendChild(x)})}
function renderSpec(){const a=atoms[selected];const b=$('#spec');if(!a){b.textContent='Import data or load the sample.';return}const n=WINDOWS[scope],parent=Math.floor(selected/n),lo=Math.max(0,parent*n),hi=Math.min(atoms.length-1,lo+n-1);b.innerHTML='<div class=row><span>id</span><b>'+a.id+'</b></div><div class=row><span>label</span><b>'+esc(a.label)+'</b></div><div class=row><span>value</span><b>'+esc(a.value||'—')+'</b></div><div class=row><span>scope</span><b>'+DOMAINS[domain][scope]+' ×'+n+'</b></div><div class=row><span>parent</span><b>group '+parent+' · atoms '+lo+'–'+hi+'</b></div><div class=row><span>operator</span><b>'+activeOp+'</b></div>'}
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function renderReceipts(){const b=$('#receipts');b.innerHTML='';receipts.slice(-12).reverse().forEach(r=>{const d=document.createElement('div');d.className='receipt';d.innerHTML='<b>'+r.op+'</b><span>'+r.scope+'</span><span>'+r.domain+'</span><span>'+esc(r.subject)+' '+esc(r.result)+'</span>';b.appendChild(d)})}
function drawLevel(level,alpha){const gs=groups(level),w=cv.width,h=cv.height,cx=w/2,cy=h/2,r=Math.min(w,h)*.32;g.save();g.globalAlpha=alpha;gs.slice(0,160).forEach((gr,i)=>{const a=-Math.PI/2+i/Math.max(1,gs.length)*Math.PI*2,rr=r+(gr.hash%31)-15,x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr,rad=4+Math.log2(gr.count+1)*3;g.fillStyle='hsla('+(gr.hash%360)+',72%,68%,.75)';g.beginPath();g.arc(x,y,rad,0,Math.PI*2);g.fill();if(i===Math.floor(selected/WINDOWS[level])){g.strokeStyle='#fff';g.lineWidth=2;g.beginPath();g.arc(x,y,rad+6,0,Math.PI*2);g.stroke()}});g.restore()}
function draw(){g.fillStyle='#05070b';g.fillRect(0,0,cv.width,cv.height);displayScope+=(targetScope-displayScope)*.14;const lo=Math.floor(displayScope),hi=Math.min(8,lo+1),f=displayScope-lo;drawLevel(lo,1-f);if(hi!==lo)drawLevel(hi,f);g.fillStyle='rgba(255,255,255,.85)';g.textAlign='center';g.font='15px ui-monospace';g.fillText(activeOp+'  '+DOMAINS[domain][scope]+'  ×'+WINDOWS[scope],cv.width/2,cv.height/2);g.fillStyle='rgba(255,255,255,.38)';g.font='11px ui-monospace';g.fillText('pinch / wheel / vertical drag = nested scope',cv.width/2,cv.height/2+22);$('#hud').textContent=domain+' · '+atoms.length+' atoms · '+groups().length+' groups';requestAnimationFrame(draw)}
function loadAtoms(a,name='data'){atoms=a;selected=0;receipt('⊙','import',name+' · '+a.length+' atoms');renderMetrics();renderSpec();renderIso()}
