'use strict';
(()=>{
const DATADISC_SCOPE={CELL:0,FIELD:1,ROW:2,RECORD:3,TABLE:4,DATASET:5};
const esc11=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const focusNode11=()=>{const a=atoms[selected];if(!a||!graph10)return null;if(domain!=='DATADISC')return a;const chain=ScaleSchema.ancestry(graph10,a.id).map(id=>nodeMap10.get(id)).filter(Boolean);const want=['CELL','FIELD','ROW','RECORD','TABLE','DATASET','DATASET','DATASET','DATASET'][scope];return chain.find(n=>n.kind===want)||chain[chain.length-1]||a};
const firstLeaf11=id=>{const n=nodeMap10.get(id);if(!n)return null;if(graph10.leafIds.includes(id))return id;const q=[...(n.childrenIds||[])],seen=new Set();while(q.length){const x=q.shift();if(seen.has(x))continue;seen.add(x);if(graph10.leafIds.includes(x))return x;const c=nodeMap10.get(x);if(c?.childrenIds?.length)q.push(...c.childrenIds)}return null};
function state11(){return{domain,scope,activeOp,selectedId:atoms[selected]?.id||null,sourceId:graph10?.source?.id||null,hasGraph:!!graph10}}
function commitNav11(subject,fn,result=''){const before=state11();fn();const after=state11();const r=receipt('⊙',subject,result,before,after,{kind:'STATE',state:before});undoStack10.push(r.id);syncHash11();renderAddress11();renderSpec();renderIso();renderMetrics()}
function jumpNode11(id,subject='jump'){if(!graph10||!id)return false;const n=nodeMap10.get(id);if(!n)return false;const leaf=firstLeaf11(id)||id,idx=atoms.findIndex(a=>a.id===leaf);if(idx<0)return false;commitNav11(subject,()=>{selected=idx;if(domain==='DATADISC'&&DATADISC_SCOPE[n.kind]!=null){scope=DATADISC_SCOPE[n.kind];targetScope=scope;renderScopes()}},n.kind+' '+n.label);return true}
function moveGroup11(delta){const gs=groups(),gr=group10(),i=gs.findIndex(x=>x.id===gr?.id);if(i<0)return;const nx=gs[clamp(i+delta,0,gs.length-1)];if(!nx||nx===gr)return;commitNav11(delta<0?'previous sibling':'next sibling',()=>{selected=nx.start},nx.label)}
function changeScope11(delta){const next=clamp(scope+delta,0,8);if(next===scope)return;const before=state11();scope=next;targetScope=next;renderScopes();const after=state11();const r=receipt('⇢',delta<0?'dive':'rise',DOMAINS[domain][scope],before,after,{kind:'STATE',state:before});undoStack10.push(r.id);syncHash11();renderAddress11();renderSpec();renderIso();renderMetrics()}
function project11(d){if(!DOMAINS[d]||d===domain)return;const before=state11();domain=d;renderDomains();renderScopes();const after=state11();const r=receipt('↔','project anchor',d,before,after,{kind:'STATE',state:before});undoStack10.push(r.id);syncHash11();renderAddress11();renderSpec();renderIso();renderMetrics()}
function hashState11(){const a=atoms[selected];if(!a)return'';const q=new URLSearchParams({focus:a.id,domain,scope:String(scope)});return'#'+q.toString()}
function syncHash11(){try{history.replaceState(null,'',location.pathname+location.search+hashState11())}catch(_){}}
function applyHash11(){if(!location.hash||!graph10)return;const q=new URLSearchParams(location.hash.slice(1)),id=q.get('focus'),d=q.get('domain'),s=Number(q.get('scope'));if(id){const idx=atoms.findIndex(a=>a.id===id);if(idx>=0)selected=idx}if(d&&DOMAINS[d])domain=d;if(Number.isFinite(s))scope=targetScope=clamp(s,0,8);renderDomains();renderScopes();renderAddress11();renderSpec();renderIso();renderMetrics()}
function breadcrumb11(){const a=atoms[selected];if(!a||!graph10)return[];if(domain==='DATADISC')return ScaleSchema.ancestry(graph10,a.id).map(id=>nodeMap10.get(id)).filter(Boolean).reverse();return DOMAINS[domain].map((label,i)=>({id:'scope:'+i,kind:label,label,scope:i})).reverse()}
function provenancePreview11(){const a=atoms[selected],src=graph10?.source?.originalText||'';if(!a||!src)return'No source text retained.';const p=a.provenance||{};if(p.offsetStart!=null){const lo=Math.max(0,p.offsetStart-90),hi=Math.min(src.length,(p.offsetEnd??p.offsetStart)+90);return src.slice(lo,hi)}if(p.row!=null){const lines=src.split(/\r?\n/);return lines.slice(Math.max(0,p.row-2),Math.min(lines.length,p.row+1)).join('\n')}if(p.pointer)return `${p.pointer}\n\n${JSON.stringify(a.value,null,2)}`;return String(a.value??a.label??'—')}
function relationTargets11(n){const out=[];(n?.relations||[]).forEach(r=>{const t=nodeMap10.get(r.target);if(t)out.push({kind:r.kind,node:t})});if(n?.parentId&&nodeMap10.get(n.parentId))out.unshift({kind:'parent',node:nodeMap10.get(n.parentId)});const p=n?.parentId?nodeMap10.get(n.parentId):null;if(p?.childrenIds?.length){for(const id of p.childrenIds){if(id===n.id)continue;const t=nodeMap10.get(id);if(t)out.push({kind:'sibling',node:t});if(out.length>10)break}}return out}
function search11(q){q=String(q||'').trim().toLowerCase();if(!q||!graph10)return[];let exact=q.match(/\/object\/([^/?#]+)/)?.[1]||q.match(/^obj_[a-z0-9_]+$/i)?.[0];if(exact&&nodeMap10.has(exact))return[nodeMap10.get(exact)];return graph10.nodes.filter(n=>n.id.toLowerCase().includes(q)||String(n.label||'').toLowerCase().includes(q)||String(n.value??'').toLowerCase().includes(q)||String(n.provenance?.pointer||'').toLowerCase().includes(q)).slice(0,10)}
function renderSearchResults11(items){const b=document.querySelector('#addrResults');if(!b)return;b.innerHTML='';items.forEach(n=>{const x=document.createElement('button');x.className='addrResult';x.innerHTML=`<b>${esc11(n.kind)}</b><span>${esc11(n.label)}</span><small>${esc11(n.id)}</small>`;x.onclick=()=>jumpNode11(n.id,'address search');b.appendChild(x)})}
function renderAddress11(){const box=document.querySelector('#addressNav');if(!box)return;const a=atoms[selected],n=focusNode11();if(!a||!graph10){box.querySelector('#addrCrumbs').textContent='No addressed object yet.';return}const addr=addr10(a),crumbs=breadcrumb11(),cb=box.querySelector('#addrCrumbs');cb.innerHTML='';crumbs.forEach((c,i)=>{const x=document.createElement('button');x.className='crumb'+((c.id===n?.id||c.scope===scope)?' on':'');x.textContent=c.kind||c.label;x.title=c.label||c.kind;x.onclick=()=>{if(c.id?.startsWith('scope:'))changeScope11(c.scope-scope);else jumpNode11(c.id,'breadcrumb')};cb.appendChild(x);if(i<crumbs.length-1){const s=document.createElement('span');s.textContent='›';cb.appendChild(s)}});box.querySelector('#addrCanonical').textContent=a.id;box.querySelector('#addrProjection').textContent=addr.projection;box.querySelector('#addrRange').textContent=addr.range;const rail=box.querySelector('#projectionRail');rail.innerHTML='';Object.keys(DOMAINS).forEach(d=>{const x=document.createElement('button');x.className=d===domain?'on':'';x.innerHTML=`<b>${d}</b><span>${DOMAINS[d][scope]}</span>`;x.onclick=()=>project11(d);rail.appendChild(x)});const rel=box.querySelector('#relationRail');rel.innerHTML='';relationTargets11(n).slice(0,9).forEach(r=>{const x=document.createElement('button');x.innerHTML=`<b>${esc11(r.kind)}</b><span>${esc11(r.node.kind)} · ${esc11(r.node.label)}</span>`;x.onclick=()=>jumpNode11(r.node.id,'relation '+r.kind);rel.appendChild(x)});if(!rel.children.length)rel.textContent='No local relation targets.';box.querySelector('#sourcePreview').textContent=provenancePreview11()}
function inject11(){const anchor=document.querySelector('#domains')?.closest('.panel');if(!anchor||document.querySelector('#addressNav'))return;const box=document.createElement('div');box.id='addressNav';box.className='panel addressNav';box.innerHTML=`<div class="topline"><div><div class="mut">ADDRESS / TRAVERSE / PROJECT</div><b>Stable focus across zoom</b></div><div class="navBtns"><button id="navRise">↑ RISE</button><button id="navDive">↓ DIVE</button><button id="navPrev">← PREV</button><button id="navNext">NEXT →</button></div></div><div id="addrCrumbs" class="breadcrumbs"></div><div class="addressSearch"><input id="addrQuery" placeholder="jump by object id, address, label, value, JSON pointer…"><button id="addrJump">JUMP</button><button id="addrCopy">COPY FOCUS</button></div><div id="addrResults" class="addrResults"></div><div class="addrTriplet"><div><span>CANONICAL</span><code id="addrCanonical"></code></div><div><span>PROJECTION</span><code id="addrProjection"></code></div><div><span>RANGE</span><code id="addrRange"></code></div></div><div class="mut">SAME ANCHOR / OTHER PROJECTIONS</div><div id="projectionRail" class="projectionRail"></div><div class="addrSplit"><div><div class="mut">RELATION CONTEXT</div><div id="relationRail" class="relationRail"></div></div><div><div class="mut">SOURCE WINDOW / PROVENANCE</div><pre id="sourcePreview" class="sourcePreview"></pre></div></div>`;anchor.after(box);box.querySelector('#navRise').onclick=()=>changeScope11(1);box.querySelector('#navDive').onclick=()=>changeScope11(-1);box.querySelector('#navPrev').onclick=()=>moveGroup11(-1);box.querySelector('#navNext').onclick=()=>moveGroup11(1);const q=box.querySelector('#addrQuery');q.oninput=()=>renderSearchResults11(search11(q.value));q.onkeydown=e=>{if(e.key==='Enter'){const r=search11(q.value);if(r[0])jumpNode11(r[0].id,'address jump')}};box.querySelector('#addrJump').onclick=()=>{const r=search11(q.value);if(r[0])jumpNode11(r[0].id,'address jump')};box.querySelector('#addrCopy').onclick=async()=>{const a=atoms[selected];if(!a)return;const addr=addr10(a),txt=`${a.id}\n${addr.projection}\n${location.origin+location.pathname+hashState11()}`;try{await navigator.clipboard.writeText(txt);box.querySelector('#addrCopy').textContent='COPIED';setTimeout(()=>box.querySelector('#addrCopy').textContent='COPY FOCUS',700)}catch(_){prompt('Copy focus address:',txt)}}}
const renderSpec10_11=renderSpec;renderSpec=function(){renderSpec10_11();renderAddress11()};const loadGraph10_11=loadGraph10;loadGraph10=function(gr,name='data'){loadGraph10_11(gr,name);setTimeout(()=>{applyHash11();renderAddress11()},0)};const renderIso10_11=renderIso;renderIso=function(){renderIso10_11();renderAddress11()};inject11();setTimeout(()=>{applyHash11();renderAddress11()},0);addEventListener('hashchange',applyHash11);
})();
