'use strict';
let graph10=null,nodeMap10=new Map(),undoStack10=[],receiptSeq10=0,sourceRegistry10={};
const oldDraw=draw;
function graphAtoms(){return graph10?ScaleSchema.leafAtoms(graph10):[]}
function state10(){return{domain,scope,activeOp,selectedId:atoms[selected]?.id||null,sourceId:graph10?.source?.id||null,hasGraph:!!graph10}}
function applyState10(st){if(!st)return;if(st.hasGraph===false){graph10=null;atoms=[];nodeMap10=new Map();selected=0}else if(st.sourceId&&sourceRegistry10[st.sourceId]&&(!graph10||graph10.source.id!==st.sourceId)){graph10=ScaleSchema.parseSource(sourceRegistry10[st.sourceId].text,sourceRegistry10[st.sourceId].name);nodeMap10=ScaleSchema.index(graph10);atoms=graphAtoms()}domain=st.domain||domain;scope=clamp(st.scope??scope,0,8);targetScope=scope;activeOp=st.activeOp||activeOp;if(st.selectedId){const i=atoms.findIndex(a=>a.id===st.selectedId);if(i>=0)selected=i}renderOps();renderDomains();renderScopes();renderIso();renderMetrics();renderSpec();renderSchema10();renderReceipts()}
receipt=function(op,subject,result='',before=null,after=null,inverse=null){const r={id:'r'+(++receiptSeq10),at:new Date().toISOString(),op,domain,scope:DOMAINS[domain][scope],subject,result,before:before||state10(),after:after||state10(),inverse:inverse||{kind:'STATE',state:before||state10()},returned:false};receipts.push(r);if(receipts.length>80)receipts.shift();const a=atoms[selected];if(a&&!a.history.includes(r.id))a.history.push(r.id);renderReceipts();return r};
function transact10(op,subject,fn,resultFn=()=>'',inverseKind='STATE'){const before=state10();fn();const after=state10();const r=receipt(op,subject,resultFn(),before,after,{kind:inverseKind,state:before});undoStack10.push(r.id);return r}
function anc10(a,level){if(!graph10||!a||domain!=='DATADISC')return null;const chain=ScaleSchema.ancestry(graph10,a.id).map(id=>nodeMap10.get(id)).filter(Boolean),want=['CELL','FIELD','ROW','RECORD','TABLE','DATASET','DATASET','DATASET','DATASET'][level];return chain.find(n=>n.kind===want)||chain[chain.length-1]||a}
groups=function(level=scope){if(!atoms.length)return[];if(domain==='DATADISC'){const seen=new Map();atoms.forEach((a,i)=>{const n=anc10(a,level),key=n?.id||a.id;if(!seen.has(key))seen.set(key,{id:key,start:i,end:i,items:[],label:n?.label||a.label,count:0,hash:n?.hash||a.hash,node:n});const q=seen.get(key);q.end=i;q.items.push(a);q.count++});return[...seen.values()]}const n=WINDOWS[level],out=[];for(let i=0;i<atoms.length;i+=n){const items=atoms.slice(i,i+n);if(!items.length)continue;out.push({id:`rng_${graph10?.source.id||'none'}_${i}_${i+items.length-1}`,start:i,end:i+items.length-1,items,label:items[0].label,count:items.length,hash:items.reduce((q,a)=>q^a.hash,0)>>>0})}return out};
function group10(){return groups().find(gr=>selected>=gr.start&&selected<=gr.end)||groups()[0]}
function addr10(a){const gr=group10()||{start:selected,end:selected};return ScaleSchema.projectionAddress(graph10,a,domain,DOMAINS[domain][scope],gr.start,gr.end)}
renderSpec=function(){const a=atoms[selected],b=$('#spec');if(!a||!graph10){b.textContent='Import data or load the sample.';return}const addr=addr10(a),gr=group10(),anc=ScaleSchema.ancestry(graph10,a.id).map(id=>nodeMap10.get(id)).filter(Boolean);const rel=(a.relations||[]).slice(0,8).map(r=>`${r.kind} → ${r.target}`).join('<br>')||'—',hist=(a.history||[]).slice(-6).map(id=>receipts.find(r=>r.id===id)).filter(Boolean).map(r=>`${r.id} ${r.op} ${esc(r.subject)}`).join('<br>')||'—',prov=Object.entries(a.provenance||{}).filter(([k,v])=>v!=null&&k!=='name').map(([k,v])=>`${k}: ${esc(typeof v==='object'?JSON.stringify(v):v)}`).join('<br>');b.innerHTML=`<div class=row><span>canonical id</span><b class=addr>${esc(a.id)}</b></div><div class=row><span>projection</span><b class=addr>${esc(addr.projection)}</b></div><div class=row><span>range</span><b class=addr>${esc(addr.range)}</b></div><div class=row><span>type</span><b>${esc(a.type)} · ${esc(a.kind)}</b></div><div class=row><span>value</span><b>${esc(a.value??'—')}</b></div><div class=row><span>parent range</span><b>${gr?gr.start+'–'+gr.end:'—'} · ${esc(gr?.label||'—')}</b></div><div class=row><span>ancestry</span><b class=addr>${anc.map(n=>n.kind+':'+n.id).join(' → ')}</b></div><div class=row><span>relations</span><b class=addr>${rel}</b></div><div class=row><span>provenance</span><b class="addr prov">${prov}</b></div><div class=row><span>history</span><b class="addr history">${hist}</b></div>`};
renderMetrics=function(){const b=$('#metrics'),fields=graph10?.schema?.tables?.reduce((q,t)=>q+(t.fields?.length||0),0)||0;b.innerHTML='';[['atoms',atoms.length],['nodes',graph10?.nodes?.length||0],['groups',groups().length],['fields',fields],['format',graph10?.source?.format||'—'],['scope',DOMAINS[domain][scope]]].forEach(([k,v])=>{const x=document.createElement('div');x.innerHTML=k+'<b>'+v+'</b>';b.appendChild(x)})};
renderIso=function(){const b=$('#iso');b.innerHTML='';Object.keys(DOMAINS).forEach(d=>{const x=document.createElement('div');x.innerHTML='<b>'+d+'</b>'+DOMAINS[d][scope]+'<br><span>anchor '+esc(atoms[selected]?.id||'—')+'</span>';b.appendChild(x)})};
renderReceipts=function(){const b=$('#receipts');b.innerHTML='';receipts.slice(-16).reverse().forEach(r=>{const d=document.createElement('div');d.className='receipt'+(r.returned?' returned':'');d.innerHTML='<b>'+r.op+'</b><span>'+esc(r.scope)+'</span><span>'+esc(r.domain)+'</span><span>'+esc(r.subject)+' '+esc(r.result)+'</span>';b.appendChild(d)})};
function renderSchema10(){const b=$('#schema');if(!b)return;if(!graph10){b.textContent='—';return}let h=`<div class=row><span>source</span><b class=addr>${esc(graph10.source.id)} · ${esc(graph10.source.name)}</b></div><div class=row><span>format</span><b>${esc(graph10.source.format)} · ${graph10.source.size} bytes · ${esc(graph10.source.contentHash)}</b></div>`;for(const t of graph10.schema.tables||[]){h+=`<div class=section><b>${esc(t.label)}</b> <span class=tag>${t.recordCount} records</span>${t.keyField?`<span class=tag>key ${esc(t.keyField)}</span>`:''}<div class=schemaTable><b>FIELD</b><b>TYPE</b><b>CONF</b><b>NULL</b>`;for(const f of t.fields||[])h+=`<span>${esc(f.name)}${f.keyCandidate?' ★':''}</span><span>${esc(f.type)}</span><span>${Math.round((f.confidence||0)*100)}%</span><span>${Math.round((f.nullRate||0)*100)}%</span>`;h+='</div></div>'}b.innerHTML=h}
function loadGraph10(gr,name='data'){const before=state10();if(graph10)sourceRegistry10[graph10.source.id]={text:graph10.source.originalText,name:graph10.source.name};graph10=gr;sourceRegistry10[gr.source.id]={text:gr.source.originalText,name:gr.source.name};nodeMap10=ScaleSchema.index(gr);atoms=graphAtoms();selected=0;domain=gr.source.format==='text'?'TEXT':'DATADISC';scope=gr.source.format==='text'?1:3;targetScope=scope;renderOps();renderDomains();renderScopes();renderIso();renderMetrics();renderSpec();renderSchema10();const after=state10(),r=receipt('⊙','parse',`${name} · ${atoms.length} typed atoms · ${gr.schema.tables.length} tables`,before,after,{kind:'STATE',state:before});undoStack10.push(r.id)}
setScope=function(i){i=clamp(i,0,8);if(i===scope)return;transact10('⇢','scope',()=>{scope=i;targetScope=i;renderScopes();renderIso();renderSpec();renderMetrics()},()=>DOMAINS[domain][i])};
renderOps=function(){const b=$('#ops');b.innerHTML='';OPS.forEach(([s,n])=>{const x=document.createElement('button');x.textContent=s+' '+n;x.classList.toggle('on',activeOp===s);x.onclick=()=>transact10(s,'operator',()=>{activeOp=s;renderOps()},()=>n);b.appendChild(x)})};
renderDomains=function(){const b=$('#domains');b.innerHTML='';Object.keys(DOMAINS).forEach(d=>{const x=document.createElement('button');x.textContent=d;x.classList.toggle('on',domain===d);x.onclick=()=>transact10('↔','domain',()=>{domain=d;renderDomains();renderScopes();renderIso();renderSpec();renderMetrics()},()=>d);b.appendChild(x)})};
function parse10(text,name){try{return ScaleSchema.parseSource(text,name)}catch(e){alert('Parse failed: '+e.message);return null}}
$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;const t=await f.text();$('#text').value=t.slice(0,250000);const gr=parse10(t,f.name);if(gr)loadGraph10(gr,f.name)};
$('#parseText').onclick=()=>{const gr=parse10($('#text').value,'pasted');if(gr)loadGraph10(gr,'pasted')};
$('#sample').onclick=()=>{const sample=Array.from({length:18},(_,i)=>({id:'evt-'+String(i+1).padStart(3,'0'),time:`${String(8+Math.floor(i/4)).padStart(2,'0')}:${String((i%4)*15).padStart(2,'0')}:00`,kind:['observe','make','test','return'][i%4],project:['house','code','cats'][i%3],value:(i*7)%13,ok:i%5!==0}));$('#text').value=JSON.stringify({session:'dayline-demo',events:sample,meta:{timezone:'Asia/Singapore',version:2}},null,2);const gr=parse10($('#text').value,'dayline-sample.json');if(gr)loadGraph10(gr,'dayline sample')};
$('#drop').addEventListener('dragover',e=>{e.preventDefault()});$('#drop').addEventListener('drop',async e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(!f)return;const t=await f.text();$('#text').value=t.slice(0,250000);const gr=parse10(t,f.name);if(gr)loadGraph10(gr,f.name)});
$('#send').onclick=()=>{if(!graph10||!atoms.length)return;const packet={schema:'scale-lens.packet.v2',at:new Date().toISOString(),source:{...graph10.source,originalText:undefined},schemaModel:graph10.schema,domain,scope,operator:activeOp,focus:addr10(atoms[selected]),items:atoms.slice(0,128).map((a,i)=>({id:a.id,label:a.label,value:a.value,type:a.type,kind:a.kind,hash:a.hash,address:ScaleSchema.projectionAddress(graph10,a,domain,DOMAINS[domain][scope],i,i),provenance:a.provenance,relations:a.relations,history:a.history})),receipts:receipts.slice(-24)};localStorage.setItem('fb-lens-studio-packet',JSON.stringify(packet));receipt('↩','field',packet.items.length+' addressed atoms');location.href='index.html#studio'};
$('#export').onclick=()=>{if(!graph10)return;const packet={schema:'scale-lens.return.v2',at:new Date().toISOString(),source:graph10.source,schemaModel:graph10.schema,nodes:graph10.nodes,leafIds:graph10.leafIds,domain,scope,operator:activeOp,focus:addr10(atoms[selected]),receipts,sourceRegistry:sourceRegistry10};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(packet,null,2)],{type:'application/json'}));a.download='scale-lens-addressed-return-v2.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);receipt('↩','export','reversible addressed packet')};
$('#undo').onclick=()=>{let r=null;while(undoStack10.length&&!r){const id=undoStack10.pop(),q=receipts.find(x=>x.id===id);if(q&&!q.returned)r=q}if(!r)return;const cur=state10();applyState10(r.inverse?.state);r.returned=true;receipt('↩','return receipt',r.id,cur,state10(),{kind:'STATE',state:cur});renderReceipts()};
cv.addEventListener('click',e=>{if(!atoms.length)return;e.stopImmediatePropagation();const rect=cv.getBoundingClientRect(),x=(e.clientX-rect.left)*cv.width/rect.width,y=(e.clientY-rect.top)*cv.height/rect.height,gs=groups(),cx=cv.width/2,cy=cv.height/2,r=Math.min(cv.width,cv.height)*.32;let best=0,bd=1e9;gs.forEach((gr,i)=>{const a=-Math.PI/2+i/Math.max(1,gs.length)*Math.PI*2,rr=r+(gr.hash%31)-15,gx=cx+Math.cos(a)*rr,gy=cy+Math.sin(a)*rr,d=(gx-x)**2+(gy-y)**2;if(d<bd){bd=d;best=i}});const before=state10();selected=Math.min(atoms.length-1,gs[best]?.start||0);const rr=receipt('⊙','select',atoms[selected].id,before,state10(),{kind:'STATE',state:before});undoStack10.push(rr.id);renderSpec();renderIso()},{capture:true});
$('#fieldBtn').onclick=()=>location.href='index.html';
let dragY10=null,startScope10=0;
cv.addEventListener('pointerdown',e=>{dragY10=e.clientY;startScope10=scope;cv.setPointerCapture?.(e.pointerId)});
cv.addEventListener('pointermove',e=>{if(dragY10==null)return;const d=dragY10-e.clientY,set=clamp(Math.round(startScope10+d/42),0,8);if(set!==scope){scope=set;targetScope=set;renderScopes();renderIso();renderMetrics();renderSpec()}});
cv.addEventListener('pointerup',()=>{if(dragY10!=null){const before={...state10(),scope:startScope10};const after=state10(),r=receipt('⇢','scope drag',DOMAINS[domain][scope],before,after,{kind:'STATE',state:before});undoStack10.push(r.id);dragY10=null}});
cv.addEventListener('wheel',e=>{e.preventDefault();setScope(scope+(e.deltaY>0?1:-1))},{passive:false});
let pinch10=null;cv.addEventListener('touchstart',e=>{if(e.touches.length===2)pinch10=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)},{passive:true});cv.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinch10){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(Math.abs(d-pinch10)>30){setScope(scope+(d>pinch10?-1:1));pinch10=d}}},{passive:true});
renderOps();renderDomains();renderScopes();renderIso();renderMetrics();renderSpec();renderSchema10();renderReceipts();$('#sample').click();draw();