/* clocks.js — THE CLOCKS: APAC instruments that carry dates. Folded in 2026-10-06 from
 * rulemap-expanded.json (9 jurisdictions, 21 instruments, sources fetched same day; 6 claims
 * flagged unverified in the runbook and shown as such). One reveal, no chrome, no tracking. */
(function(){
 var RULES=[
{j:'Indonesia',i:'UU No. 27/2022 tentang Pelindungan Data Pribadi (PDP Law)',d:'2022-10-17 (fully binding 2024-10-17)',s:'In force; transition ended 17 Oct 2024; supervisory authority (Badan PDP) NOT yet established; admin fine cap 2% annual revenue',b:'Controllers/processors of Indonesian personal data incl. foreign big tech; criminal + corporate liability (10x fines)',a:'Map all ID-data processing to a lawful basis and stand up breach-notice + transfer docs despite the regulator gap',u:'https://www.dlapiperdataprotection.com/index.html?t=enforcement&c=ID'},
{j:'Indonesia',i:'SE Menkominfo No. 9/2023 tentang Etika Kecerdasan Artifisial (Kominfo Circular 9/2023 on AI Ethics)',d:'2023-12-19',s:'In force but soft law, no sanctions; reconfirmed as current standard 27 Aug 2026; Perpres replacements unsigned',b:'All public/private PSEs incl. foreign — in-house AI ethics policies (inclusivity, humanity, security, transparency, data protection)',a:'Keep a documented in-house AI ethics policy mapped to the 9 circular values; watch the AI Perpres',u:'https://aiinasia.com/policy/indonesia-aiia-asia-policy-atlas-september-2026'},
{j:'Indonesia',i:'Draft Perpres: National AI Roadmap 2026-2029 + AI Ethics/Safety framework (programmed in Perpres 38/2025)',d:'drafts since Aug 2025 consultation; unsigned',s:'DRAFT — unsigned as of late Sep 2026; risk-tiered; first derivative rule will mandate AI-content labelling/watermarking; Perpres to carry no sanctions of its own',b:'Would bind all AI providers in Indonesia; foreign firms commented (US Chamber, US-ABC)',a:'Perpres-watch: one named owner; pre-build watermarking/labelling for ID-facing generative outputs',u:'https://anuragverma.co/worldwatch/indonesia/ai'},
{j:'Indonesia',i:'PP No. 17/2025 (PP Tunas) + Permenkomdigi No. 9/2026 (child protection in electronic systems)',d:'2025-03-27 (enforced 2026-03-28)',s:'In force/enforced from 28 Mar 2026; compliance limit 27 Mar 2027; 8 high-risk platforms must bar under-16 accounts; non-filing self-assessment = high-risk default',b:'All PSEs accessible to children incl. Meta FB/IG/Threads, AI products; age assurance + 7-dimension self-risk-assessment filed to Komdigi',a:'File PP Tunas self-assessments and lock under-16/age-assurance defaults on all ID consumer surfaces',u:'https://en.antaranews.com/news/411891/meta-raises-minimum-age-to-access-its-services-in-indonesia'},
{j:'Thailand',i:'พ.ร.บ.คุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 / Personal Data Protection Act B.E. 2562 (2019)',d:'2022-06-01',s:'Fully in force since 1 Jun 2022; active enforcement (THB 21.5m fines by Aug 2025 incl. processors; iris-data destruction order Nov 2025); admin fines to THB 5m, criminal to 1yr/THB 1m',b:'Extraterritorial: foreign controllers offering goods/services to or monitoring individuals in Thailand; directors personally liable',a:'Run DPIAs on high-risk AI uses of Thai data now; PDPA is the de-facto AI law',u:'https://practiceguides.chambers.com/practice-guides/data-protection-privacy-2026/thailand/trends-and-developments'},
{j:'Thailand',i:'ร่าง ปค. Business Operations Using AI Systems Royal Decree (ONDE/MDES) + ETDA Draft Principles of AI Law',d:'drafts 2022-2025; unenacted',s:'DRAFTS only — no binding AI law in Thailand as of Oct 2026; no enactment timeline; EU-style risk tiers, offshore high-risk providers would need a Thai local rep',b:'Would bind providers/deployers incl. offshore platforms (proposed cease orders, platform/ISP blocking)',a:'Watch item only; build to the proposed high-risk duties (risk mgmt, human oversight, incident reporting)',u:'https://www.tilleke.com/insights/comprehensive-policy-thailands-ai-governance-framework/'},
{j:'Thailand',i:'PDPC Draft Guidelines on Personal Data Protection in the Development and Use of AI',d:'2026-02-17 (draft)',s:'DRAFT — released 17 Feb 2026, 2nd consultation 13-19 Mar 2026, not final; non-binding restatement of PDPA duties for AI (roles, lawful basis, DPIAs, model-training bans in DPAs)',b:'Would guide all controllers/processors using personal data in AI development/deployment',a:'Pre-align DPAs and AI impact assessments to the draft so final text is copy-paste',u:'https://japan-thailand-law.com/en/articles/thai-digital-law-series-01en/'},
{j:'Thailand',i:'Emergency Decree on Technology Crimes (No.2) B.E. 2568 (2025) + Royal Decree on Cybercrime Measures B.E. 2568',d:'2025-04-13',s:'In force (eff. 13 Apr 2025); criminal misuse-of-personal-data offences; shared liability extended to social media platforms, telcos, financial institutions',b:'Platforms operating in Thailand — fraud/scam data misuse liability, blocking duties',a:'Confirm scam/fraud data-sharing and account-blocking cooperation with Thai authorities',u:'https://practiceguides.chambers.com/practice-guides/data-protection-privacy-2026/thailand/trends-and-developments'},
{j:'Vietnam',i:'Luật Bảo vệ dữ liệu cá nhân / Law on Personal Data Protection No. 91/2025/QH15 + Decree 356/2025/ND-CP',d:'2025-06-26 (in force 2026-01-01)',s:'In force 1 Jan 2026 (supersedes Decree 13/2023); extraterritorial; DPIA+CTIA filed with MPS within 60 days, updated 6-monthly; 72h breach notice from detection',b:'Foreign orgs directly involved in processing personal data of Vietnamese citizens; fines: 5% prior-year revenue (cross-border), 10x proceeds (data trading), VND 3bn cap',a:'Confirm A05 DPIA/CTIA filings are current under Law 91/Decree 356 templates',u:'https://english.luatvietnam.vn/dan-su/law-on-personal-data-protection-law-no-91-2025-qh15-405135-d1.html'},
{j:'Vietnam',i:'Luật Công nghiệp công nghệ số / Law on the Digital Technology Industry No. 71/2025/QH15 (AI chapter)',d:'2025-06-14 (in force 2026-01-01)',s:'In force 1 Jan 2026 (incentives from 1 Jul 2025); first binding national AI chapter in SEA: risk classification, prohibited practices incl. social scoring, machine-readable AI-output labelling, sandbox (2yrs+), 150% R&D deduction',b:'All AI developers/providers in Vietnam incl. foreign; labelling duties on AI-generated digital products',a:'Build machine-readable provenance labelling for VN-shipped generative outputs',u:'https://static3.luatvietnam.vn/uploaded/vietlawfile/2025/8/law_71_2025_qh15_incom_080825164701.pdf'},
{j:'Vietnam',i:'Luật Trí tuệ nhân tạo / Law on Artificial Intelligence No. 134/2025/QH15',d:'2025-12-10 (in force 2026-03-01)',s:'In force 1 Mar 2026; high/medium/low risk tiers; 6 prohibited-act categories; high-risk = conformity assessment + national AI registry + audits; transition 12mo (to 1 Mar 2027) / 18mo health-education-finance (to 1 Sep 2027) for pre-existing systems',b:'Foreign orgs and individuals participating in AI activities in Vietnam; sanctions: administrative or criminal + civil damages (quantum unverified)',a:'Classify all VN-facing AI features now; book conformity-assessment/registry work against 1 Mar 2027 and 1 Sep 2027',u:'https://en.baochinhphu.vn/viet-nams-law-on-artificial-intelligence-111260715113551787.htm'},
{j:'Vietnam',i:'Luật Chuyển đổi số / Law on Digital Transformation No. 148/2025/QH15',d:'2025-12-11 (in force 2026-07-01)',s:'In force 1 Jul 2026; cross-cutting consistency principles for data, e-transactions, cyber, telecom, AI fields',b:'All digital transformation actors; harmonisation clause across sectoral laws',a:'Note in VN compliance memos as the interpretive overlay for 71/2025 + 134/2025',u:'https://english.luatvietnam.vn/law-on-digital-transformation-dated-december-11-2025-of-the-national-assembly-no-148-2025-qh15-422111-doc1.html'},
{j:'Philippines',i:'Republic Act No. 10173, Data Privacy Act of 2012 (+ NPC Circular 2022-04)',d:'2012-08-15 (enforcement 2017-03)',s:'In force; extraterritorial (Sec.6); criminal penalties 6mo-6yrs + PHP 100k-4m bands; NPC Circular 2022-04 mandates DPO + data-processing-system registration (250+ staff / 1,000+ SPI / likely-risk) incl. ADM systems',b:'Foreign PICs processing data of PH citizens/residents or using equipment in PH; big-tech PH entities clear the registration thresholds',a:'Confirm NPC registration + DPO filings current; verify ADM notification where profiling feeds ranking/ads',u:'https://privacy.gov.ph/data-privacy-act/'},
{j:'Philippines',i:'NPC Advisory No. 2024-04 (DPA application to AI systems processing personal data)',d:'2024-12-19',s:'In effect since 19 Dec 2024; full AI lifecycle covered (dev/training/testing/deployment); significant-risk ADM needs meaningful human intervention + contestability',b:'PICs/PIPs using AI on PH personal data incl. foreign developers',a:'Add human-review + contest channels for significant AI decisions on PH users; PIA before AI deployment',u:'https://privacy.gov.ph/wp-content/uploads/2025/02/Advisory-2024.12.19-Guidelines-on-Artificial-Intelligence-w-SGD.pdf'},
{j:'Philippines',i:'NPC Advisory No. 2026-01 — Guidelines on Scraping Publicly Available Personal Data',d:'2026-04-13',s:'Issued 13 Apr 2026, published 21 May 2026, effective immediately; scraping = regulated processing; public availability is NOT consent; mandatory PIAs; hosts must deter scraping',b:'Foreign companies scraping/purchasing PH public personal data for AI training, lead-gen, scoring — PICs under RA 10173',a:'Audit all PH-data collection pipelines for training/ranking: PIA + lawful basis or stop',u:'https://ttfc.law/blog/2026-08-27-npc-advisory-2026-01-data-scraping-foreign-companies-philippines/'},
{j:'Philippines',i:'Republic Act No. 11967 Internet Transactions Act of 2023 + IRR (JAO 24-03)',d:'2023-12-05 (full enforcement 2025-06-21)',s:'Fully enforceable since 21 Jun 2025 (18-month transition ended 20 Jun 2025); DTI takedown/blacklist orders, subpoenas; solidary platform liability; IRR in effect since 24 May 2024',b:'B2B/B2C internet transactions where a party is in PH or platform avails of PH market with minimum contacts (extraterritorial)',a:'Verify takedown-response SLAs and vendor-liability playbook against ITA/IRR',u:'https://insightplus.bakermckenzie.com/bm/investigations-compliance-ethics/philippines-implementing-rules-of-the-internet-transactions-act-issued'},
{j:'Korea (cross-check)',i:'AI Basic Act (Act No. 20676) + Enforcement Decree',d:'2026-01-22',s:'CONFIRMED in force 22 Jan 2026; MSIT grace >=1yr (investigations/fines deferred except serious harm); Transparency Guidelines issued 22 Jan 2026',b:'AI business operators incl. foreign (domestic-rep thresholds per RUNBOOK.md — not re-verified this session)',a:'Keep: 3-part classification + Korean AI-use notice before grace expires ~Jan 2027',u:'https://www.msit.go.kr/eng/bbs/view.do?sCode=eng&mPid=2&mId=4&bbsSeqNo=42&nttSeqNo=1214'},
{j:'Australia (cross-check)',i:'Privacy and Other Legislation Amendment Act 2024 — APP 1.7-1.9 ADM transparency',d:'2026-12-10',s:'CONFIRMED commences 10 Dec 2026; OAIC fact sheet + flowchart + updated APP 1 Guidelines published 30 Sep 2026 (90 submissions)',b:'APP entities incl. private sector >A$3m turnover; privacy-policy disclosure for computer-program decisions',a:'Keep: ADM inventory + APP 1.8 privacy-policy disclosure before 10 Dec 2026',u:'https://www.oaic.gov.au/news/media-centre/new-resources-on-transparency-for-use-of-ai-and-automated-decision-making'},
{j:'China (cross-check)',i:'人工智能拟人化互动服务管理暂行办法 / Interim Measures for Administration of Anthropomorphic AI Interaction Services',d:'2026-07-15',s:'CONFIRMED issued 10 Apr 2026 (CAC+NDRC/MIIT/MPS/SAMR), in force 15 Jul 2026; 2-hour reminders, under-14 parental consent, no virtual intimacy for under-18s; fines to CNY 200,000 + public criticism',b:'Providers of anthropomorphic/emotional AI services to users in mainland China incl. foreign via JV/licensed entities',a:'Keep: route persona/companion features through the Jul 2026 checklist',u:'https://www.licentium.io/post/china-cac-interim-measures-anthropomorphic-ai-10-april-2026'},
{j:'Singapore (cross-check)',i:'Model AI Governance Framework for Agentic AI v1.5 (IMDA + AI Verify Foundation)',d:'2026-05-20',s:'CONFIRMED published 20 May 2026, updated 5 Jun 2026; voluntary, no penalties; living document, 60+ company feedback',b:'Soft law; de-facto baseline for enterprise/gov procurement of agent features in SG',a:'Keep: adopt as internal checklist for any agent feature shipped in SG',u:'https://www.imda.gov.sg/-/media/imda/files/about/emerging-tech-and-research/artificial-intelligence/mgf-for-agentic-ai.pdf'},
{j:'Singapore (cross-check)',i:'PDPA Part VIB data portability obligation',d:'legislated 2020-10-29; not commenced',s:'CONFIRMED legislated (2020 Amendment Act) but NOT in force as of 2026; implementing regulations pending; no announced commencement',b:'Would bind all organisations on commencement; zero operational duty today',a:'Keep: monitor PDPC for commencement; no build required yet',u:'https://practiceguides.chambers.com/practice-guides/data-protection-privacy-2026/singapore/trends-and-developments/O24516'}
 ];
 function esc(s){return String(s).replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
 function mount(){
  if(document.getElementById('clocks'))return;
  var host=document.querySelector('.foot, footer, .forwho, body');
  if(!host)return;
  var d=document.createElement('details');
  d.id='clocks';
  d.style.cssText='margin:14px 0;font-size:13px;line-height:1.55;border-top:1px solid currentColor;padding-top:10px';
  var rows=RULES.map(function(r){
   return '<div style="margin:8px 0"><b>'+esc(r.j)+'</b> — '+esc(r.i)+'<br>'+
    '<span style="opacity:.75">'+esc(r.d)+' · '+esc(r.s)+'</span><br>'+
    'binds: '+esc(r.b)+'<br><i>'+esc(r.a)+'</i> <a href="'+esc(r.u)+'" target="_blank" rel="noopener" '+
    'style="text-decoration:underline;text-underline-offset:3px">source</a></div>';
  }).join('');
  d.innerHTML='<summary style="cursor:pointer;font-weight:700;letter-spacing:.06em">the clocks · 9 jurisdictions · dates that bite</summary>'+
   '<p style="opacity:.8">The instruments a Meta-like APAC regulatory professional actually answers to, '+
   'Oct 2026. Dates are as fetched; 6 claims are flagged unverified in the runbook and labelled at source.</p>'+rows;
  host.appendChild(d);
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
